newrelic/newrelic-java-agent

- instrumentation/netty-reactor-0.8.0/build.gradle
This updates the instrumentation verifier since the [FluxRecieve](https://github.com/newrelic/newrelic-java-agent/blob/main/instrumentation/netty-reactor-0.8.0/src/main/java/reactor/netty/channel/FluxRecieve_Instrumentation.java#L22) instrumentation point was changed to match the latest versions of reactor-netty.
> Updated reactor-netty matches the latest versions

- newrelic-agent/src/main/java/com/newrelic/agent/service/analytics/SpanEventsServiceImpl.java
Args get passed to `recordSupportabilityMetrics` in the correct order now.
Fixes #18
> Fix span event supportability metrics

- newrelic-agent/src/main/java/com/newrelic/agent/transport/DataSenderImpl.java
- newrelic-agent/src/test/java/com/newrelic/agent/transport/DataSenderImplConnectCycleTest.java
At least two language agents always go back to their original configured host on preconnect. The Java agent will make the second round of `preconnect` on the redirect host.
This is currently causing issues because calling preconnect on the gov-collector-NNN hosts redirects you back to the collector-NNN shards. This is wrong and will cause `LicenseException` if they are prevented from allowing anything into the default backend.
This fixes that problem by always calling `preconnect` on the configured host (e.g., `gov-collector.newrelic.com`) and then updating the redirect host from there.
Auto app naming will create multiple instances of `DataSenderImpl`, so those won't conflict. This was tested by me on staging through a `ForceRestartException`.
Example of bad behavior:
```
com.newrelic …
```
> Always use configured host on preconnect

- newrelic-agent/src/main/java/com/newrelic/agent/Agent.java
- newrelic-agent/src/main/java/com/newrelic/agent/jmx/LinkingMetadata.java
- newrelic-agent/src/main/java/com/newrelic/agent/jmx/LinkingMetadataMBean.java
- newrelic-agent/src/main/java/com/newrelic/agent/jmx/LinkingMetadataRegistration.java
- newrelic-agent/src/test/java/com/newrelic/agent/jmx/LinkingMetadataRegistrationTest.java
We have a need in JFR to be able to fetch the entity guid from the agent.  This change exposes a new MBean that contains the linking metadata, so that the JFR Daemon may leverage the entity guid.
> Expose the mbean that contains the linking metadata.

- newrelic-agent/src/main/java/com/newrelic/agent/config/SystemPropertyProvider.java
- newrelic-agent/src/test/java/com/newrelic/agent/config/SystemPropertyProviderTest.java
Fixes https://github.com/newrelic/newrelic-java-agent/issues/38
> 🌶  Ignore sysprop formatted envvars and log the correct variable name

- instrumentation/akka-2.2/build.gradle
We currently don't verify akka instrumentation on scala 2.12. This changes that.
Looks like this correctly verifies akka against scala 2.12
```
> Task :instrumentation:akka-2.2:verifyInstrumentation
> Task :instrumentation:akka-2.2:verifyPass_com.typesafe.akka_akka-actor_2.12_2.6.4
> Task :instrumentation:akka-2.2:verifyPass_com.typesafe.akka_akka-actor_2.12_2.6.6
> Task :instrumentation:akka-2.2:verifyPass_com.typesafe.akka_akka-actor_2.12_2.6.7
> Task :instrumentation:akka-2.2:verifyPass_com.typesafe.akka_akka-actor_2.12_2.6.0-RC2
> Task :instrumentation:akka-2.2:verifyPass_com.typesafe.akka_akka-actor_2.12_2.6.2
> Task :instrumentation:akka-2.2:verifyPass_com.typesafe.akka_akka-actor_2.12_2.6.9
> Task :instrumentation:akka-2.2:verifyPass_com.typesafe.akka_akka-actor_2.12_2.6.8
> Task …
```
> Add verfier range for akka on scala 2.12

- instrumentation/jdbc-postgresql-9.4.1208/build.gradle
Addresses #63 < See this for failure details
Verification failed locally before the change in this PR and passes with the change:
```
~/code/newrelic-java-agent/instrumentation/jdbc-postgresql-9.4.1208 on branch fix-verifier-jdbc-postgres-9-4-1208 > ../../gradlew verifyInstrumentation --info
Resolving: org.postgresql:postgresql:9.4.1208
Resolving: org.postgresql:postgresql:9.4.1208.jre6
Resolving: org.postgresql:postgresql:9.4.1208.jre7
Resolving: org.postgresql:postgresql:9.4.1209
Resolving: org.postgresql:postgresql:9.4.1209.jre6
Resolving: org.postgresql:postgresql:9.4.1209.jre7
Resolving: org.postgresql:postgresql:9.4.1210
Resolving: org.postgresql:postgresql:9.4.1210.jre6
Resolving: org.postgresql:postgresql:9.4.1210.jre7
Resolving: org.postgresql:postgresql:9.4.1211
Resolving: …
```
> #63 Exclude Java 6 dependency from verification

- instrumentation-test/src/main/java/com/newrelic/agent/introspec/internal/IntrospectorServiceManager.java
- newrelic-agent/src/main/java/com/newrelic/agent/Agent.java
- newrelic-agent/src/main/java/com/newrelic/agent/jmx/JmxService.java
- newrelic-agent/src/main/java/com/newrelic/agent/jmx/LinkingMetadataRegistration.java
- newrelic-agent/src/main/java/com/newrelic/agent/service/ServiceManagerImpl.java
- newrelic-agent/src/test/java/com/newrelic/agent/MockServiceManager.java
- newrelic-agent/src/test/java/com/newrelic/agent/jmx/LinkingMetadataRegistrationTest.java
This resolves #61 
This moves the registration of the linking metadata mbean into the jmxservice.
I picked up a little bit of campsite cleanup around the `ServiceFactory` usage in the `JMXService` as well.
> Move linking mbean to jmxservice

- instrumentation-test/src/main/java/com/newrelic/agent/introspec/internal/IntrospectorServiceManager.java
- newrelic-agent/src/main/java/com/newrelic/agent/config/JmxConfig.java
- newrelic-agent/src/main/java/com/newrelic/agent/config/JmxConfigImpl.java
- newrelic-agent/src/main/java/com/newrelic/agent/jmx/JmxService.java
- newrelic-agent/src/main/java/com/newrelic/agent/service/ServiceManagerImpl.java
- newrelic-agent/src/test/java/com/newrelic/agent/MockServiceManager.java
This fixes #62.
We introduce a new config item `newrelic.config.jmx.linkingMetadataMBean` that, when set to true, will cause the `LinkingMetadataMBean` to be registered with the platform MBean server.  This value defaults to false (not registered).
> Add config "newrelic.config.jmx.linkingMetadataMBean"

- agent-bridge/src/main/java/com/newrelic/agent/bridge/NoOpSegment.java
- newrelic-agent/src/main/java/com/newrelic/agent/Segment.java
- newrelic-agent/src/main/java/com/newrelic/agent/attributes/AttributeValidator.java
- newrelic-agent/src/main/java/com/newrelic/agent/tracers/AbstractTracer.java
- newrelic-agent/src/test/java/com/newrelic/agent/SegmentTest.java
- newrelic-api/src/main/java/com/newrelic/api/agent/AttributeCarrying.java
- newrelic-api/src/main/java/com/newrelic/api/agent/AttributeHolder.java
- newrelic-api/src/main/java/com/newrelic/api/agent/NoOpAgent.java
- newrelic-api/src/main/java/com/newrelic/api/agent/Segment.java
- newrelic-api/src/main/java/com/newrelic/api/agent/TracedMethod.java
Change allows adding custom attributes to the tracer via a Segment.addCustomAttribute API. It assumes all instances of AbstractTracer are able to send attributes outside of a Transaction.
> Segment attribute

- infinite-tracing/src/main/java/com/newrelic/ResponseObserver.java
- infinite-tracing/src/test/java/com/newrelic/ResponseObserverTest.java
Also manually tested and works.
> add check for timeout exception

- infinite-tracing/build.gradle.kts
This works around an earlier grpc vuln.
> update to the latest protobufs for infinite tracing

- agent-bridge/src/main/java/com/newrelic/agent/bridge/NoOpTracedMethod.java
- agent-bridge/src/main/java/com/newrelic/agent/bridge/TracedMethod.java
- functional_test/src/test/java/com/newrelic/agent/bridge/MockTracer.java
- instrumentation/akka-http-2.4.5/src/main/scala/akka/http/scaladsl/server/AkkaHttpContextFunction.scala
- instrumentation/scala-2.12.0/src/main/java/scala/concurrent/impl/CallbackRunnable_Instrumentation.java
- newrelic-agent/src/main/java/com/newrelic/agent/instrumentation/tracing/FlyweightTraceMethodVisitor.java
- newrelic-agent/src/main/java/com/newrelic/agent/tracers/AbstractTracer.java
- newrelic-agent/src/main/java/com/newrelic/agent/tracers/NoOpTracer.java
- newrelic-agent/src/main/java/com/newrelic/agent/tracers/UltraLightTracer.java
- newrelic-agent/src/test/java/com/newrelic/agent/instrumentation/sql/NoOpTrackingSqlTracer.java
- newrelic-agent/src/test/java/com/newrelic/agent/tracers/AbstractTracerTest.java
Transaction context can get lost between Directives because of Akka-Https use CallbackRunnables. This change attempts to propagate that context by weaving the CallbackRunnable constructor to create a token and link it on the run() method.
Due to performance concerns, I added a trackCallbackRunnable api to the Tracer, so that we only create/link the token when coming directly from AkkaHttp. We may consider putting this behind a config and/or traversing the tracer stack and not just checking the current tracer.
Thoughts?
> Akka http fix

- newrelic-agent/src/main/java/com/newrelic/agent/utilization/CloudUtility.java
- newrelic-agent/src/test/java/com/newrelic/agent/utilization/CloudUtilityTest.java
I noticed we'd log a SocketException when attempting to connect to AWS for cloud usage data
> ignore SocketExceptions when attempting to connect to cloud providers

- newrelic-agent/src/main/java/com/newrelic/agent/InitProblemClasses.java
We sometimes infrequently see a `ClassCircularityError` when weaving, and it shows up when loading `java.util.concurrent.locks.ReentrantReadWriteLock$Sync$HoldCounter`.
This adds to existing work-arounds by forcing an early, deterministic classload for this class.
> Work around occasional ClassCircularityError 

- instrumentation/akka-http-core-10.0.11/build.gradle
- instrumentation/akka-http-core-10.0.11/src/main/scala/akka/http/DefaultParsingErrorHandler.scala
- instrumentation/akka-http-core-10.2.0/build.gradle
- instrumentation/akka-http-core-10.2.0/src/main/scala/akka/http/DefaultParsingErrorHandler.scala
`Play2Test.test_play_27` and `SnapTest.test_snap_270` AITs were failing due to both the `akka-http-core-10.0.11` and `akka-http-core-10.2.0` instrumentation modules applying and causing doubled metric counts:
`Expected {'name': 'Akka/RequestHandler', 'count': 1} `
Actual count was 2 due to the doubling.
Tests now pass:
```
(agent-integration-tests) jkeller in ~/code/agent-integration-tests on branch main > TEST_APP_OVERRIDE='play2.version=2.7.0' ./bin/runtest.sh tests/java/functionality/framework/play/play2.py Play2Test.test_play_27
runtest.sh: firing up...
runtest.sh: all tests to run tests/java/functionality/framework/play/play2.py Play2Test.test_play_27
AIT validate: start.
AIT validate: success.
runtest.sh: Python interpreter: /Users/jkeller/code/agent-integration-tests/bin/python …
```
> Fix issue causing multiple instrumentation modules to apply

- instrumentation/spring-webflux-5.1.0/build.gradle
For context see: https://github.com/newrelic/newrelic-java-agent/issues/104
> Cap spring-webflux-5.1.0 supported versions

- instrumentation/grpc-1.30.0/build.gradle
The `grpc-1.30.0` instrumentation isn't compatible with Java 1.7 and should be skipped when running instrumentation tests with the `-Ptest7` property.
```
> Task :instrumentation:grpc-1.30.0:test FAILED
BasicRequestsTest > initializationError FAILED
java.lang.UnsupportedClassVersionError at ClassLoader.java:-2
GrpcErrorsTest > initializationError FAILED
java.lang.UnsupportedClassVersionError at ClassLoader.java:-2
2 tests completed, 2 failed
```
It causes the following test failures:
```
BasicRequestsTest.initializationError
java.lang.UnsupportedClassVersionError: BasicRequestsTest : Unsupported major.minor version 52.0
GrpcErrorsTest.initializationError
java.lang.UnsupportedClassVersionError: GrpcErrorsTest : Unsupported major.minor version 52.0
```
> Prevent grpc-1.30.0 instrumentation test from running on JDK7

- instrumentation/spring-webclient-5.0/src/main/java/com/nr/agent/instrumentation/spring_webclient/Util.java
- instrumentation/spring-webclient-5.0/src/main/java/org/springframework/web/reactive/function/client/ExchangeFunction_Instrumentation.java
- instrumentation/spring-webclient-5.0/src/main/java/org/springframework/web/reactive/function/client/WebClient_Instrumentation.java
- instrumentation/spring-webclient-5.0/src/test/java/com/nr/instrumentation/ConcurrencyTest.java
The behavior being fixed: When multiple threads make HTTP calls to several URLs in parallel, the stats reported to NewRelic for one call may be recorded with URL from another call.
Root cause: The logic capturing request URLs was passing the URLs to the reporting logic (segment.reportAsExternal) using a static variable. Multiple threads were able to write and read that variable in parallel. Since a thread wrote its request URL to the variable, but before it read it back, other threads were able to overwrite it.
> Wrong URL reporting for Spring WebClient when multiple threads make requests to different URLs in parallel

- instrumentation-test/src/main/java/com/newrelic/agent/introspec/internal/IntrospectorSpanEventService.java
- newrelic-agent/src/main/java/com/newrelic/agent/service/SpanEventsServiceFactory.java
- newrelic-agent/src/main/java/com/newrelic/agent/service/analytics/TracerToSpanEvent.java
- newrelic-agent/src/test/java/com/newrelic/agent/service/analytics/SpanEventsServiceTest.java
- newrelic-agent/src/test/java/com/newrelic/agent/service/analytics/TracerToSpanEventTest.java
Context: When we process tracers to convert them to span events, we grab an error handler based off of the app name from the transaction. Since we register error handlers on startup and it’s based on the app name from the config, the transaction app name might not match the yaml app name (when auto app naming is enabled), which results in returning null for the error handler. The agent then tries to operate with it, causing an NPE and preventing the span event from reporting .
The stacktrace for this NPE looks like: 
```
2020-11-19T14:19:25,742-0600 [1886 428] com.newrelic FINER: An error occurred creating span event for tracer: com.newrelic.agent.tracers.OtherRootTracer@2f2fe363 in tx: /custom/transaction 124ms
java.lang.NullPointerException: null
at …
```
> fix span error builder

- instrumentation/netty-4.0.8/src/main/java/io/netty/bootstrap/NettyDispatcher.java
- instrumentation/netty-4.0.8/src/main/java/io/netty/handler/codec/http/HttpObjectDecoder.java
When testing the spring-webflux-5.3.1 changes, @jack-berg and I found that the initial Transaction created by Netty-4.0.8 instrumentation was never getting created. The issue is that AbstractServerBootstrap isn't always used, consequently never triggering the (re)instrumentation of NettyDispatcher::channelRead , which is the Transaction start poing
> Make sure NettyDispatcher gets initialized

- .github/workflows/unit_test.yml
- newrelic-agent/src/main/java/com/newrelic/agent/MetricNames.java
- newrelic-agent/src/main/java/com/newrelic/agent/jmx/JmxService.java
- newrelic-agent/src/main/java/com/newrelic/agent/jmx/LinkingMetadataRegistration.java
Adds a `Supportability/LinkingMetadataMBean/Enabled` metric when the agent is configured as follows:
```
jmx:
enabled: true
linkingMetadataMBean: true
```
This will help us to partially track JFR (aka RTP) usage but only when using the agent.
> Add LinkingMetadataMBean supportability metric

- newrelic-agent/src/main/java/com/newrelic/agent/service/analytics/CollectorSpanEventReservoirManager.java
Changed logging on `CollectorSpanEventReservoirManager` for dropped spans from warn to fine
https://github.com/newrelic/newrelic-java-agent/issues/176
existing tests. 
[ yes] Are your contributions backwards compatible with relevant frameworks and APIs?
[ no] Does your code contain any breaking changes? Please describe. 
[ no] Does your code introduce any new dependencies? Please describe.
> change dropped span log level to fine

- newrelic-agent/src/main/java/com/newrelic/agent/config/JarCollectorConfig.java
- newrelic-agent/src/main/java/com/newrelic/agent/config/JarCollectorConfigImpl.java
- newrelic-agent/src/main/java/com/newrelic/agent/service/module/JarCollectorServiceProcessor.java
- newrelic-agent/src/test/java/com/newrelic/agent/config/JarCollectorConfigImplTest.java
- newrelic-agent/src/test/java/com/newrelic/agent/service/module/JarCollectorServiceProcessorTest.java
> add configurable rate limiter for jar collector processing

- newrelic-agent/src/test/java/com/newrelic/agent/threads/ThreadStateSamplerTest.java
Hmm `ThreadStateSamplerTest` seems to flicker pretty badly. The test passes locally but seems to fail consistently when run on PRs. I’ve seen numerous failures on a PR that doesn’t even touch agent functionality.
```
com.newrelic.agent.threads.ThreadStateSamplerTest > testCpuTimeMetrics FAILED
java.lang.AssertionError at ThreadStateSamplerTest.java:57
```
The assertion looks to be:
```
assertTrue("TotalTime: " + totalTimeSeconds + ", SystemTime: " + systemTimeSeconds + ", UserTime: " + userTimeSeconds,
totalTimeSeconds + 0.2 >= systemTimeSeconds + userTimeSeconds); // account for rounding error
```
> Fix ThreadStateSamplerTest flicker

- instrumentation/jdbc-ojdbc7-12.1.0.2/build.gradle
It looks like the instrumentation verifier failed on our `jdbc-ojdbc7-12.1.0.2` instrumentation module. This appears to be due to a breaking change in [version 21.1.0.0 of ojdbc8](https://mvnrepository.com/artifact/com.oracle.database.jdbc/ojdbc8/21.1.0.0).
This PR caps the `ojdbc8` support at the breaking version and also adds `ojdbc10` to the verifier for this instrumentation.
```
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':instrumentation:jdbc-ojdbc7-12.1.0.2:verifyPass_com.oracle.database.jdbc_ojdbc8_21.1.0.0'.
> A failure occurred while executing com.newrelic.agent.instrumentation.verify.VerifyWorkAction
> Verification FAILED. Instrumentation module jdbc-ojdbc7-12.1.0.2-1.0.jar SHOULD HAVE applied to com.oracle.database.jdbc:ojdbc8:21.1.0.0 …
```
> Cap ojdbc8 support range to fix verifier

- infinite-tracing/src/main/java/com/newrelic/ChannelManager.java
- infinite-tracing/src/main/java/com/newrelic/ResponseObserver.java
- infinite-tracing/src/test/java/com/newrelic/ChannelManagerTest.java
- infinite-tracing/src/test/java/com/newrelic/ResponseObserverTest.java
Fix a race condition in infinite tracing involving `SpanEventSender` and `ResponseObserver`:
- SpanEventSender obtains an observer via `ChannelManager#getSpanObserver()`
- SpanEventSender does some work, and eventually writes a Span to the observer
- However, the observer has already been cancelled by  ResponseObserver#onCompleted, which cancels the observer
The fix is to have ResponseObserver not directly cancel the observer, but instead mark it as needing recreation, where its recreated the next time SpanEventSender gets an observer from the channel manager. In doing so, SpanEventSender shouldn't be able to write to a cancelled observer, since any cancelling and recreation of observers happens in a blocking fashion during its call to ChannelManager#getSpanObserver(), and never in a …
> fix infinite tracing race condition regarding span observer

- instrumentation/build.gradle
The weaver [loads & caches each instrumentation module](https://github.com/newrelic/newrelic-java-agent/blob/main/newrelic-weaver/src/main/java/com/newrelic/weave/weavepackage/CachedWeavePackage.java#L162-L189) by locating the instrumentation module jar and reading in the bytes for the all of the classes contained in the module.
However it appears that the weaver depends on the classes being read in from the JarInputStream in a specific and predictable order, meaning that the instrumentation module jar files need to be generated in a deterministic manner. 
This PR modifies the build task for the instrumentation modules so that the resulting jar file always adds files in a reproducible order.
---
One notable example is the `jax-rs-1.0` instrumentation, which could fail with a …
> Reproducible build

- instrumentation/netty-reactor-0.7.0/NOTICE.txt
- instrumentation/netty-reactor-0.7.0/src/main/java/com/nr/instrumentation/TokenLinkingSubscriber.java
- instrumentation/netty-reactor-0.8.0/NOTICE.txt
- instrumentation/netty-reactor-0.8.0/src/main/java/com/nr/instrumentation/reactor/netty/TokenLinkingSubscriber.java
- instrumentation/netty-reactor-0.9.0/NOTICE.txt
- instrumentation/netty-reactor-0.9.0/src/main/java/com/nr/instrumentation/reactor/netty/TokenLinkingSubscriber.java
- instrumentation/spring-webflux-5.0.0/NOTICE.txt
- instrumentation/spring-webflux-5.0.0/src/main/java/org/springframework/web/reactive/DispatchHandler_Instrumentation.java
- instrumentation/spring-webflux-5.1.0/NOTICE.txt
- instrumentation/spring-webflux-5.1.0/src/main/java/org/springframework/web/reactive/DispatchHandler_Instrumentation.java
- instrumentation/spring-webflux-5.3.0/NOTICE.txt
- instrumentation/spring-webflux-5.3.0/src/main/java/org/springframework/web/reactive/DispatchHandler_Instrumentation.java
The OpenTelemetry default branch name was updated. Additionally, `TracingSubscriber.java` was moved to another location.
> Update and fix OpenTelemetry URLs

- newrelic-agent/src/main/java/com/newrelic/agent/config/AgentConfigHelper.java
- newrelic-agent/src/main/java/com/newrelic/agent/config/PointCutConfig.java
- newrelic-agent/src/main/java/com/newrelic/agent/extension/ExtensionParsers.java
- newrelic-agent/src/main/java/com/newrelic/agent/instrumentation/yaml/InstrumentationConstructor.java
- newrelic-agent/src/test/java/com/newrelic/agent/config/PointCutConfigTest.java
- newrelic-agent/src/test/java/com/newrelic/agent/instrumentation/yaml/InstrumentationConstructorTest.java
- newrelic-agent/src/test/java/com/newrelic/agent/jmx/create/JmxYmlParserTest.java
Switches everything over to use [SafeConstructor](https://www.javadoc.io/doc/org.yaml/snakeyaml/1.27/org/yaml/snakeyaml/constructor/SafeConstructor.html) (Construct standard Java classes) instead of [Constructor](https://www.javadoc.io/doc/org.yaml/snakeyaml/1.27/org/yaml/snakeyaml/constructor/Constructor.html) (Construct a custom Java instance).
AIT: https://javaagent-build.pdx.vm.datanerd.us/view/All/job/JavaAgent_PR_AIT/55/
> Refactor to use SafeConstructor for SnakeYAML

- instrumentation/netty-reactor-0.8.0/src/main/java/com/nr/instrumentation/reactor/netty/TokenLinkingSubscriber.java
- instrumentation/netty-reactor-0.8.0/src/test/java/com/nr/agent/instrumentation/TransactionPropagationTest.java
- instrumentation/netty-reactor-0.9.0/src/main/java/com/nr/instrumentation/reactor/netty/TokenLinkingSubscriber.java
- instrumentation/netty-reactor-0.9.0/src/test/java/com/nr/agent/instrumentation/TransactionPropagationTest.java
This PR fixes two issues with the project reactor instrumentation
- Transaction is not propagated to Mono.doOnSuccess and Flux.doOnComplete
- Transaction is lost after Mono.retry* re-subscribes while handling an error
> Fix of transaction propagation for empty mono/flux and retry operators

- instrumentation/netty-reactor-0.9.0/src/main/java/reactor/core/publisher/LambdaMonoSubscriber_Instrumentation.java
- instrumentation/netty-reactor-0.9.0/src/main/java/reactor/core/publisher/LambdaSubscriber_Instrumentation.java
- instrumentation/netty-reactor-0.9.0/src/test/java/com/nr/agent/instrumentation/TransactionPropagationTest.java
Fix of lambda subscribers instrumentation to call original instrumented methods and expire token in case of errors
> Fix of reactor lambda subscribers instrumentation

- instrumentation/java.completable-future-jdk8u40/src/main/java/java/util/concurrent/CompletableFuture_Instrumentation.java
In writing an integration test for the Java11 HttpClient Instrumentation PR, this bug was surfaced.
For every request made with the Java 11 HttpClient, numerous unexpired tokens were being created by the CompletableFutures instrumentation.  These tokens would timeout on their own - after a default 180 seconds.  This would prolong the time it takes to end the transaction and it can appear to a customer that these transactions never occurred, causing confusion and delay. 🚂 
There is a helpful supportability metric detailing where an unexpired token was created. Using that, I tracked down a code path to check for unexpired tokens and expire them. The image below shows a test run without this fix and with. The red box indicates the time for the fix being tested.
> catch unexpired tokens in postFire

- instrumentation/netty-reactor-0.7.0/build.gradle
- instrumentation/netty-reactor-0.8.0/build.gradle
- instrumentation/netty-reactor-0.9.0/build.gradle
This commit disables the netty-reactor instrumentation tests from running in Java 7.
All the supported netty-reactor versions require Java 8+, which causes problems when running with Java 7.
Are your contributions backwards compatible with relevant frameworks and APIs?
Yes.
Does your code contain any breaking changes? Please describe. 
No.
Does your code introduce any new dependencies? Please describe.
No.
> Disable netty-reactor instrumentation modules from running in Java 7

- newrelic-agent/src/main/java/com/newrelic/agent/instrumentation/context/InstrumentationContextManager.java
- newrelic-agent/src/main/java/com/newrelic/agent/instrumentation/context/TraceByReturnTypeMatchVisitor.java
- newrelic-agent/src/test/java/com/newrelic/agent/instrumentation/classmatchers/TraceByReturnTypeMatchVisitorTest.java
- newrelic-api/src/main/java/com/newrelic/api/agent/TraceByReturnType.java
- newrelic-weaver-scala/build.gradle
- newrelic-weaver-scala/src/test/scala/com/nr/weave/weavepackage/language/scala/TraceByReturnTypeVisitorTest.scala
New class annotation TraceByReturnType. Marking a class with the TraceByReturnType annotation will instruct the New Relic agent to automatically annotate methods with return type matching any class specified in `TraceByReturnType#traceReturnTypes`
Added unit tests to cover TraceByReturnType usage scenarios with Java and Scala.
Deploy updated agent locally and reviewed traces in New Relic One.
[x] Does your code contain any breaking changes? Please describe. 
[x] Does your code …
> Class annotation to trace methods by return type

- instrumentation/jdbc-mariadb-1.3.0/build.gradle
Why this is necessary is in this issue #293
> cap to last version successfully instrumented

- newrelic-agent/src/main/java/com/newrelic/agent/errors/ErrorServiceImpl.java
- newrelic-agent/src/main/java/com/newrelic/agent/service/analytics/InsightsServiceImpl.java
We already log about dropped span events at FINE, this PR does the same for error and insights/custom events instead of logging them at WARN to decrease log verbosity.
```
"Dropped {0} span events out of {1}."
"Dropped {0} error events out of {1}."
"Dropped {0} custom events out of {1}."
```
> Changed dropped events to log at FINE instead of WARN

- instrumentation/akka-http-core-2.13_10.1.8/build.gradle
- instrumentation/akka-http-core-2.13_10.1.8/src/main/scala/akka/http/scaladsl/HttpInstrumentation.java
- instrumentation/akka-http-core-2.13_10.2.0/build.gradle
- instrumentation/akka-http-core-2.13_10.2.0/src/main/scala/akka/http/scaladsl/HttpExtInstrumentation.java
- instrumentation/akka-http-core-2.13_10.2.0/src/main/scala/akka/http/scaladsl/HttpInstrumentation.java
When running a Play 2.8.5/Scala 2.13 app I noticed that multiple versions of the `akka-http-core` instrumentation were being applied:
```
com.newrelic.instrumentation.jdbc-socket - validated classloader BootstrapPlaceholder
com.newrelic.instrumentation.scala-2.13.0 - validated classloader sun.misc.Launcher$AppClassLoader@18b4aac2
com.newrelic.instrumentation.akka-2.2 - validated classloader sun.misc.Launcher$AppClassLoader@18b4aac2
com.newrelic.instrumentation.play-2.7 - validated classloader sun.misc.Launcher$AppClassLoader@18b4aac2
com.newrelic.instrumentation.akka-http-core-2.13_10.1.8 - validated classloader sun.misc.Launcher$AppClassLoader@18b4aac2
com.newrelic.instrumentation.akka-http-core-2.13_10.2.0 - validated classloader sun.misc.Launcher$AppClassLoader@18b4aac2 …
```
> Prevent multiple versions of akka-http-core instrumentation from applying.

- agent-bridge/src/main/java/com/newrelic/agent/bridge/PublicApi.java
- newrelic-api/src/main/java/com/newrelic/api/agent/NewRelic.java
javadoc erroneously indicated that first error in noticeError call is the one that is reported.
Last error is in fact the one reported.
https://github.com/newrelic/newrelic-java-agent/issues/305
This change updates the comments so the javadoc correctly states that the last error will be reported.
> update all 1st error to last error reported

- newrelic-agent/build.gradle
On the 7.0.0 release, an indirect dependency to okhttp (4.8) was introduced to the agent.
This dependency was not shadowed, so it shared the same namespace of any customers' dependencies to older versions of okhttp, which caused errors on their end.
This commit instructs the shadower to change those classes so they are in a different namespace (package).
As an added bonus, this will also prevent the weaver to change these classes.
Resolves https://github.com/newrelic/newrelic-java-agent/issues/324
This change cannot be tested in this project, as it requires different versions of the same dependency to be loaded at the same time.
[N] Does …
> Fix okhttp dependency clash

- instrumentation/spring-ws-2.0/build.gradle
Instrumentation verifier [failed](https://javaagent-build.pdx.vm.datanerd.us/job/JavaAgent_Verify_Instrumentation/1953/consoleText) for the spring-ws-2.0 instrumentation on `org.springframework.ws:spring-ws-core:3.1.0` but then passes again for `org.springframework.ws:spring-ws-core:3.1.1`.
Hopefully it was a one off thing for that version but we'll want to keep an eye on it.
Failure was:
```
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':instrumentation:spring-ws-2.0:verifyPass_org.springframework.ws_spring-ws-core_3.1.0'.
> A failure occurred while executing com.newrelic.agent.instrumentation.verify.VerifyWorkAction
> Verification FAILED. Instrumentation module spring-ws-2.0-1.0.jar SHOULD HAVE applied to …
```
> Exclude spring-ws-core 3.1.0 from being verified against spring-ws-2.0 instrumentation

- newrelic-agent/src/main/java/com/newrelic/agent/config/JfrConfigImpl.java
- newrelic-agent/src/main/resources/newrelic.yml
Changing JFR to be on by default and updating `newrelic.yml`.
#329 
Are your contributions backwards compatible with relevant frameworks and APIs?
Yes
Does your code contain any breaking changes? Please describe. 
No
Does your code introduce any new dependencies? Please describe.
No
> JFR on-by-default

- newrelic-agent/build.gradle
- newrelic-agent/src/main/java/com/newrelic/agent/ThreadService.java
- newrelic-agent/src/main/java/com/newrelic/agent/jfr/JfrService.java
- newrelic-agent/src/main/java/com/newrelic/agent/threads/ThreadNameNormalizer.java
- newrelic-agent/src/test/java/com/newrelic/agent/jfr/JfrServiceTest.java
The new version of jfr-core groups some metrics and event on thread name to decrease the amount of data sent to NR.
Are your contributions backwards compatible with relevant frameworks and APIs?
Yes
Does your code contain any breaking changes? Please describe. 
No
Does your code introduce any new dependencies? Please describe.
It updates the dependency on jfr-daemon
> Enabling JFR's thread name normalizer

- instrumentation/anorm-2.0/build.gradle
- instrumentation/anorm-2.3/build.gradle
- instrumentation/anorm-2.4/build.gradle
- instrumentation/play-2.3/build.gradle
- instrumentation/play-2.4/build.gradle
- instrumentation/play-2.5/build.gradle
- instrumentation/play-2.6.13/build.gradle
- instrumentation/play-2.6/build.gradle
- instrumentation/play-2.7/build.gradle
anorm and play instrumentation module dependencies do not resolve through bintray and the agent does not compile and build
This removes dl.bintray.  Also, this removes jcenter because it goes away Feb 2022. 
A few of the module's dependencies had to be updated. They are not available on jcenter or mavenCentral.
> remove bintray and jcenter, update dependency versions

- functional_test/src/test/java/com/newrelic/agent/instrumentation/pointcuts/net/HttpURLConnectionTest.java
These tests were making external calls to the `newrelic.com` domain and failing on Java 9 & 10.
The assertion failures were because not all of the expected `External` metrics were being generated:
```
External/allOther
External/newrelic.com/all
External/all
External/newrelic.com/HttpURLConnection
```
The underlying cause seemed to be related to SSL cert issues only present on Java 9 & 10.
```
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```
It's a bad idea to repeatedly hit the `newrelic.com` domain in tests in the first place and switching it to `example.com`, which is a domain dedicated for testing, resolved …
> Fix errors related to newrelic.com domain

- instrumentation/sttp-2.13_3.0.0/build.gradle
This instrumentation module was supposed to be verifying against Scala 2.13 instead of 2.12. All versions pass now.
> Correctly verify against Scala 2.13 instead of 2.12

- instrumentation/jedis-3.0.0/build.gradle
Exclude `redis.clients:jedis:3.6.2` from verification as there is something weird about that version that causes failures.
> Exclude problematic artifact for jedis-3.0.0 instrumentation verifier

- instrumentation/http4s-blaze-client-2.12_0.22/build.gradle
- instrumentation/http4s-blaze-client-2.13_0.22/build.gradle
Cap `http4s-blaze-client-2.12_0.22` and `http4s-blaze-client-2.13_0.22` instrumentation supported versions to prevent verifier failures.
Full context here: https://github.com/newrelic/newrelic-java-agent/issues/429
> Cap http4s-blaze-client instrumentation range

- instrumentation/grpc-1.30.0/build.gradle
Cap `grpc-1.30.0` instrumentation supported version to prevent verifier failures.
Full context here: https://github.com/newrelic/newrelic-java-agent/issues/427
> Cap grpc-1.30.0 supported version

- newrelic-weaver-scala/src/test/scala/com/nr/weave/weavepackage/language/scala/ScalaAdapterTest.scala
- test-annotations/src/main/java/com/newrelic/test/marker/Java16IncompatibleTest.java
Additional work will need to be done for the ScalaAdapterTest to be compatible with Java11+ . That work is being tracked #438
> mark test as incompatible with java 11+

- gradle/wrapper/gradle-wrapper.properties
https://docs.gradle.org/6.9.1/release-notes.html#backports
```
Limited support for Java 16
This release does not support running Gradle with JDK 16, but you can use Java toolchains to request Java 16 and compile your project.
```
https://docs.gradle.org/6.8.3/release-notes.html#composite-builds-improvements
```
Composite builds improvements
```
https://docs.gradle.org/6.8.3/release-notes.html#java-toolchain-improvements
```
Java toolchain improvements
```
> Update to gradle 6.9.1

- settings.gradle
We are going to need to use 'tags' to distinguish builds/tests easily.  Once again, I can't even test this out easily on GHA without it being on main.  Even testing with just instrumentation tests gets difficult to tell them apart pretty quickly.
> Add tags to Gradle build scan

- instrumentation/http4s-blaze-server-2.12_0.21/src/main/scala/com/nr/instrumentation/http4s/TransactionMiddleware.scala
- instrumentation/http4s-blaze-server-2.12_0.21/src/test/scala/com/nr/http4s/BlazeServerBuilderTest.scala
- instrumentation/http4s-blaze-server-2.13_0.21/src/main/scala/com/nr/instrumentation/http4s/TransactionMiddleware.scala
- instrumentation/http4s-blaze-server-2.13_0.21/src/test/scala/com/nr/http4s/BlazeServerBuilderTest.scala
This pr moves creation of the transaction to happen when the request is actually run and not during the construction of the effect itself. This seems to cause invalid tracer states and nullpointer exceptions in one of our application that uses cats effect and Doobie. 
This fix is only an assumption as debugging/reproducing this is relatively time consuming. 
According to how cats effect support is implemented the transaction creation should be delayed which is done by wrapping that into `Sync.delay(AgentBridge.instrumentation.createScalaTxnTracer())`. This works because delay take a call by name parameter. However, the construct helper method takes a call by value parameter and therefor circumvents the lazy evaluation of creating the transaction. 
In our application I believe that this …
> Ensure Http4s transaction tracer is lazy

- instrumentation/cassandra-datastax-3.0.0/src/main/java/com/datastax/driver/core/NewRelicChainedResultSetFuture.java
- instrumentation/cassandra-datastax-3.0.0/src/test/java/com/nr/agent/instrumentation/cassandra/CassandraTest.java
- instrumentation/cassandra-datastax-3.8.0/src/main/java/com/datastax/driver/core/NewRelicChainedResultSetFuture.java
- instrumentation/cassandra-datastax-3.8.0/src/test/java/com/nr/agent/instrumentation/cassandra/CassandraTest.java
A wrapped statement is a class that the driver supplies to support custom Retry and LoadBalancing policies.
If developers implement and extend [com.datastax.driver.core.StatementWrapper](https://docs.datastax.com/en/drivers/java/3.0/com/datastax/driver/core/StatementWrapper.html) as part of a custom Retry or LoadBalancing policy, the statements were being rejected as ```unsupported statement type```.
Changes include:
* checking if the statement is a WrappedStatement
* if it is, get the statement that is being wrapped and use it as the Query to use for metrics. Otherwise use the original statement.
* Unit tests to verify Wrapped statements work
* Applied to version 3.0.0 and 3.8.0 of the Datastax driver. (This class looks like it may have been present in some version of 2.0 - but not in …
> Provide support for Datastax/Cassandra WrappedStatments.

- newrelic-agent/src/main/java/com/newrelic/agent/errors/ThrowableError.java
- newrelic-agent/src/test/java/com/newrelic/agent/errors/TracedErrorTest.java
Adds suppressed exceptions (`Throwable.getSuppressed()`) to stack traces extracted from Throwables
This resolves #399 
[ Yes ] Are your contributions backwards compatible with relevant frameworks and APIs?
[ No ] Does your code contain any breaking changes? Please describe. 
[ No ] Does your code introduce any new dependencies? Please describe.
> Add suppressed exceptions to ThrowableError.stackTrace

- .github/workflows/GHA-AIT-functionality-basic_features--datastore-tests.yaml
- .github/workflows/GHA-AIT-functionality-framework-tests.yaml
- .github/workflows/GHA-AIT-functionality-security-tests.yaml
- .github/workflows/GHA-AIT-functionality-server-tests.yaml
- .github/workflows/GHA-AIT-functionality-trace-tests.yaml
- .github/workflows/GHA-Functional-Tests.yaml
- .github/workflows/GHA-Instrumentation-Tests.yaml
- .github/workflows/GHA-Scala-Functional-Tests.yaml
- .github/workflows/GHA-Scala-Instrumentation-Tests.yaml
- .github/workflows/GHA-Unit-Tests.yaml
- .github/workflows/Java-11-Instrumentation-Tests.yml
- .github/workflows/Java-17-Instrumentation-Tests.yml
- .github/workflows/Java-8-Instrumentation-Tests.yml
- .github/workflows/X-Reusable-Test.yml
- instrumentation/newrelic-scala-monix-api/build.gradle
- instrumentation/play-2.3/build.gradle
- newrelic-scala-monix-api/build.gradle.kts
Remove unneeded newrelic-api dependency from Play 2.3.
Add zinc compiler version to monix-api instrumentation.
Add zinc compiler version and fixed scala library version to monix-api.
Exclude Monix API from unit test workflow. 
**All other workflow changes are not needed, they are to run against the latest and showcase passing tests without merging to main.**
Running GHA tests. All passing.
[X] Does your code contain any breaking changes? Please describe.  No
> Monix build fix - Include Zinc and fix play dependencies

- instrumentation/cats-effect-3/src/main/java/cats/effect/internals/Utils.java
- instrumentation/newrelic-cats-effect3-api/src/main/scala/com/newrelic/cats3/api/TraceOps_Instrumentation.scala
- instrumentation/newrelic-cats-effect3-api/src/main/scala/com/newrelic/cats3/api/Util.scala
- newrelic-cats-effect3-api/src/main/scala/com/newrelic/cats3/api/TraceOps.scala
- newrelic-cats-effect3-api/src/test/scala/com/newrelic/cats3/api/CatsEffectIOTest3.scala
This is a change to the newrelic scala cats 3 api. The change ensures transaction and current token information is passed by parameters rather than ThreadLocal variables. Parameters used are [implicit](https://docs.scala-lang.org/tour/implicit-parameters.html), this helps to keep API changes to a minimum
#406
Github Actions when a pull request is made. More details on …
> cats effect 3: pass transaction info by implicits

- instrumentation/async-http-client-2.0.0/build.gradle
Updated Async-Http-Client library version to 2.0.35 to address the security issue
https://snyk.io/vuln/maven:org.asynchttpclient%3Aasync-http-client
AsyncHttpClient/async-http-client#1455
https://github.com/newrelic/newrelic-java-agent/issues/444
Ran unit tests and verify instrumentation on a branch
[X] Are your contributions backwards compatible with relevant frameworks and APIs?  Yes
[X] Does your code contain any breaking changes? Please describe. No
[X] Does your code introduce any new dependencies? Please describe. Yes, upgraded Async-Http-Client library version to 2.0.35
> Updated Async-Http-Client library version to 2.0.35

- newrelic-agent/build.gradle
Caching with Caffeine can expose a bug in the JDK where the ForkJoinPool.commonPool (FJP) does not initialize appropriately.  With Caffeine this caused a resulting OOM when the caches were not being evicted.  Improvements were made for more aggressive eviction when there is a broken executor. 
This change mitigates the effect caused by the broken commonPool, by helping to avoid an OOM.  Of course, the broken FJP may have other negative effects.
https://bugs.openjdk.java.net/browse/JDK-8274349 v17.02 -fixed
https://bugs.openjdk.java.net/browse/JDK-8274756 v18 -fixed
Primarily taking this dependency update for this commit:
https://github.com/ben-manes/caffeine/commit/8c7160d008730b68974227b7d988362a4bc974d3
>Fixed reference eviction when used …
> update caffeine dep

- newrelic-agent/src/main/java/com/newrelic/agent/InitProblemClasses.java
We were pretty regularly (but not every time) getting a `ClassCircularityError` when running tests for
https://github.com/newrelic/newrelic-java-agent/pull/576
This looks like a similar issue that used to happen with Guava, though it presented in a different class.
It may make more sense to find out why this happens during Weaving and see if we can find a root cause, but I believe (based on the previous issue history and notes) that it would be a considerable effort.  If we go that route, we should get this on the Engineering Board and prioritized.
This workaround should at least get us moving forward for this case. It's a workaround that's been implemented before, so there's some precedence for it. 
This change forces an early deterministic classload for ThreadLocalRandom.  It is …
> work-around ClassCircularityError

- newrelic-agent/src/main/java/com/newrelic/agent/ThreadService.java
- newrelic-agent/src/main/java/com/newrelic/agent/attributes/DefaultDestinationPredicate.java
- newrelic-agent/src/main/java/com/newrelic/agent/database/CachingDatabaseStatementParser.java
- newrelic-agent/src/main/java/com/newrelic/agent/instrumentation/weaver/extension/ExtensionHolderFactoryImpl.java
- newrelic-agent/src/main/java/com/newrelic/agent/profile/v2/DiscoveryProfile.java
- newrelic-agent/src/main/java/com/newrelic/agent/profile/v2/Profile.java
- newrelic-agent/src/main/java/com/newrelic/agent/profile/v2/TransactionProfile.java
- newrelic-agent/src/main/java/com/newrelic/agent/profile/v2/TransactionProfileSessionImpl.java
- newrelic-agent/src/main/java/com/newrelic/agent/service/analytics/InsightsServiceImpl.java
- newrelic-agent/src/main/java/com/newrelic/agent/service/analytics/TransactionEventsService.java
- newrelic-agent/src/main/java/com/newrelic/agent/service/async/AsyncTransactionService.java
- newrelic-agent/src/main/java/com/newrelic/agent/sql/BoundedConcurrentCache.java
- newrelic-agent/src/main/java/com/newrelic/agent/threads/ThreadStateSampler.java
- newrelic-agent/src/main/java/com/newrelic/agent/tracers/metricname/MetricNameFormats.java
- newrelic-agent/src/main/java/com/newrelic/agent/transaction/TransactionCache.java
- newrelic-agent/src/main/java/com/newrelic/agent/util/AgentCollectionFactory.java
- newrelic-agent/src/main/java/com/newrelic/bootstrap/EmbeddedJarFilesImpl.java
- newrelic-agent/src/test/java/com/newrelic/agent/extension/DependencyRemapperTest.java
- newrelic-weaver/src/main/java/com/newrelic/weave/weavepackage/WeavePackageManager.java
By default Caffeine uses `ForkJoinPool.commonPool()`. When running Java 17, usage of `ForkJoinPool` early in the agent's life cycle may trigger an initialization failure which causes the pool to become non-functional. This may produce out-of-memory errors as well as functional errors in the instrumented application. See #558 for details.
_Note:_ this PR updates only caches for which some cleanup/expiry policy exists, as (IIUC) instances created using "just" `Caffeine.newBuilder().build(someLoader)` don't use the configured executor anyway. If I got that wrong, please let me know and I'll update also the remaining usages. (And if I got it right, please double-check that I didn't miss any.)
> Configure Caffeine caches with a same-thread executor

- newrelic-agent/build.gradle
log4j-core version bump to fix CVE-2021-44228
> Upgrade log4j-core version bump to fix CVE-2021-44228

- newrelic-scala-api/build.gradle.kts
Resolves build issue locally when running `./gradlew clean jar`.
Updated newrelic-scala-api scala-library dependency to 2.13.7
None
Ran command locally with success.
Ran green GHA builds
[X] Does your code contain any breaking changes? Please describe.  No
[X] Does your code introduce any new dependencies? Please describe. Updated newrelic-scala-api  scala-library dependency to 2.13.7
> Newrelic-scala-api scala-library to 2.13.7 - Local build issue

- newrelic-agent/build.gradle
Bumping to version 2.16.0 to users are protected from potential bypasses existing in pattern formatters.
Apache's patch notes for 2.16.0:
`The mitigation advice for CVE-2021-4428 suggests that for Log4j > 2.10.0 and < 2.15.0, the vulnerability can be avoided by setting -Dlog4j2.formatMsgNoLookups=true or upgrading to 2.15.0. However, many users may not be aware that even in this case, lookups used in pattern formatters to provide specific pieces of context information will still recursively resolve, possibly triggering JNDI lookups.`
REF: https://issues.apache.org/jira/plugins/servlet/mobile#issue/LOG4J2-3221
Issue Link: https://github.com/newrelic/newrelic-java-agent/issues/605
> Upgrade log4j-core version bump 2.16.0

- newrelic-agent/src/main/java/com/newrelic/agent/tracers/servlet/QueueTimeTracker.java
This message is logged by default with customer input. Push this down to a non-default log level.
> Reduce logging granularity

- newrelic-agent/build.gradle
This PR upgrades `log4j-core` to the latest version (`2.17.0`) to protect from uncontrolled recursion from self-referential lookups, fixing [CVE-2021-45105](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-45105) relevant for Java 8 and later.
References: 
https://logging.apache.org/log4j/2.x/security.html
https://issues.apache.org/jira/browse/LOG4J2-3230
#605 
#603 
#610
> Upgrade log4j-core version to fix CVE-2021-45105

- newrelic-agent/src/main/java/com/newrelic/agent/config/AgentConfigImpl.java
Small optimization reducing regex compilation (`String.replaceAll`) on every method call.
> optimization: change String.replaceAll in favor of Pattern.compile

- instrumentation/solr-jmx-7.0.0/src/main/java/com/agent/instrumentation/solr/CacheMetric.java
- instrumentation/solr-jmx-7.0.0/src/main/java/com/agent/instrumentation/solr/GaugeMetric.java
- instrumentation/solr-jmx-7.0.0/src/main/java/com/agent/instrumentation/solr/MeteredMetric.java
- instrumentation/solr-jmx-7.0.0/src/main/java/com/agent/instrumentation/solr/MetricUtil.java
- instrumentation/solr-jmx-7.0.0/src/main/java/com/agent/instrumentation/solr/NRMetric.java
- instrumentation/solr-jmx-7.0.0/src/main/java/org/apache/solr/metrics/SolrMetricManager_Instrumentation.java
- instrumentation/solr-jmx-7.0.0/src/test/java/com/agent/instrumentation/solr/SolrMetricManagerInstrumentationTests.java
- instrumentation/solr-jmx-7.4.0/src/main/java/com/agent/instrumentation/solr/CacheMetric.java
- instrumentation/solr-jmx-7.4.0/src/main/java/com/agent/instrumentation/solr/GaugeMetric.java
- instrumentation/solr-jmx-7.4.0/src/main/java/com/agent/instrumentation/solr/MeteredMetric.java
- instrumentation/solr-jmx-7.4.0/src/main/java/com/agent/instrumentation/solr/MetricUtil.java
- instrumentation/solr-jmx-7.4.0/src/main/java/com/agent/instrumentation/solr/NRMetric.java
- instrumentation/solr-jmx-7.4.0/src/main/java/org/apache/solr/metrics/SolrMetricManager_Instrumentation.java
- instrumentation/solr-jmx-7.4.0/src/test/java/com/agent/instrumentation/solr/SolrMetricManagerInstrumentationTests.java
Currently, the `SolrMetricManager` instrumentation in the `solr-jmx-7.0.0` and `solr-jmx-7.4.0` projects maintains a map of all tracked metrics using the `MetricUtil` class.
The SolrMetricManager instrumentation currently doesn't support removing metrics causing a memory leak.
This pull request adds additional instrumentation to the `SolrMetricManager` class to support removing metrics and renaming registries. It also reduces the memory footprint of the `NRMetric` class by replacing the `SolrInfoBean` used internally with a string. `SolrInfoBean` is only used to get the name of the bean which is now past directed as a string.
https://github.com/newrelic/newrelic-java-agent/issues/355
Ran verifyInstrumentation successfully.
Ran GHA build checks successfully.
Added SolrMetricManager unit …
> #355 - Solr FilterCache Memory Leak - Replace SolrInfoBean in NRMetric with String

- newrelic-agent/build.gradle
Upgrade log4j-core version to fix vulnerability (CVE-2021-44832)
[See More](https://logging.apache.org/log4j/2.x/security.html)
#624
> Upgrade log4j-core version to fix vulnerability (CVE-2021-44832)

- newrelic-agent/src/main/java/com/newrelic/agent/tracers/DefaultSqlTracer.java
- newrelic-agent/src/test/java/com/newrelic/agent/tracers/DefaultSqlTracerTest.java
When recreating a "raw" query from a PreparedStatement, the values from the params were added to the "raw" query without escaping any quotes inside of it.
This caused some problems later on when the obfuscator would try to match the quotes to remove any value in the query.
Fixed by escaping single quotes (unless it was already escaped using a `\`) prior to adding values to the "raw" query.
#568 
Tests were added to verify the quotes were being properly escaped.
> SqlObfuscator does not obfuscate certain html documents

- instrumentation/mongodb-async-4.0/src/test/java/com/nr/agent/instrumentation/mongodb/MongoDbAsync400Test.java
Lowered the MongoDB version to one defined in a `PlatformMatchRule`:
https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/blob/45f37517309cf9a4848c43561bcf93def999305f/src/main/java/de/flapdoodle/embed/mongo/packageresolver/linux/LinuxPackageFinder.java#L115-L124
> Change test to MongoDB version V4_0_2

- instrumentation/cats-effect-2/build.gradle
- instrumentation/cats-effect-3/build.gradle
- instrumentation/jedis-3.0.0/build.gradle
- instrumentation/slick-2.12_3.2.0/build.gradle
- instrumentation/spring-ws-2.0/build.gradle
Some instrumentation modules had the versions that they apply to outdated due to new releases of the libraries.
This PR fixes that and also improves some of the checks to certify that a module is not applied to a version of the library it should not apply to.
> Updating version some instrumentation modules apply to

- newrelic-agent/src/main/java/com/newrelic/agent/Agent.java
- newrelic-agent/src/main/java/com/newrelic/agent/config/AgentConfigImpl.java
- newrelic-agent/src/main/java/com/newrelic/agent/config/JavaVersionUtils.java
- newrelic-agent/src/main/java/com/newrelic/bootstrap/BootstrapAgent.java
Feature https://github.com/newrelic/newrelic-java-agent/issues/628
This adds a configuration option (must use system property or environment variable) that bypasses the agents check on supported version. 
We currently check in JavaVersionUtils to see if the agent has been loaded in a supported Java version. We fail and exit if we detect the agent has been loaded in an unsupported version (both old and new jdk versions).
This bypass is to allow for experimental usage of an agent build in any forward JDK. This would allow for some simple smoke testing or other usages without having to do a build with changes  to JavaVersionUtils.
Describe Alternatives
continue as we do. Create a special branch and change what's needed to build and run on a future java runtime.
Given the faster cadence of …
> add bypass for agent version chck

- .github/workflows/GHA-Scala-Functional-Tests.yaml
- .github/workflows/GHA-Scala-Instrumentation-Tests.yaml
- .github/workflows/X-Reusable-Test.yml
- README.md
- instrumentation/build.gradle
Zinc compiler issues prevent compiling multiple scala versions together.
Exclude Scala test tasks by default. 
Include -PincludeScala project property to enable Scala test tasks.
Provide an example of new project property usage in the readme. 
Remove noScala project property and usage.
https://github.com/newrelic/newrelic-java-agent/issues/584
Local test runs
Ran green GHA checks against draft pull request
[X] Does your code contain any breaking changes? Please describe. No
> Exclude Scala test tasks by default

- .github/workflows/AITs-Basic-Features-Flaky.yml
- .github/workflows/AITs-Basic-Features-Special-JREs.yml
- .github/workflows/AITs-Basic-Features.yml
- .github/workflows/Datastore-AITs.yml
- .github/workflows/GHA-AIT-functionality-framework-tests.yaml
- .github/workflows/GHA-AIT-functionality-security-tests.yaml
- .github/workflows/GHA-AIT-functionality-server-tests.yaml
- .github/workflows/GHA-AIT-functionality-trace-tests.yaml
- .github/workflows/GHA-Functional-Tests.yaml
- .github/workflows/GHA-Scala-Functional-Tests.yaml
- .github/workflows/GHA-Scala-Instrumentation-Tests.yaml
- .github/workflows/GHA-Unit-Tests.yaml
- .github/workflows/X-Reusable-Test.yml
Adopt has been discontinued and temurin has taken over.
So we have to use temurin to be able to use the latest update of each Java version.
> Changing setup-java to use temurin since adopt is dead

- instrumentation/aws-java-sdk-s3-1.2.13/src/main/java/com/amazonaws/services/s3/AmazonS3_Instrumentation.java
Removes a redundant debug log (System.out.println) in aws-java-sdk-s3.
https://github.com/newrelic/newrelic-java-agent/issues/681
Yes
No
No
> Remove debug log

- .github/workflows/Java-18-ea-Instrumentation-Tests.yml
Necessary evil to get reusable workflow usage corrected after commit to main until we move reusable workflows to separate repo.
> Fix Java 18 EA Instrumentation run to use reusable workflow in main

- newrelic-agent/src/main/java/com/newrelic/agent/RPMService.java
- newrelic-agent/src/test/java/com/newrelic/agent/MockCollectorServlet.java
- newrelic-agent/src/test/java/com/newrelic/agent/tracers/jasper/GeneratorVisitTracerFactoryTest.java
Logging and one test change.
https://github.com/newrelic/newrelic-java-agent/issues/687
Java agent log messages still contain the support email address support@newrelic.com
That email address is no longer active and is not a way that customers can contact support. Update the logs be updated to point to the support portal at https://support.newrelic.com
```
2022-01-27T21:24:59,085+0000 [1 63] com.newrelic WARN: Received a ForceRestartException: com.newrelic.agent.ForceRestartException: . The agent will attempt to reconnect for data reporting. If this message continues, please contact support@newrelic.com.
```
> get rid of support@newrelic refs

- agent-interfaces/src/main/java/com/newrelic/agent/interfaces/NoOpReservoirManager.java
- agent-interfaces/src/main/java/com/newrelic/agent/interfaces/ReservoirManager.java
- functional_test/src/test/java/com/newrelic/agent/instrumentation/pointcuts/javax/xml/rpc/XmlRpcPointCutTest.java
- functional_test/src/test/java/test/newrelic/test/agent/DistributedTracingTest.java
- functional_test/src/test/java/test/newrelic/test/agent/spans/RootSpanStatusErrorsTest.java
- functional_test/src/test/java/test/newrelic/test/agent/spans/SpanErrorsTest.java
- functional_test/src/test/java/test/newrelic/test/agent/spans/SpanIdOnErrorsTest.java
- functional_test/src/test/java/test/newrelic/test/agent/spans/SpanParentTest.java
- functional_test/src/test/java/test/newrelic/test/agent/spans/TransactionAttributesOnSpanTest.java
- instrumentation-test/src/main/java/com/newrelic/agent/introspec/internal/IntrospectorSpanEventService.java
- newrelic-agent/src/main/java/com/newrelic/agent/service/ReservoirAddingSpanEventConsumer.java
- newrelic-agent/src/main/java/com/newrelic/agent/service/analytics/CollectorSpanEventReservoirManager.java
- newrelic-agent/src/main/java/com/newrelic/agent/service/analytics/SpanEventsService.java
- newrelic-agent/src/main/java/com/newrelic/agent/service/analytics/SpanEventsServiceImpl.java
- newrelic-agent/src/main/java/com/newrelic/agent/tracing/DistributedTraceUtil.java
- newrelic-agent/src/test/java/com/newrelic/agent/DataCollectionConfigCrossAgentTest.java
- newrelic-agent/src/test/java/com/newrelic/agent/DistributedTraceCrossAgentTest.java
- newrelic-agent/src/test/java/com/newrelic/agent/MockSpanEventReservoirManager.java
- newrelic-agent/src/test/java/com/newrelic/agent/SegmentTest.java
- newrelic-agent/src/test/java/com/newrelic/agent/service/ReservoirAddingSpanEventConsumerTest.java
- newrelic-agent/src/test/java/com/newrelic/agent/service/SpanEventsServiceFactoryTest.java
- newrelic-agent/src/test/java/com/newrelic/agent/service/analytics/CollectorSpanEventReservoirManagerTest.java
- newrelic-agent/src/test/java/com/newrelic/agent/service/analytics/SpanEventsServiceTest.java
- newrelic-agent/src/test/java/com/newrelic/agent/tracers/DefaultSqlTracerTest.java
- newrelic-agent/src/test/java/com/newrelic/agent/tracers/DefaultTracerTest.java
- newrelic-agent/src/test/java/com/newrelic/agent/tracers/ExternalTracerTest.java
- newrelic-agent/src/test/java/com/newrelic/agent/tracing/W3CTraceContextCrossAgentTest.java
WIP  for #124 
Manual testing, spans are generated and associated with the correct app names.  The code research and how the agent works in this scenario is documented here - https://docs.google.com/document/d/1QR9qMqfSA2ILtmGzgkxe6OdSN9knVHOx8e5tid91_MY/edit?usp=sharing
AIT: 🟢   https://javaagent-build.pdx.vm.datanerd.us/job/AIT_Configurable/231/
Additional PR for AITS to add test coverage: https://source.datanerd.us/java-agent/agent-integration-tests/pull/66
The  sample app has a base name and creates two Auto App name transactions.  The expected behavior is that spans should report to the associate transaction, on the the particular auto app name, which is happening here.
This is broken behavior, where all spans of all app names report to the base app name.
> Spans auto app name

- instrumentation-test/src/main/java/com/newrelic/agent/introspec/internal/InstrumentingClassLoader.java
- instrumentation-test/src/main/java/com/newrelic/agent/introspec/internal/WeavingClassLoader.java
- instrumentation/akka-2.2/src/test/java/com/nr/instrumentation/akka22/test/AkkaTest.java
- newrelic-agent/src/main/java/com/newrelic/agent/instrumentation/classmatchers/ScalaTraitMatcher.java
- newrelic-agent/src/main/java/com/newrelic/agent/instrumentation/context/InstrumentationContext.java
- newrelic-agent/src/main/java/com/newrelic/agent/instrumentation/context/InstrumentationContextManager.java
- newrelic-agent/src/main/java/com/newrelic/agent/instrumentation/weaver/ClassLoaderClassTransformer.java
- newrelic-agent/src/main/java/com/newrelic/agent/instrumentation/weaver/ClassWeaverService.java
- newrelic-weaver-scala/build.gradle
- newrelic-weaver-scala/src/test/scala/com/nr/weave/weavepackage/language/scala/ScalaAdapterTest.scala
- newrelic-weaver-scala/src/test/scala/com/nr/weave/weavepackage/language/scala/violations/ScalaViolationsTest.scala
- newrelic-weaver/src/main/java/com/newrelic/weave/ClassWeave.java
- newrelic-weaver/src/main/java/com/newrelic/weave/weavepackage/PackageValidationResult.java
- newrelic-weaver/src/main/java/com/newrelic/weave/weavepackage/WeavePackageManager.java
- newrelic-weaver/src/main/java/com/newrelic/weave/weavepackage/language/scala/ScalaAdapter.java
- newrelic-weaver/src/test/java/com/newrelic/weave/EnumAccessTest.java
- newrelic-weaver/src/test/java/com/newrelic/weave/WeaveTestUtils.java
- newrelic-weaver/src/test/java/com/newrelic/weave/weavepackage/ConcurrentWeaveTest.java
- newrelic-weaver/src/test/java/com/newrelic/weave/weavepackage/PublicNewFieldTest.java
- newrelic-weaver/src/test/java/com/newrelic/weave/weavepackage/WeaveInterfaceConcretePackageTest.java
- newrelic-weaver/src/test/java/com/newrelic/weave/weavepackage/WeavePackageManagerTest.java
- newrelic-weaver/src/test/java/com/newrelic/weave/weavepackage/WeavePackageTest.java
This PR enables the scala weaver to work with Java 11+ JREs
#438 
[X] Are your contributions backwards compatible with relevant frameworks and APIs?
[] Does your code contain any breaking changes? Please describe. 
[ ] Does your code introduce …
> upgrade scala weaver to 2.12 to allow use with java 11+

- newrelic-api/build.gradle
testing https://github.com/newrelic/newrelic-java-agent/pull/684
Concern...does adding explicit automatic name force others to explicitly require?
Also rebase to test.
> Adding attribute Automatic-Module-Name for JDK9/11

- infinite-tracing/src/main/java/com/newrelic/SpanEventSender.java
- newrelic-agent/src/main/java/com/newrelic/agent/DummyTransaction.java
- newrelic-agent/src/main/java/com/newrelic/agent/MetricNames.java
- newrelic-agent/src/main/java/com/newrelic/agent/stats/DataUsageStats.java
- newrelic-agent/src/main/java/com/newrelic/agent/stats/DataUsageStatsImpl.java
- newrelic-agent/src/main/java/com/newrelic/agent/stats/RecordDataUsageMetric.java
- newrelic-agent/src/main/java/com/newrelic/agent/stats/SimpleStatsEngine.java
- newrelic-agent/src/main/java/com/newrelic/agent/stats/StatsEngine.java
- newrelic-agent/src/main/java/com/newrelic/agent/stats/StatsEngineImpl.java
- newrelic-agent/src/main/java/com/newrelic/agent/stats/StatsWorks.java
- newrelic-agent/src/main/java/com/newrelic/agent/transport/DataSenderImpl.java
- newrelic-agent/src/test/java/com/newrelic/agent/stats/StatsEngineTest.java
- newrelic-agent/src/test/java/com/newrelic/agent/stats/StatsServiceTest.java
- newrelic-agent/src/test/java/com/newrelic/agent/transport/DataSenderImplTest.java
This PR implements the [Data-Usage-Supportability-Metrics](https://source.datanerd.us/agents/agent-specs/blob/main/Data-Usage-Supportability-Metrics.md) agent spec with a couple of caveats.
The spec lists destinations for agent data as `Collector`, `OTLP`, and `InfiniteTracing`. This PR only generates metrics for the `Collector` destination. Generating data usage metrics for the `InfiniteTracing` destination is not currently implemented and can be done in a follow up PR at a later time (see https://github.com/newrelic/newrelic-java-agent/issues/717). The Java agent does not currently support `OTLP` as a destination to send data.
Example of metrics generated:
```
[
...
[
[
{
"name": "Supportability\/Java\/Collector\/transaction_sample_data\/Output\/Bytes"
},
[
1,
12215,
0,
0,
0,
0
]
],
[
{ …
```
> Implement data usage metrics

- instrumentation/apache-log4j-2/src/main/java/org/apache/logging/log4j/core/config/LoggerConfig_Instrumentation.java
- instrumentation/apache-log4j-2/src/test/java/com/nr/agent/instrumentation/log4j2/LoggerConfig_InstrumentationTest.java
Fix for duplicated logs being forwarded when using log4j2 and child loggers with additivity
N/A
Added unit tests for this case
> fix: log4j duplicated log lines and counters

- newrelic-agent/src/test/java/com/newrelic/agent/config/ApplicationLoggingMetricsConfigTest.java
Adds tests for `ApplicationLoggingMetricsConfig`
Part of:
https://github.com/newrelic/newrelic-java-agent/issues/733
> add logging metric tests (ApplicationLoggingMetricsConfig)

- instrumentation/apache-log4j-1/src/main/java/com/nr/agent/instrumentation/log4j1/AgentUtil.java
- instrumentation/apache-log4j-2/src/main/java/com/nr/agent/instrumentation/log4j2/AgentUtil.java
- instrumentation/java.logging-jdk8/src/main/java/com/nr/instrumentation/jul/AgentUtil.java
- instrumentation/logback-classic-1.2/src/main/java/com/nr/agent/instrumentation/logbackclassic12/AgentUtil.java
- newrelic-agent/src/main/java/com/newrelic/agent/AgentImpl.java
- newrelic-agent/src/main/java/com/newrelic/agent/AgentLinkingMetadata.java
- newrelic-agent/src/main/java/com/newrelic/agent/service/logging/LogSenderServiceImpl.java
- newrelic-agent/src/test/java/com/newrelic/agent/AgentLinkingMetadataTest.java
Moves the adding of agent linking metadata to `LogEvent`s out of individual instrumentation module and into the `LogSenderServiceImpl`.
Potential benefits:
- Might be slightly more performant as it no longer gets the full map of agent attributes and filters them down to just the ones used by `LogEvent`s. In reality this is pretty minor.
- If we ever wanted a public API like `NewRelic.getAgent().getLogSender().recordLogEvent(attributesMap)` then this is probably a better design as the linking metadata attributes (`span.id`, `entity.guid`, `hostname`, `trace.id`) are automatically added in core agent code when calling the API and the `attributesMap` only needs to contain the log attributes (`message`, `timestamp`, `log.level`). In the current design the `attributesMap` needs to have both …
> Refactor adding of agent linking metadata

- newrelic-agent/src/main/java/com/newrelic/agent/HarvestServiceImpl.java
This will log the harvest limit details for all event types (both those with faster event harvest and also SpanEvents without it). Also standardizes the format of these log messages a bit.
Example log output:
```
2022-03-17T15:45:12,930-0700 [57270 1] com.newrelic FINE: harvest limit from collector for log_event_data is: 0 max samples stored per every 5 second harvest
2022-03-17T15:45:12,931-0700 [57270 1] com.newrelic FINE: harvest limit from collector for custom_event_data is: 833 max samples stored per every 5 second harvest
2022-03-17T15:45:12,940-0700 [57270 1] com.newrelic FINE: harvest limit from collector for analytic_event_data is: 166 max samples stored per every 5 second harvest
2022-03-17T15:45:12,941-0700 [57270 1] com.newrelic FINE: harvest limit from collector for …
```
> Log the number of events stored per harvest

- instrumentation/apache-log4j-1/src/main/java/com/nr/agent/instrumentation/log4j1/AgentUtil.java
- instrumentation/apache-log4j-2/src/main/java/com/nr/agent/instrumentation/log4j2/AgentUtil.java
- instrumentation/java.logging-jdk8/src/main/java/com/nr/instrumentation/jul/AgentUtil.java
- instrumentation/logback-classic-1.2/src/main/java/com/nr/agent/instrumentation/logbackclassic12/AgentUtil.java
- newrelic-agent/src/main/java/com/newrelic/agent/AgentLinkingMetadata.java
- newrelic-agent/src/test/java/com/newrelic/agent/AgentLinkingMetadataTest.java
Adds `entity.name` as a `LogEvent` attribute as well as including it in the metadata that is appended to log lines. Updates related tests.
Resolves https://github.com/newrelic/newrelic-java-agent/issues/796
> Add entity.name to LogEvents. Fix tests.

- instrumentation/apache-log4j-1/src/main/java/com/nr/agent/instrumentation/log4j1/AgentUtil.java
- instrumentation/apache-log4j-1/src/test/java/com/nr/agent/instrumentation/log4j1/AgentUtilTest.java
- instrumentation/apache-log4j-2/src/main/java/com/nr/agent/instrumentation/log4j2/AgentUtil.java
- instrumentation/apache-log4j-2/src/test/java/com/nr/agent/instrumentation/log4j2/AgentUtilTest.java
- instrumentation/java.logging-jdk8/src/main/java/com/nr/instrumentation/jul/AgentUtil.java
- instrumentation/java.logging-jdk8/src/test/java/com/nr/instrumentation/jul/AgentUtilTest.java
- instrumentation/logback-classic-1.2/src/main/java/com/nr/agent/instrumentation/logbackclassic12/AgentUtil.java
- instrumentation/logback-classic-1.2/src/test/java/com/nr/agent/instrumentation/logbackclassic12/AgentUtilTest.java
There was a [spec change](https://source.datanerd.us/agents/agent-specs/pull/570/commits/cda9b9b5e6bc12e61e4edeb7d140c72b2e53533d) that requires the `entity.name` to be URL encoded when added to the agent metadata blob for local log file decorating. The purpose is to avoid any entity names using the `|` character as it is also used as the delimiter of attributes in the blob.
Previously the blob appended to logs would look like this with an app name of `|My Application|`:
```
NR-LINKING|entityGuid123|199.199.1.19|traceId123|spanId123||My Application||
```
With URL encoding it is now:
```
NR-LINKING|entityGuid123|199.199.1.19|traceId123|spanId123|%7CMy+Application%7C|
```
> URL encode entity.name for local_decorating metadata blob

- newrelic-agent/src/main/java/com/newrelic/agent/service/logging/LogSenderServiceImpl.java
Prevents MessageFormat from being called if log message would not be written.
> Removing unnecessary call to MessageFormat

- instrumentation/apache-log4j-2/build.gradle
- instrumentation/logback-classic-1.2/build.gradle
Fixes the versions that log4j-2 and logback instrumentation should apply to.
[y] Are your contributions backwards compatible with relevant frameworks and APIs?
[n] Does your code contain any breaking changes? Please describe. 
[n] Does your code introduce any new dependencies? Please describe.
> Fixing version range that log instrumentation should apply

- .github/workflows/AITs-Basic-Features-Special-JREs.yml
- .github/workflows/AITs-Basic-Features.yml
- .github/workflows/AITs-Datastores.yml
- .github/workflows/AITs-Frameworks.yml
- .github/workflows/AITs-Security.yml
- .github/workflows/AITs-Servers.yml
- .github/workflows/AITs-Traces.yml
- .github/workflows/GHA-Functional-Tests.yaml
- .github/workflows/GHA-Unit-Tests.yaml
- .github/workflows/Java-18-Instrumentation-Tests.yml
- .github/workflows/X-Reusable-Test.yml
- newrelic-agent/src/main/java/com/newrelic/agent/config/JavaVersionUtils.java
- newrelic-agent/src/test/java/com/newrelic/agent/config/JavaVersionUtilsTest.java
- newrelic-api/build.gradle
Final updates for JDK 18 GA support.
Updates JavaVersionUtils and JavaVersionUtilsTest
Updates GHA version from 18-ea to 18
https://github.com/newrelic/newrelic-java-agent/issues/669
> 18 GA tests and version utils

- .github/workflows/AITs-Basic-Features-Special-JREs.yml
- .github/workflows/AITs-Basic-Features.yml
- .github/workflows/AITs-Datastores.yml
- .github/workflows/AITs-Frameworks.yml
- .github/workflows/AITs-Security.yml
- .github/workflows/AITs-Servers.yml
- .github/workflows/AITs-Traces.yml
- .github/workflows/X-Reusable-Test.yml
- .github/workflows/publish_main_snapshot.yml
- .github/workflows/publish_release.yml
Forces Gradle's toolchains to use the JDKs installed by `setup-java`.
Fixes #723 
[y] Are your contributions backwards compatible with relevant frameworks and APIs?
[n] Does your code contain any breaking changes? Please describe. 
[n] Does your code introduce any new dependencies? Please describe.
> Forcing Gradle's toolchain to use setup-java's JDKs

- newrelic-agent/src/main/java/com/newrelic/agent/config/ApplicationLoggingConfigImpl.java
- newrelic-agent/src/main/java/com/newrelic/agent/config/ApplicationLoggingForwardingConfig.java
- newrelic-agent/src/main/resources/newrelic.yml
- newrelic-agent/src/test/java/com/newrelic/agent/config/AgentConfigImplTest.java
- newrelic-agent/src/test/java/com/newrelic/agent/config/ApplicationLoggingForwardingConfigTest.java
Resolves https://github.com/newrelic/newrelic-java-agent/issues/814
---
Logging AITs pass
```
./bin/runtest.sh tests/java/functionality/basic_features/logging_test.py
runtest.sh: firing up...
runtest.sh: all tests to run tests/java/functionality/basic_features/logging_test.py
AIT validate: start.
AIT validate: success.
runtest.sh: Python interpreter: /path/to/java-agent-integration-tests/bin/python
runtest.sh: running test tests/java/functionality/basic_features/logging_test.py with args 
test_application_logging_disabled (__main__.LoggingTest) ... 2022-04-11 16:15:34,991 - INFO: run: /path/to/java-agent-integration-tests/tests/java/functionality/basic_features/logging_test.py:test_application_logging_disabled, tmpdir: /tmp/tmpzsj_gm67
2022-04-11 16:15:34,997 - INFO: ............... …
```
> Enable application_logging by default

- newrelic-weaver/build.gradle
Use same version of caffeine in `newrelic-weaver` that is used in `newrelic-agent`.
> Update weaver to use caffeine 2.9.3

- .github/workflows/X-Reusable-VerifyInstrumentation.yml
Some libraries are built with Java 11. This cause errors when running the tests with Java 8.
It was not straightforward to use toolchain to run a single module with 11. So changing all tests to run with 11 allows all tests to pass.
#830
> Running verify instrumentation tests with Java 11

- .github/workflows/X-Reusable-VerifyInstrumentation.yml
- instrumentation/solr-jmx-7.4.0/build.gradle
Caps the solr-jmx-7.4.0 instrumentation to version 9.0.0 of Solr
#847
> Capping Solr JMX instrumentation

- instrumentation/cassandra-datastax-2.1.2/src/main/java/com/nr/agent/instrumentation/cassandra/CQLParser.java
- instrumentation/cassandra-datastax-3.0.0/src/main/java/com/nr/agent/instrumentation/cassandra/CQLParser.java
- instrumentation/cassandra-datastax-3.8.0/src/main/java/com/nr/agent/instrumentation/cassandra/CQLParser.java
- instrumentation/cassandra-datastax-4.0.0/src/main/java/com/nr/agent/instrumentation/cassandra/CQLParser.java
Capture and ignore exceptions in the CQLParser getOperationAndTableName method used by Cassandra 4.x to address https://github.com/newrelic/newrelic-java-agent/issues/827.
https://github.com/newrelic/newrelic-java-agent/issues/827
Ran module unit tests
[X] Does your code contain any breaking changes? Please describe. No
> #827 - CQLParser getOperationAndTableName exception handling

- instrumentation/kafka-clients-metrics-3.0.0/src/main/java/org/apache/kafka/clients/consumer/internals/PartitionAssignor.java
The Kafka 3 instrumentation was applying to some older versions.
This PR adds a verification to prevent that.
#711
> Preventing Kafka 3.0.0 instrumentation from applying on older versions

- newrelic-agent/build.gradle
Update to `jfr-daemon` 1.8.0 to address [CVE-2022-25647](https://github.com/advisories/GHSA-4jrv-ppp4-jm57) with GSON library.
Resolves https://github.com/newrelic/newrelic-java-agent/issues/867
> Update to jfr-daemon 1.8.0

- instrumentation/aws-java-sdk-dynamodb-2.15.34/build.gradle
DynamoDB's SDK version 2.17.200 failed the verify instrumentation test. But 2.17.201 works again.
Skipping that version for now.
> Skipping bad dynamoDB version

- instrumentation/play-2.7/build.gradle
- instrumentation/wildfly-8/build.gradle
New versions of play and wildfly are not being instrumented.
This PR prevents the tests from failing. Follow up tickets will be written.
> Capping version of play and wildfly instrumentation modules

- instrumentation/jax-rs-1.0/build.gradle
Jakarta EE 8 doesn't change functionality or package names, it only publishes the artifacts under new jakarta maven coordinates.
In theory our instrumentation should still compile and function properly when updated to use the jakarta 8 dependencies as the package names and code that we instrument haven't changed.
For existing instrumentation that has dependencies on the various javax.* packages we'll need to update them to use the Jakarta 8 EE version of the dependency and verify that the modules still compile and that all tests still pass.
jax-rs-1.0
Dependencies to use:
// https://mvnrepository.com/artifact/jakarta.ws.rs/jakarta.ws.rs-api
implementation 'jakarta.ws.rs:jakarta.ws.rs-api:3.1.0'
https://mvnrepository.com/artifact/jakarta.ws.rs/jakarta.ws.rs-api/3.1.0
Success Criteria …
> impelementation jakarta jax-rs

- instrumentation/r2dbc-mariadb/build.gradle
r2dbc-mariadb instrumentation module fails to apply to version 1.1.2 of the artifact.
Capping the checked versions in verify instrumentation to prevent further errors.
A ticket has been filed.
> Capping r2dbc-mariadb

- instrumentation/jax-rs-1.0/build.gradle
Jakarta EE 8 doesn't change functionality or package names, it only publishes the artifacts under new jakarta maven coordinates.
In theory our instrumentation should still compile and function properly when updated to use the jakarta 8 dependencies as the package names and code that we instrument haven't changed.
For existing instrumentation that has dependencies on the various {*}javax.{*}* packages we'll need to update them to use the Jakarta 8 EE version of the dependency and verify that the modules still compile and that all tests still pass.
 https://issues.newrelic.com/browse/NR-28393
> fixed compile deps for jax-rs

- functional_test/build.gradle
- instrumentation/akka-http-2.11_2.4.5/build.gradle
- instrumentation/akka-http-2.13_10.1.8/build.gradle
- instrumentation/play-2.6.13/build.gradle
- instrumentation/play-2.6/build.gradle
- instrumentation/play-2.7/build.gradle
- instrumentation/spray-http-1.3.1/build.gradle
- instrumentation/vertx-web-3.2.0/build.gradle
- instrumentation/vertx-web-3.3.0/build.gradle
- instrumentation/vertx-web-3.5.0/build.gradle
- instrumentation/vertx-web-3.5.1/build.gradle
- instrumentation/vertx-web-3.5.2/build.gradle
- instrumentation/vertx-web-3.6.0/build.gradle
- instrumentation/vertx-web-3.8.0/build.gradle
- instrumentation/vertx-web-3.8.3/build.gradle
For existing instrumentation that has dependencies on the various javax.* packages we'll need to update them to use the Jakarta 8 EE version of the dependency and verify that the modules still compile and that all tests still pass.
java.xml
Dependencies to use:
https://mvnrepository.com/artifact/jakarta.xml.ws/jakarta.xml.ws-api/2.3.3
This dependency was scattered throughout many different modules.
> jakarta.xml

- instrumentation-test/src/main/java/com/newrelic/agent/introspec/internal/InstrumentingClassLoader.java
- newrelic-agent/src/main/java/com/newrelic/agent/instrumentation/classmatchers/ScalaTraitMatcher.java
- newrelic-agent/src/main/java/com/newrelic/agent/instrumentation/context/InstrumentationClassTransformer.java
- newrelic-agent/src/main/java/com/newrelic/agent/instrumentation/context/InstrumentationContext.java
- newrelic-agent/src/main/java/com/newrelic/agent/instrumentation/context/InstrumentationContextManager.java
- newrelic-agent/src/main/java/com/newrelic/agent/instrumentation/custom/ScalaTraitFinalFieldTransformer.java
- newrelic-agent/src/main/java/com/newrelic/agent/instrumentation/custom/ScalaTraitFinalFieldVisitor.java
- newrelic-weaver-scala/src/test/scala/com/nr/weave/weavepackage/language/scala/ScalaAdapterTest.scala
This PR fixes issue #620 where an Illegal Access Exception was being thrown from apps using NR agent with scala 2.12 and Java 11. The issue is related to  https://github.com/scala/scala-dev/issues/408 where a scala trait has a `val` field and synthetic setter methods in the trait are called by implementing child class breaking a constraint set in the JMM in JDK 9+. 
The workarround for this is similar to  scala 2.13 where the trait field is marked as not final in the bytecode. 
verify your changes don't …
> issue 620 scala illegal access error

- .github/workflows/AITs-Clients.yml
- .github/workflows/AITs-Frameworks.yml
- .github/workflows/AITs-R2DBC.yml
- agent-bridge/src/main/java/com/newrelic/agent/bridge/external/ExternalMetrics.java
- functional_test/src/test/java/com/newrelic/agent/instrumentation/pointcuts/net/HttpURLConnectionTest.java
- functional_test/src/test/java/test/newrelic/test/agent/HttpCommonsTest.java
- instrumentation-test/src/main/java/com/newrelic/agent/introspec/internal/InstrumentingClassLoader.java
- instrumentation/httpurlconnection/src/main/java/com/nr/agent/instrumentation/httpurlconnection/MetricState.java
- instrumentation/httpurlconnection/src/main/java/java/net/HttpURLConnection.java
- instrumentation/httpurlconnection/src/test/java/com/nr/agent/instrumentation/httpurlconnection/MetricStateResponseCodeTest.java
- instrumentation/r2dbc-mariadb/build.gradle
- newrelic-agent/src/main/java/com/newrelic/agent/Agent.java
- newrelic-agent/src/main/java/com/newrelic/agent/DebugFlag.java
- newrelic-agent/src/main/java/com/newrelic/agent/config/AgentConfigImpl.java
- newrelic-agent/src/main/java/com/newrelic/agent/config/AgentJarHelper.java
- newrelic-agent/src/main/java/com/newrelic/agent/config/ConfigFileHelper.java
- newrelic-agent/src/main/java/com/newrelic/agent/instrumentation/classmatchers/ScalaTraitMatcher.java
- newrelic-agent/src/main/java/com/newrelic/agent/instrumentation/context/InstrumentationClassTransformer.java
- newrelic-agent/src/main/java/com/newrelic/agent/instrumentation/context/InstrumentationContext.java
- newrelic-agent/src/main/java/com/newrelic/agent/instrumentation/custom/ScalaTraitFinalFieldTransformer.java
- newrelic-agent/src/main/java/com/newrelic/agent/instrumentation/custom/ScalaTraitFinalFieldVisitor.java
- newrelic-api/src/main/java/com/newrelic/api/agent/TracedMethod.java
- newrelic-weaver-scala/src/test/scala/com/nr/weave/weavepackage/language/scala/ScalaAdapterTest.scala
Merging main to the Jakarta branch so more people are working with the Scala fix.
> Merging main to jakarta 8

- newrelic-agent/build.gradle
Pulls in the following improvements from the underlying telemetry-sdk:
* Update to telemetry-sdk 0.15.0 to address [CVE-2020-29582](https://github.com/newrelic/newrelic-telemetry-sdk-java/issues/273) with kotlin lib dependencies of okhttp
* Also includes telemetry-sdk 0.14.0 improvement to decrease CPU utilization: [Replace UUID.randomUUID() with a faster implementation](https://github.com/newrelic/newrelic-telemetry-sdk-java/pull/292)
> Update to jfr-daemon 1.9.0

- build.gradle
- instrumentation/r2dbc-mssql/build.gradle
- instrumentation/spring-3.0.0/build.gradle
- instrumentation/spring-4.0.0/build.gradle
- instrumentation/spring-4.2.0/build.gradle
- instrumentation/spring-4.3.0/build.gradle
r2dbc-mssql stopped applying with the new RC just released. Capping the version to prevent future errors in verify instrumentation.
> Capping r2dbc-mssql version

- functional_test/src/test/java/com/newrelic/agent/instrumentation/pointcuts/net/HttpURLConnectionTest.java
- functional_test/src/test/java/test/newrelic/test/agent/HttpCommonsTest.java
- instrumentation/httpurlconnection/src/main/java/java/net/HttpURLConnection.java
A customer was having trouble linking two applications using HttpUrlConnection on a RSClient created by JAXRSClientFactory.
The problem was that the client calls `getResponseCode` on the `HttpUrlConnection` which in turn calls `getInputStream`.
Our instrumentation instruments both methods, and both have `@Trace(leaf = true)`.
The part of the instrumentation that would add the headers in this case is in `getInputStream`. But before adding the headers, it check if the tracer is metric producer. In this case, since the tracer in `getResponseCode` is a leaf, `getInputStream` will get a `NoOpTracer` (which is not a metric producer). And thus the headers will not be added.
NR-19683
> Fix DT headers not being added on requests made with HttpUrlConnection

- instrumentation/spring-aop-2/src/main/java/org/springframework/aop/support/MethodMatchers.java
Updates spring-aop module to account for jakarta ee 9:
[MethodMatchers$matches](https://github.com/newrelic/newrelic-java-agent/blob/86a28f9974228c40f0f7b27106c562ee2a21f13a/instrumentation/spring-aop-2/src/main/java/org/springframework/aop/support/MethodMatchers.java#L31-L32) method needs a check for className.startsWith("jakarta") when using JEE9 artifacts.
> exclude jakarta in MethodMatchers.matches

- instrumentation/apache-log4j-2/src/main/java/com/nr/agent/instrumentation/log4j2/AgentUtil.java
- instrumentation/apache-log4j-2/src/main/java/com/nr/agent/instrumentation/log4j2/ExceptionUtil.java
- instrumentation/apache-log4j-2/src/test/java/com/nr/agent/instrumentation/log4j2/ExceptionUtilTest.java
- instrumentation/logback-classic-1.2/src/main/java/ch/qos/logback/classic/spi/LoggingEvent_Instrumentation.java
- instrumentation/logback-classic-1.2/src/main/java/com/nr/agent/instrumentation/logbackclassic12/AgentUtil.java
- instrumentation/logback-classic-1.2/src/main/java/com/nr/agent/instrumentation/logbackclassic12/ExceptionUtil.java
- instrumentation/logback-classic-1.2/src/test/java/com/nr/agent/instrumentation/logbackclassic12/ExceptionUtilTest.java
Custom jar with these changes can be downloaded here: https://github.com/newrelic/newrelic-java-agent/actions/runs/2800301113
Waiting on approval of this proposal to update agent specs with these changes: https://source.datanerd.us/agents/agent-specs/pull/579
---
Addresses https://github.com/newrelic/newrelic-java-agent/issues/802
This PR adds the `thread.name`, `thread.id`,  `logger.name`,  `logger.fqcn`, `error.class`, `error.stack`, and `error.message` attributes to log events for the `logback-classic-1.2` and `apache-log4j-2` instrumentation.
Screenshot showing the new log event attributes that this PR adds:
This is the result of calling the following Spring controller:
```
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Controller; …
```
> Add error and thread attributes to log4j2 and logback1.2 logs

- newrelic-agent/src/main/java/com/newrelic/agent/tracers/DefaultTracer.java
When an error occurs while retrieving CLM data, a log message is written, but it is missing the stack trace on finer log levels.
This adds the stack trace, as other errors in the same class.
> Adding stack trace to when logging CLM data retrieval error

- functional_test/src/test/java/test/newrelic/test/agent/ExpectedErrorsTest.java
- functional_test/src/test/resources/configs/expected_errors_test.yml
- newrelic-agent/src/main/java/com/newrelic/api/agent/NewRelicApiImplementation.java
The changes here force the noticeError API to check the expected error configuration when using APIs that do not explicitly set the expected boolean. 
Previously, we just passed false all the way through and the expected boolean only gets set if the caller uses the API that includes the boolean.
Tested with local apps and config.
This will add new tests.
[ yes] Are your contributions backwards compatible with relevant frameworks and APIs?
[ no] Does your code contain any breaking changes? Please describe. 
[ no] Does your code introduce any new dependencies? Please describe.
> NEWRELIC-658 check expected error config for noticeError api

- functional_test/src/test/java/com/newrelic/agent/instrumentation/ClassLoaderTest.java
- functional_test/src/test/java/test/newrelic/test/agent/spans/SpanErrorsTest.java
- gradle/script/java.gradle
- instrumentation/cassandra-datastax-4.0.0/src/test/java/com/nr/agent/instrumentation/cassandra/CassandraInstrumented.java
- instrumentation/cassandra-datastax-4.0.0/src/test/java/com/nr/agent/instrumentation/cassandra/CassandraNoInstrumentation.java
- newrelic-agent/src/main/java/com/newrelic/agent/config/AgentConfig.java
- newrelic-agent/src/main/java/com/newrelic/agent/config/AgentConfigImpl.java
- newrelic-agent/src/main/java/com/newrelic/agent/config/IBMUtils.java
- newrelic-agent/src/main/java/com/newrelic/agent/instrumentation/context/InstrumentationContextClassMatcherHelper.java
- newrelic-agent/src/main/java/com/newrelic/agent/instrumentation/weaver/ClassLoaderClassTransformer.java
- newrelic-agent/src/main/java/com/newrelic/bootstrap/BootstrapAgent.java
- newrelic-agent/src/test/java/com/newrelic/agent/jfr/JfrServiceTest.java
- test-annotations/src/main/java/com/newrelic/test/marker/IBMJ9IncompatibleTest.java
Issue explained in these comments:
We never add the agent-bridge-datastore.jar in the ibmWorkaround path.  However, even with that, there is still a bug in the IBM Workaround path where we fail to use the correct branch of logic for versions 8 and above.
```
// Check for the IBM workaround
boolean ibmWorkaround = IBMUtils.getIbmWorkaroundDefault();
if (System.getProperty("ibm_iv25688_workaround") != null) {
ibmWorkaround = Boolean.parseBoolean(System.getProperty("ibm_iv25688_workaround"));
}
ClassLoader classLoader;
if (ibmWorkaround) {
// For the IBM workaround lets just use the System ClassLoader
//if you come down this path, we never end up
//performing addBridgeJarToClassPath(inst, AGENT_BRIDGE_DATASTORE_JAR_NAME); hence NoClassDefFound for Record.Sql
classLoader = …
```
> NEWRELIC-3836 remove obsolete ibm workaround - support Semeru/OpenJ9 versions

- instrumentation/apache-log4j-2/src/main/java/com/nr/agent/instrumentation/log4j2/AgentUtil.java
The method used in the first PR for this feature in Log4J was introduced in version 2.7.
But the instrumentation module supports version 2.6.
So this is changing the method used to the existing in 2.6.
> NR-23881 - change the method used to get the MDC

- gradle/script/java.gradle
Fixes build issue.
We (I) added the apply scala plugin to the java.gradle script, which meant we were expecting scala classes in each module. Our build task however did not expect that so was appropriately throwing an exception when the directories for scala classes weren't available in modules that did not in fact compile any scala.
> NEWRELIC-3498 fix Vfs.Dir scala dir

- functional_test/src/test/java/test/newrelic/test/agent/JavaUtilLoggerTest.java
- instrumentation/java.logging-jdk8/src/main/java/com/nr/instrumentation/jul/AgentUtil.java
- instrumentation/java.logging-jdk8/src/main/java/com/nr/instrumentation/jul/ExceptionUtil.java
- instrumentation/java.logging-jdk8/src/main/java/java/util/logging/LogRecord_Instrumentation.java
- instrumentation/java.logging-jdk8/src/main/java/java/util/logging/Logger_Instrumentation.java
- instrumentation/java.logging-jdk8/src/test/README.md
- instrumentation/java.logging-jdk8/src/test/java/com/nr/instrumentation/jul/ExceptionUtilTest.java
- instrumentation/java.logging-jdk8/src/test/resources/application_logging_enabled.yml
Adds instrumentation for creating and forwarding `LogEvent`s logged by the `java.util.logging` library.
AITs for this PR: https://github.com/newrelic/java-agent-integration-tests/pull/120
> NR-2447 Add log forwarding and tests for JUL.

- newrelic-agent/src/main/java/com/newrelic/agent/tracers/DefaultTracer.java
When adding CLM attrs to an span, going thru the add attribute code, it tries to get a transaction.
But if the @Trace is someplace where there is no transaction, this causes an NPE.
This PR adds a guard to prevent that from happening.
> Checks that there is a transaction prior to adding CLM attrs

- instrumentation/httpclient-jdk11/src/main/java/com.nr.agent.instrumentation.httpclient/Java11HttpClientUtil.java
Fixes a bug that would cause a segment timeout in the JDK 11 HTTP client instrumentation. The bug would occur whenever the synchronous `HttpClient.send(...)` method was invoked and any exception other than a `ConnectException` was thrown.
If an exception occurred here we would call `handleConnectException`:
```
@Trace
public <T> HttpResponse<T> send(HttpRequest req, HttpResponse.BodyHandler<T> responseHandler)
throws IOException, InterruptedException {
URI uri = req.uri();
Segment segment = startSegment(uri);
HttpResponse<T> response;
try {
response = Weaver.callOriginal();
if (segment == null) {
return response;
}
} catch (Exception e) {
handleConnectException(e, req, segment);
throw e;
}
processResponse(response, segment);
return response;
}
```
If the exception was a `ConnectException` …
> Fix jdk11 http client so that segments don't time out

- newrelic-agent/src/main/resources/newrelic.yml
The default config file had the wrong label for the context data stanza
> NR-23881 - Fixing typo in context data config

- instrumentation/play-2.6.13/build.gradle
- instrumentation/play-2.6/build.gradle
- instrumentation/play-2.7/build.gradle
- instrumentation/spring-aop-2/build.gradle
Some artifacts used by the agent used a syntax for version (1.0.+) to get the latest patch version.
This works well in JCenter, but not on Maven Central. So when JCenter have problems we are not able to build the agent.
Specifying the version for these artifacts allows us to download them from Maven Central.
It is unlikely that we'd get any new patch version for these artifacts since their last version are from 2017.
> NR-00000 - Moving dependencies from JCenter to Maven Central

- instrumentation/apache-log4j-2/src/main/java/org/apache/logging/log4j/core/config/LoggerConfig_Instrumentation.java
Fixes a bug where the below logic could evaluate to `true` even if application logging was disabled at the top level (i.e. `application_logging.enabled: false`):
```
if (isApplicationLoggingEnabled() && getParent() == null || !isAdditive()) {...}
```
If the entire `application_logging` stanza is disabled at the top level it should result in all related features being disabled regardless of how they are set.
In this case, where the `metrics` feature is still enabled, the code would make it past the above logic and still generate logging metrics.
```
application_logging:
enabled: false
forwarding:
enabled: true
max_samples_stored: 10000
local_decorating:
enabled: true
metrics:
enabled: true
```
> Fix bug with log4j2 metrics not getting disabled

- instrumentation/r2dbc-h2/build.gradle
- instrumentation/r2dbc-mssql/build.gradle
New versions of r2dbc-h2 and r2dbc-mssql were released on 2022/11/10 and they appear to be compatible with the agent, though the RC1 was not. So this PR updates the verification range.
> NR-00000 - Updating verification range for r2dbc h2 and mssql

- instrumentation/tomcat-jmx/src/main/java/com/nr/agent/instrumentation/tomcat/TomcatUtils.java
- newrelic-agent/src/main/java/com/newrelic/agent/jmx/JmxApiImpl.java
- newrelic-agent/src/main/java/com/newrelic/agent/jmx/values/EmbeddedTomcatDataSourceJmxValues.java
- newrelic-agent/src/main/java/com/newrelic/agent/jmx/values/EmbeddedTomcatJmxValues.java
Add instrumentation to cover embedded tomcat.
The agent doesn’t correctly query the following Tomcat JMX metrics when using embedded Tomcat with SpringBoot:
type=DataSource
type=ThreadPool
type=Manager
We add Tomcat JMX values for the above categories if the server was started via one of the following two methods:
```
org.apache.catalina.startup.HostConfig.start()
org.apache.catalina.core.StandardServer.startInternal()
```
It appears that when using embedded Tomcat with Spring Boot StandardServer does get instrumented properly:
```
Supportability/WeaveInstrumentation/WeaveClass/com.newrelic.instrumentation.tomcat-jmx/org/apache/catalina/core/StandardServer
Supportability/WeaveInstrumentation/WeaveClass/com.newrelic.instrumentation.tomcat-8.5.2/org/apache/catalina/core/StandardServer
``` …
> NEWRELIC-3834 add embedded tomcat jmx instrumentation

- newrelic-cats-effect3-api/build.gradle.kts
- newrelic-scala-api/build.gradle.kts
- newrelic-scala-cats-api/build.gradle.kts
- newrelic-scala-monix-api/build.gradle.kts
- newrelic-scala-zio-api/build.gradle.kts
Latest point release for scala 2.13.x APIs.
bumps to 2.13.10
> bump scala 2.13 to latest point release 2.13.10

- instrumentation/graphql-java-16.2/build.gradle
- instrumentation/graphql-java-16.2/src/main/java/com/nr/instrumentation/graphql/GraphQLSpanUtil.java
- instrumentation/graphql-java-16.2/src/test/java/com/nr/instrumentation/graphql/GraphQLSpanUtilTest.java
- instrumentation/graphql-java-17.0/build.gradle
- instrumentation/graphql-java-17.0/src/main/java/com/nr/instrumentation/graphql/GraphQLSpanUtil.java
- instrumentation/graphql-java-17.0/src/test/java/com/nr/instrumentation/graphql/GraphQLSpanUtilTest.java
* Unsafe cast to GraphQLObjectType
* https://github.com/newrelic/newrelic-java-agent/issues/1064
* https://issues.newrelic.com/browse/NEWRELIC-4936 (internal)
> NEWRELIC-4936 - Fix invalid ClassCastException in graphql 16/17

- instrumentation/spring-jms-2/build.gradle
- instrumentation/spring-webflux-5.3.0/build.gradle
Spring 6.0.0 GA revealed that new modules will be needed for spring-jms and spring-webflux. This pr caps the verification to the passing range.
> cap spring version verification

- newrelic-agent/src/main/java/com/newrelic/agent/TransactionActivity.java
- newrelic-agent/src/main/java/com/newrelic/agent/tracers/DefaultTracer.java
Adds some additional logging to help troubleshoot `Inconsistent state! tracer != last tracer` errors. 
Additional logging will appear when the following is set:
```
-Dnewrelic.config.log_level=finest 
-Dnewrelic.debug=true
```
Grep'ing the agent logs for `Tracer Debug:` should produce all of the debug log messages related to this issue, which shows how tracers are being created and processed.
For context, this issue occurs when the agent is handling some async activity and is adding tracers for each method call and popping tracers off the stack as each method call completes. The agent tracks what the first tracer (root tracer) is when the async activity started and by the end we would expect that that last tracer we pop off should be the root, but in this case it isn't, which means that …
> Tracer debug logging

- newrelic-agent/src/main/java/com/newrelic/agent/service/analytics/InsightsServiceImpl.java
InsightsServiceImpl.recordCustomEvent log pattern now includes event type, key and value
[ ] Does your …
> NEWRELIC-5268 - recordCustomEvent log pattern now includes event type, key and value

- instrumentation/spring-ws-2.0/build.gradle
Capping the versions the spring-ws-2.0 instrumentation module should apply to.
> Capping spring-ws-2.0 versions

- instrumentation/glassfish-6/build.gradle
The glassfish-6 instrumentation shouldn't apply to Glassfish 7, but it did apply to 7.0.0-M10.
Disabling that version for now.
> NR-00000 - Removing "bad" glassfish version from verifier

- instrumentation/build.gradle
- instrumentation/grpc-1.40.0/build.gradle
- instrumentation/grpc-1.40.0/src/main/java/com/nr/agent/instrumentation/grpc/GrpcUtil.java
- instrumentation/grpc-1.40.0/src/main/java/io/grpc/ServerCallListener_Instrumentation.java
- instrumentation/grpc-1.40.0/src/main/java/io/grpc/internal/ServerCallImpl_Instrumentation.java
- instrumentation/grpc-1.40.0/src/main/java/io/grpc/internal/ServerStream_Instrumentation.java
- instrumentation/grpc-1.40.0/src/test/java/BasicRequestsTest.java
Insure transactions are visible to user code.
> NEWRELIC-4191 Properly link tokens so transaction is available to user code

- instrumentation/glassfish-6/build.gradle
The glassfish-6 instrumentation module stopped applying to version 7.0.0-M3, but it is applying to 7.0.0.
This PR fixes the verification range
> Updating glassfish-6 verification range

- instrumentation/netty-4.0.0/src/main/java/io/netty/channel/ChannelHandler_Instrumentation.java
- instrumentation/netty-4.0.8/src/main/java/io/netty/channel/ChannelHandler_Instrumentation.java
- instrumentation/netty-reactor-0.8.0/src/main/java/reactor/netty/http/client/HttpClientConnect_Instrumentation.java
- instrumentation/netty-reactor-0.9.0/src/main/java/reactor/netty/http/client/HttpClientConnect_Instrumentation.java
When Spring WebClient emits a `io.netty.handler.timeout.ReadTimeoutException` due to a timeout, the transaction trace was originally lost. This PR fixes the bug.
[Related Github Issue link](https://github.com/newrelic/newrelic-java-agent/issues/242)
> Newrelic-3822 Bug fix for when Spring Webclient times out and emits a ReadTimeoutException, the transaction fails to link

- .github/workflows/Create-Custom-Jar.yml
- .github/workflows/GHA-Scala-Instrumentation-Tests.yaml
- .github/workflows/Java-Instrumentation-Tests.yml
- .github/workflows/Release-CopyToS3-prod.yml
- .github/workflows/Release-CopyToS3-staging.yml
- .github/workflows/VerifyInstrumentation-Single.yml
- .github/workflows/VerifyInstrumentation.yml
- .github/workflows/X-Reusable-VerifyInstrumentation.yml
- .github/workflows/publish_main_snapshot.yml
- .github/workflows/publish_release.yml
This PR brings some fixes and updates to the Verify Instrumentation workflow.
It also decreases the total runtime from 2 days to 17 hours and the actual runtime from 30 ~ 40 minutes to 20 ~ 30 minutes.
Changes:
- Building the agent only once and caching;
- removing the gradle cache on the verify instrumentation job
- this prevent flooding the cache server with requests
- does not impair runtime since very little of that cache was useful to the job;
- fixes AWS credentials.
> NR-00000 - Improve verify instrumentation

- instrumentation/jcache-1.0.0/src/main/java/javax/cache/Cache.java
This instrumentation creates metrics that start with `/Java`.  Metric names should not start with a forward slash.
As a matter of style, the `JCACHE` segment also stands out as a sore thumb but ¯\_(ツ)_/¯ 
> Metric names should not start with a forward slash

- newrelic-agent/src/main/java/com/newrelic/agent/MetricNames.java
- newrelic-agent/src/main/java/com/newrelic/agent/config/JfrConfig.java
- newrelic-agent/src/main/java/com/newrelic/agent/config/JfrConfigImpl.java
- newrelic-agent/src/main/java/com/newrelic/agent/jfr/JfrService.java
- newrelic-agent/src/test/java/com/newrelic/agent/jfr/JfrServiceTest.java
- Implement the `AgentConfigListener` interface on the `JfrService` to allow the JFR to be toggled, real time, via the yml file
- Add `Supportability/JfrService/Stopped/Success` to track when JFR is toggled off
- Additional test
> NR-66564 JFR toggle Config Listener

- instrumentation/akka-http-2.11_2.4.5/src/test/java/com/agent/instrumentation/akka/http/AkkaHttpRoutesTest.java
- instrumentation/akka-http-2.13_10.1.8/src/test/java/com/agent/instrumentation/akka/http/AkkaHttpRoutesTest.java
- instrumentation/grpc-1.22.0/src/main/java/io/grpc/internal/ServerStream_Instrumentation.java
- instrumentation/grpc-1.22.0/src/test/java/ValidationHelper.java
- instrumentation/grpc-1.30.0/src/main/java/io/grpc/internal/ServerStream_Instrumentation.java
- instrumentation/grpc-1.30.0/src/test/java/ValidationHelper.java
- instrumentation/grpc-1.4.0/src/main/java/io/grpc/internal/ServerStream_Instrumentation.java
- instrumentation/grpc-1.4.0/src/test/java/ValidationHelper.java
- instrumentation/grpc-1.40.0/src/main/java/com/nr/agent/instrumentation/grpc/GrpcUtil.java
- instrumentation/grpc-1.40.0/src/test/java/ValidationHelper.java
- newrelic-agent/src/main/java/com/newrelic/agent/attributes/AttributeNames.java
- newrelic-agent/src/main/java/com/newrelic/agent/config/AttributesConfigImpl.java
- newrelic-agent/src/main/java/com/newrelic/agent/dispatchers/WebRequestDispatcher.java
- newrelic-agent/src/main/java/com/newrelic/agent/service/analytics/SpanEventFactory.java
- newrelic-agent/src/test/java/com/newrelic/agent/service/analytics/TracerToSpanEventTest.java
Remove deprecated attributes: `httpResponseCode`, `httpResponseMessage`
> NEWRELIC-4831 Clean up deprecated attributes

- newrelic-agent/src/main/java/com/newrelic/bootstrap/BootstrapAgent.java
I have an app that crashes when using nri-lsi-java to attach the java agent.  Here's how to reproduce this: https://source.datanerd.us/saxon/java-agent-crash
Here's the exception:
```New Relic support.java.lang.ClassCircularityError: java/text/FieldPosition$Delegate
at java.base/java.text.FieldPosition.getFieldDelegate(FieldPosition.java:215)at java.base/java.text.DecimalFormat.format(DecimalFormat.java:714)at java.base/java.text.DecimalFormat.format(DecimalFormat.java:507)at ```
We can avoid the error by loading `FieldPosition$Delegate` before we modify class loaders.
[Include a link to the related GitHub issue, if applicable](https://issues.newrelic.com/browse/NR-84187)
You can verify the fix with https://source.datanerd.us/saxon/java-agent-crash
[ ] Are your contributions backwards …
> NR-84187 Fix ClassCircularityError when agent attaches

- newrelic-agent/src/main/java/com/newrelic/agent/tracers/AbstractTracer.java
[_Before contributing, please read our [contributing guidelines](https://github.com/newrelic/newrelic-java-agent/blob/main/CONTRIBUTING.md) and [code of conduct](https://github.com/newrelic/.github/blob/main/CODE_OF_CONDUCT.md)._](https://issues.newrelic.com/browse/NEWRELIC-6338)
null guards shouldAddAttribute
[NOTE]: # In a least one use case, a NullPointerExeception is thrown when calling any of the addCustomAttribute or addCustomAttributes method on TracedMethod. The exception is being thrown in the shouldAddAttribute() of AbstractTracer.
Description
If the following is true then a NullPointerExeception is thrown by the Agent, The async token is created but no transaction is started (No-op token created). If a method is called …
> NullPointerException thrown when calling addCustomAttributes

- agent-bridge/src/main/java/com/newrelic/agent/bridge/AgentBridge.java
Code such as this expect that `TokenAndRefCount.token` is never null:
https://github.com/newrelic/newrelic-java-agent/blob/main/newrelic-agent/src/main/java/com/newrelic/agent/Transaction.java#L1403
This sets the `token` to the no-op implementation if a null token is passed in.  We could add some logging when the token is null since ignoring this case could mask an issue, but I'll leave that as a future enhancement.
[here](https://github.com/newrelic/newrelic-java-agent/blob/main/CONTRIBUTING.md) …
> Make sure TokenAndRefCount.token is never null

- agent-bridge/src/main/java/com/newrelic/agent/bridge/Instrumentation.java
- agent-bridge/src/main/java/com/newrelic/agent/bridge/NoOpInstrumentation.java
- instrumentation-test/src/main/java/com/newrelic/agent/introspec/internal/NoOpClassTransformerService.java
- newrelic-agent/src/main/java/com/newrelic/agent/Transaction.java
- newrelic-agent/src/main/java/com/newrelic/agent/config/ClassTransformerConfig.java
- newrelic-agent/src/main/java/com/newrelic/agent/config/ClassTransformerConfigImpl.java
- newrelic-agent/src/main/java/com/newrelic/agent/instrumentation/ClassTransformerService.java
- newrelic-agent/src/main/java/com/newrelic/agent/instrumentation/ClassTransformerServiceImpl.java
- newrelic-agent/src/main/java/com/newrelic/agent/instrumentation/InstrumentationImpl.java
- newrelic-agent/src/test/java/com/newrelic/agent/instrumentation/InstrumentationImplTest.java
There are cases for async transactions in which customers call `Token.link()` outside of a transaction, which causes linking to fail.  We can detect this happening and re-transforming the class so that the method is traced with transactions enabled.
To determine the calling class/method, we generate an exception and use the stack trace elements.  Because we're doing this automatically, I added rate limiting so that we only try this once per second.  We could make that time configurable, and we could add a config switch to completely disable this behavior.
https://issues.newrelic.com/browse/NR-74916
The referenced ticket contains an application which can be used to reproduce the issue and verify the fix.
[ ] …
> Instrument methods with dispatcher=true when they invoke token.link() outside of a transaction 

- instrumentation/kafka-clients-metrics-3.0.0/src/main/java/com/nr/instrumentation/kafka/NewRelicMetricsReporter.java
- instrumentation/kafka-clients-metrics-3.0.0/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer_Instrumentation.java
- instrumentation/kafka-clients-metrics-3.0.0/src/main/java/org/apache/kafka/clients/producer/KafkaProducer_Instrumentation.java
This PR adds a new metric that captures the Kafka bootstrap nodes.
[x] Are your contributions backwards compatible with relevant frameworks and APIs? Yes
[x] Does your code contain any breaking changes? No
[x] Does your code introduce any new dependencies? No
> Instrument the Kafka bootstrap nodes

- instrumentation/netty-3.4/src/main/java/com/agent/instrumentation/netty34/RequestWrapper.java
- instrumentation/netty-3.4/src/test/java/netty34/RequestWrapperTest.java
- instrumentation/netty-3.8/src/main/java/com/agent/instrumentation/netty38/RequestWrapper.java
- instrumentation/netty-3.8/src/test/java/netty38/RequestWrapperTest.java
- instrumentation/netty-4.0.0/src/main/java/com/agent/instrumentation/netty40/RequestWrapper.java
- instrumentation/netty-4.0.0/src/test/java/netty40/RequestWrapperTest.java
- instrumentation/netty-4.0.8/src/main/java/com/agent/instrumentation/netty40/RequestWrapper.java
- instrumentation/netty-4.0.8/src/test/java/netty408/RequestWrapperTest.java
This makes the RequestWrapper more efficient since it does not have to compile the pattern each time.
N/A
The CI testing suite should pass.
> Use Pattern.compile in Netty RequestWrapper

- newrelic-agent/src/main/java/com/newrelic/agent/Agent.java
- newrelic-agent/src/main/java/com/newrelic/agent/util/DelegatingInstrumentation.java
- newrelic-agent/src/main/java/com/newrelic/agent/util/InstrumentationWrapper.java
- newrelic-agent/src/main/java/com/newrelic/agent/util/UnwindableInstrumentation.java
- newrelic-agent/src/main/java/com/newrelic/agent/util/UnwindableInstrumentationImpl.java
- newrelic-agent/src/test/java/com/newrelic/agent/util/UnwindableInstrumentationImplTest.java
If the java agent encounters a serious issue on startup, it calls `System.exit`.  It would be better if it gracefully shutdown.  This is a particularly troublesome quality when connecting to running applications.
I have a demo that connects to a Spring Petclinic app and uses the nri-lsi-java tool to connect the agent.  It's causing the app to exit.  Here's the repo: https://source.datanerd.us/saxon/java-agent-crash
This wraps the `Instrumentation` instance so that we can remove class transformers and shutdown the agent if there's an exception.  We only do this for the attach (`agentmain`) case.  `premain` works as it does today.  When everyone is comfortable with this change it'd be nice to use it for premain as well.
https://issues.newrelic.com/browse/NR-84187
I've referenced a test repo …
> Gracefully shutdown the agent if it encounters issues on startup

- agent-bridge/src/main/java/com/newrelic/agent/instrumentation/InstrumentedMethod.java
- agent-bridge/src/main/java/com/newrelic/agent/instrumentation/WeavedMethod.java
The InstrumentedMethod and WeavedMethod are added, in runtime, to methods that are instrumented by the agent.
They are also added to instrumented constructors, even though their target does not list constructors.
This usually does not pose a problem, but may cause failures if that class is validated during runtime.
Fixes #1153
> Fix weavedmethod constructor

- agent-bridge-datastore/src/main/java/com/newrelic/agent/bridge/datastore/ExpiringValueMap.java
- agent-bridge-datastore/src/main/java/com/newrelic/agent/bridge/datastore/JdbcHelper.java
- agent-bridge-datastore/src/test/java/com/newrelic/agent/bridge/datastore/ExpiringValueMapTest.java
- agent-bridge-datastore/src/test/java/com/newrelic/agent/bridge/datastore/JdbcHelperTest.java
Temporary configuration option that will allow the agent to use a `ConcurrentHashMap` implementation rather than the `ExpiringValueMap` implementation for the urlToFactory and urlToDatabaseName maps. To revert to the `ConcurrentHashMap`, set a top level agent config of `use_jdbchelper_vanilla_map`.
Also renamed `ExpiringValueCache` to `ExpiringValueMap`. It now extends the `AbstractMap` class so that we only need variables of type `Map` that can be assigned to either the `ConcurrentHashMap` or `ExpiringValueMap` instances. Otherwise we would have unnecessary if blocks scattered in the methods that use these objects.
This config option will be removed in a future Agent release.
> NR-92387 Add toggle "newrelic.jdbchelper.vanilla_map" to revert map impl

- instrumentation/tomcat-10/src/main/java/com/nr/agent/instrumentation/tomcat10/AsyncListenerFactory.java
- instrumentation/tomcat-10/src/main/java/com/nr/agent/instrumentation/tomcat10/TomcatRequest.java
- instrumentation/tomcat-10/src/main/java/com/nr/agent/instrumentation/tomcat10/TomcatResponse.java
- instrumentation/tomcat-10/src/main/java/com/nr/agent/instrumentation/tomcat10/TomcatServletRequestListener.java
- instrumentation/tomcat-10/src/main/java/org/apache/catalina/connector/Request_Weaved.java
- instrumentation/tomcat-10/src/main/java/org/apache/catalina/core/StandardContext_Weaved.java
This fixes an issue where we miss reporting an Exception stack trace.  This surfaced as a "Spring Boot 3" issue, but it is in reality an issue with our tomcat 10 instrumentation.  Tomcat 10 was migrated to all Jakarta naming packages. There was a key string we use that did not update to the correct jakarta named package that we expect (was javax...)
Essentially the exception thrown in the Spring Boot  controller bubbles up to the `DispatcherServlet extends FrameworkServlet`, which is where we would report this exception. Because the naming was wrong, the transactionData throwable is set to null and we only show the status 500.
And just for completeness, I updated the agent package names to reflect they are in our tomcat10 module vs tomcat7
This screenshot demonstrates
Describe the changes …
> fix tomcat 10 jakarta naming

- .github/workflows/X-Reusable-VerifyInstrumentation.yml
Spring 6 is only compatible with Java 17+. So verify instrumentation needs to be run with at least that version of Java.
> Updating verify instrumentation to run tests with Java 17

- instrumentation/spring-webflux-6.0.0/README.md
> Fix grammar

- instrumentation/kafka-streams-metrics-1.0.0/src/main/java/com/nr/instrumentation/kafka/streams/MetricsScheduler.java
Some numeric metrics from Kafka Streams are not recorded. This fix is here to include them.
> Kafka Streams: Include missing numeric metrics

- instrumentation/oracle-r2dbc/build.gradle
Around March 15, Oracle release version 1.1.1 of its r2dbc drivers and they were incompatible with the agent (maybe it was a botched release).
On April 3 that artifact was re-released and it was again compatible with the agent.
This PR removes the cap that was added.
> Removing cap from oracle-r2dbc

- agent-bridge/src/main/java/com/newrelic/agent/bridge/NoOpPublicApi.java
- agent-bridge/src/main/java/com/newrelic/agent/bridge/PublicApi.java
- agent-bridge/src/main/java/com/newrelic/api/agent/NewRelic.java
- newrelic-agent/src/main/java/com/newrelic/agent/MetricNames.java
- newrelic-agent/src/main/java/com/newrelic/agent/errors/ErrorDataImpl.java
- newrelic-agent/src/main/java/com/newrelic/agent/errors/ErrorGroupCallbackHolder.java
- newrelic-agent/src/main/java/com/newrelic/agent/errors/ErrorServiceImpl.java
- newrelic-agent/src/main/java/com/newrelic/agent/errors/TracedError.java
- newrelic-agent/src/main/java/com/newrelic/agent/service/analytics/ErrorEventFactory.java
- newrelic-agent/src/main/java/com/newrelic/api/agent/NewRelicApiImplementation.java
- newrelic-agent/src/test/java/com/newrelic/agent/errors/ErrorDataImplTest.java
- newrelic-agent/src/test/java/com/newrelic/agent/errors/ExpectedErrorFactoryTest.java
- newrelic-api/src/main/java/com/newrelic/api/agent/ErrorData.java
- newrelic-api/src/main/java/com/newrelic/api/agent/ErrorGroupCallback.java
- newrelic-api/src/main/java/com/newrelic/api/agent/ErrorGrouper.java
- newrelic-api/src/main/java/com/newrelic/api/agent/NewRelic.java
Implements the error grouping feature:
- Callback handler and error data classes
- API upgrade for callback registration
- Callback invoked for each error reported to NR
- Javadocs
- Associated unit tests
> NR-64056 Error grouping

- instrumentation/jdbc-ojdbc-tns/build.gradle
A new version of ojdbc8 no longer works with the jdbc-ojdbc-tns instrumentation module.
> Capping jdbc-ojdbc-tns instrumentation

- instrumentation/lettuce-5.0/src/main/java/com/nr/lettuce5/instrumentation/NRHolder.java
- instrumentation/lettuce-6.0/src/main/java/com/nr/lettuce6/instrumentation/NRHolder.java
Reported NPE on newrelic java agent 7.9 and 7.11 in the lettuce instrumentation
```
java.lang.NullPointerException
at com.nr.lettuce5.instrumentation.NRHolder.end(NRHolder.java:59)
at com.nr.lettuce5.instrumentation.NRSignalTypeConsumer.accept(NRSignalTypeConsumer.java:24)
at com.nr.lettuce5.instrumentation.NRSignalTypeConsumer.accept(NRSignalTypeConsumer.java:13)
}}{{at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.runFinally(FluxDoFinally.java:156)
}}{{at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onError(FluxDoFinally.java:132)
```
https://issues.newrelic.com/browse/NEWRELIC-6527
[ ] Does your code introduce any …
> #NEWRELIC-6527 guard lettuce npe

- .github/workflows/AITs-Servers.yml
Tomee AIT has been failing constantly for a few days. It passes constantly locally. Disabling so other PRs can pass.
> Disabling Tomee AIT

- .github/workflows/Java-Instrumentation-Tests.yml
Reduce developer toil.  We often have to repeatedly re-run tests by observing a failure, logging onto github. triggering a re-run.  Often, this rerun has to happen multiple times. This will retry up to 2 times if the first test, and subsequently the 2nd retry fails. This should reduce the number of times a developer has to manually trigger the job significantly.  Even if the 3 tries doesn't get past a false failure, then a second manual run still nets up to 6 runs.  
This also gives someone a good opportunity to intervene and make sure the failure is not a legit failure before manually kicking off the job after the 1st 3 tries.
*Note, this does not restart a workflow in the case where it is cancelled due to a timeout or some other cancelled condition. It only reruns if there is a test …
> retries on failed instrumentation test

- .github/workflows/GHA-Scala-Instrumentation-Tests.yaml
This PR adds retry logic to the scala instrumentation GHA workflows.  It is essentially the same as what was added to the Java Instrumentation workflows. Timeouts are slightly different because the number of jobs and average finish times.
*This also removes the old github enterprise portion of the workflow.
Example run where first job failed and the retry succeeds. 
https://github.com/newrelic/newrelic-java-agent/actions/runs/4751877319/jobs/8441538352
> retry scala instrumentation

- newrelic-agent/src/main/java/com/newrelic/agent/tracers/jasper/JasperClassFactory.java
This change checks whether the constructor is accessible already.  Sets it to accessible if it is not. |
I reproduced this issue using: Tomcat/9.0.74
I tested this on Tomcat versions Apache Tomcat/8.0.14 (prior to tomcat changes to access level)
And on Apache Tomcat/9.0.74 (a version that has the access changed to package private).
In both cases, confirmed no Exception is thrown, i.e.:
```
2023-03-10T11:49:39,630+1000 [6462 95] com.newrelic FINE: An error occurred auto enabling real user monitoring
java.lang.NoSuchMethodException: org.apache.jasper.compiler.Node$Scriptlet.<init>(java.lang.String, org.apache.jasper.compiler.Mark, org.apache.jasper.compiler.Node)
at java.lang.Class.getConstructor0(Class.java:3349) ~[?:?]
at java.lang.Class.getConstructor(Class.java:2151) ~[?:?]
at …
```
> set constructor accessible if needed for jasper compiler Scriptlet class

- .github/workflows/GHA-Unit-Tests.yaml
Fixing a copy and paste error that allowed a workflow to pass even though the test failed.
> Fixing job success even though test failed

- newrelic-agent/src/main/java/com/newrelic/agent/logging/FileAppenderFactory.java
- newrelic-agent/src/test/java/com/newrelic/agent/logging/FileAppenderFactoryTest.java
This corrects the agent logger agent config so that a RollingFileAppender is only created if the setting `log_limit_in_kbytes` is > 0. Before, if the `log_limit_in_kbytes` was 0 but `log_file_count` was > 1, a RollingFileAppender was created, but with a NoOp trigger policy, no rolling ever actually occurred.  
Created unit tests for these scenarios.
The docs will be clarified with the follow info:
- if `log_daily` is true, it will use the `file_count value`, with a minimum value of 1; if `log_limit_in_kbytes` > 0, a composite trigger policy will be configured: daily roll and size based roll
- if `log_limit_in_kbytes` > 0, a rolling file appender strategy will be configured, using the configured `log_file_count` (minimum of 1)
- Otherwise, no log rolling strategy will be configured
This is …
> Use RollingFileAppender only when log_limit_in_kbytes greater than 0

- .github/workflows/repolinter.yml
The repolinter action used a version of github-script that ran in Node12.
Github is retiring Node12, so that action needs to be updated for the workflow to continue working.
> Repolinter

- instrumentation/jedis-4.0.0/build.gradle
exclude alphas on jedis
Jedis added a 5.0.0-alpha1. Our verifyInstrumentation didn't exclude alphas. Added that to the test config.
https://mvnrepository.com/artifact/redis.clients/jedis
> exclude alphas on jedis

- newrelic-agent/build.gradle
The latest version of JFR removes some debug code that would be printed to STDOUT.
> Updating JFR version

- functional_test/src/test/java/test/newrelic/test/agent/spans/SpanParentTest.java
- newrelic-agent/build.gradle
- newrelic-agent/src/main/java/com/newrelic/agent/profile/v2/Murmur3StringMap.java
- newrelic-agent/src/main/java/com/newrelic/agent/tracing/DistributedTracePayloadImpl.java
- newrelic-agent/src/main/java/com/newrelic/agent/tracing/DistributedTracePayloadParser.java
- newrelic-agent/src/main/java/com/newrelic/agent/transport/DataSenderWriter.java
- newrelic-agent/src/main/java/com/newrelic/agent/util/Obfuscator.java
- newrelic-agent/src/main/java/com/newrelic/agent/utilization/DataFetcher.java
- newrelic-agent/src/main/java/com/newrelic/bootstrap/BootstrapAgent.java
- newrelic-agent/src/test/java/com/newrelic/agent/HeadersUtilTest.java
- newrelic-agent/src/test/java/com/newrelic/agent/JSONSerializerTest.java
- newrelic-agent/src/test/java/com/newrelic/agent/database/DatabaseStatementResponseParserTest.java
- newrelic-agent/src/test/java/com/newrelic/agent/database/SqlObfuscatorTest.java
- newrelic-agent/src/test/java/com/newrelic/agent/profile/ProfileTest.java
- newrelic-agent/src/test/java/com/newrelic/agent/profile/v2/ProfileTest.java
- newrelic-agent/src/test/java/com/newrelic/agent/sql/SqlTraceServiceTest.java
- newrelic-agent/src/test/java/com/newrelic/agent/trace/TransactionTraceTest.java
1. Replace commons-codec Base64 with [Java 8's version](https://docs.oracle.com/javase/8/docs/api/java/util/Base64.html). This doesn't remove commons-codec because it's still a dependency of the httpclient 4.5. `Base64.getEncoder()` and `Base64.getDecoder()` return static constants so there's no construction or allocation happening.
2. Replace guava's Charsets constants with Java 7's [StandardCharsets](https://docs.oracle.com/javase/7/docs/api/java/nio/charset/StandardCharsets.html#UTF_8). The Javadoc implies that the members are deprecated in Java 7.
none
Github Actions when a pull request is made. More details on running the tests locally can be …
> Use some Java 7 and 8 utilities

- agent-bridge/src/main/java/com/newrelic/agent/bridge/PublicApi.java
- agent-bridge/src/main/java/com/newrelic/api/agent/NewRelic.java
- functional_test/src/test/java/test/newrelic/test/agent/api/ApiTest.java
- functional_test/src/test/resources/configs/high_security_config.yml
- instrumentation/servlet-user-5.0/src/main/java/jakarta/servlet/Filter.java
- instrumentation/servlet-user-5.0/src/main/java/jakarta/servlet/Servlet.java
- instrumentation/servlet-user/src/main/java/javax/servlet/Filter.java
- instrumentation/servlet-user/src/main/java/javax/servlet/Servlet.java
- newrelic-agent/src/main/java/com/newrelic/api/agent/NewRelicApiImplementation.java
- newrelic-api/src/main/java/com/newrelic/api/agent/NewRelic.java
Disabled user tracking when high security mode is enabled
> NR-106006 disable userid when high security

- functional_test/src/test/java/test/newrelic/test/agent/servlet/ServletUserTest.java
- instrumentation/servlet-user-5.0/src/main/java/jakarta/servlet/Filter.java
- instrumentation/servlet-user-5.0/src/main/java/jakarta/servlet/Servlet.java
- instrumentation/servlet-user/src/main/java/javax/servlet/Filter.java
- instrumentation/servlet-user/src/main/java/javax/servlet/Servlet.java
Fixes a problem that is missed in the previous PR for the ticket because GHA was not working so tests did not run. The "user" attribute was changed to a custom attribute but I reverted it to be an agent attribute.
> NR-106006 fix how user attribute is set in servlet-user from previous PR

- .github/actions/setup-environment/action.yml
- .github/workflows/X-Reusable-VerifyInstrumentation.yml
Makes the Verify Instrumentation job run using Java 17.
Also removes the gradle wrapper verification, which causes lots of failures due to the Gradle servers not responding.
> Verify instrumentation fix

- infinite-tracing/build.gradle.kts
- infinite-tracing/src/main/java/com/newrelic/ChannelManager.java
- infinite-tracing/src/main/java/com/newrelic/InfiniteTracing.java
- infinite-tracing/src/main/java/com/newrelic/InfiniteTracingConfig.java
- infinite-tracing/src/main/java/com/newrelic/Observer.java
- infinite-tracing/src/main/java/com/newrelic/SpanBatchObserver.java
- infinite-tracing/src/main/java/com/newrelic/SpanConverter.java
- infinite-tracing/src/main/java/com/newrelic/SpanEventSender.java
- infinite-tracing/src/main/java/com/newrelic/SpanObserver.java
- infinite-tracing/src/test/java/com/newrelic/ChannelManagerTest.java
- infinite-tracing/src/test/java/com/newrelic/InfiniteTracingConfigTest.java
- infinite-tracing/src/test/java/com/newrelic/SpanBatchObserverTest.java
- infinite-tracing/src/test/java/com/newrelic/SpanConverterTest.java
- infinite-tracing/src/test/java/com/newrelic/SpanEventSenderTest.java
- infinite-tracing/src/test/java/com/newrelic/SpanObserverTest.java
- newrelic-agent/src/main/java/com/newrelic/agent/config/InfiniteTracingConfig.java
- newrelic-agent/src/main/java/com/newrelic/agent/config/InfiniteTracingConfigImpl.java
- newrelic-agent/src/main/java/com/newrelic/agent/service/ServiceManagerImpl.java
- newrelic-agent/src/test/java/com/newrelic/agent/config/InfiniteTracingConfigImplTest.java
This PR adds support for Infinite Tracing payloads to be both compressed and batched by default. The following changes are included as part of this work:
- Implements support for compressing infinite tracing payloads
- `gzip` compression is enabled by default for batching **and** non-batching configurations
- Implements support for batching spans within infinite tracing payloads
- Defaults for batching are:
- Batching `enabled` by default
- Up to `100` spans bundled per batch
- Waiting (linger) for up to `5s` to fill up the batch before sending
The span data is still streaming over HTTP/2 using gRPC but utilizing compression and batching will significantly reduce payload sizes and bytes over the wire, resulting in significantly lower network transfer costs for customers. 
All new …
> Infinite Tracing payload compression and batching

- instrumentation/cats-effect-2/src/main/scala/com/nr/agent/instrumentation/TokenAwareExecutionContext.scala
This PR is a duplicate of [another one](https://github.com/newrelic/newrelic-java-agent/pull/1173).
As such, here is a copy/paste of the PR description:
In one of previous PRs somebody introduced an info log in CE 2 instrumentation that was being logged on every instrumentation of IO.shift and it wasn't caught by neither `application_logging.enabled` property, nor `log_level`. This PR fixes it by making this log on Finest level only if it's applicable. …
> PR-1173 Fix cats effect 2 logging

- instrumentation/cats-effect-2/src/main/scala/com/nr/agent/instrumentation/TokenAwareExecutionContext.scala
In one of previous PRs somebody introduced an info log in CE 2 instrumentation that was being logged on every instrumentation of IO.shift and it wasn't caught by neither `application_logging.enabled` property, nor `log_level`. This PR fixes it by making this log on Finest level only if it's applicable.
Github Actions when a pull request is made. More details on …
> Log Cats Effect 2 instrumentation with Finest log level

- newrelic-agent/src/main/java/com/newrelic/agent/LifecycleObserver.java
- newrelic-agent/src/main/java/com/newrelic/agent/instrumentation/ClassTransformerService.java
- newrelic-agent/src/main/java/com/newrelic/agent/instrumentation/ClassTransformerServiceImpl.java
- newrelic-agent/src/main/java/com/newrelic/agent/util/asm/Utils.java
- newrelic-agent/src/test/java/com/newrelic/agent/util/asm/UtilsTest.java
@toddwest pointed out that when using attach (calling `agent main`) the agent does not re-instrument classes using custom instrumentation (the `@Trace`) annotation.  This fixes that.
Please reach out to me for a test application.  I have an internal application I can share.
> Retransform classes using Trace annotation on attach

- gradle/script/spotbugs-exclude-filter.xml
- newrelic-weaver/src/main/java/com/newrelic/weave/GeneratedNewFieldMethod.java
- newrelic-weaver/src/main/java/com/newrelic/weave/utils/WeaveUtils.java
Fix findings mentioned in https://issues.newrelic.com/browse/NR-118548
com.newrelic.weave.utils.WeaveUtils.getRuntimeMaxSupportedClassVersion()
Boxing/unboxing to parse a primitive, line 185
com.newrelic.weave.GeneratedNewFieldMethod.isGeneratedNewFieldMethod(MethodNode, Collection)
Useless condition: it's known that nextInsnOpcode <= 177 (0xb1) at this point, line 98
> Address spotbugs findings for the weaver module

- .github/codecov.yml
- .github/workflows/GHA-Scala-Functional-Tests.yaml
- .github/workflows/GHA-Unit-Tests.yaml
Previously, we were collecting the reports and uploading to codecov for each version of the java runs. This is unnecessary because the coverage is the same across versions. We only need to upload once.
I chose Java 17 for the Java units and Java 11 for the scala specific tests.   
It's unclear if this directly resolved the issue with codecov that we were experiencing. That is still an open question, however the most recent runs have succeeded.  It's possible that the overwrites were causing an issue, but there is no direct evedince of that as we did not have any error reporting from codecov.  The GHA action showed successful uploads. Codecov side was showing upload errors.  Will observe, but either way, this optimization is better.
*also, use token for more efficient uploads and codecov …
> only upload coverage reports to codecov once

- gradle/script/spotbugs-exclude-filter.xml
- newrelic-agent/src/main/java/com/newrelic/agent/TransactionApiImpl.java
- newrelic-agent/src/main/java/com/newrelic/agent/attributes/AgentAttributeSender.java
- newrelic-agent/src/main/java/com/newrelic/agent/attributes/CustomAttributeSender.java
- newrelic-agent/src/main/java/com/newrelic/agent/errors/ErrorMessageReplacer.java
- newrelic-agent/src/main/java/com/newrelic/agent/instrumentation/PointCutConfiguration.java
- newrelic-agent/src/main/java/com/newrelic/agent/instrumentation/classmatchers/ManyClassMatcher.java
- newrelic-agent/src/main/java/com/newrelic/agent/profile/ProfilerParameters.java
- newrelic-agent/src/main/java/com/newrelic/agent/service/analytics/SpanEventFactory.java
- newrelic-agent/src/main/java/com/newrelic/agent/trace/RandomTransactionSampler.java
- newrelic-agent/src/main/java/com/newrelic/agent/tracers/AbstractTracer.java
- newrelic-agent/src/main/java/com/newrelic/agent/tracers/MethodExitTracerNoSkip.java
- newrelic-agent/src/main/java/com/newrelic/agent/tracers/jasper/GeneratorVisitTracerFactory.java
- newrelic-agent/src/main/java/com/newrelic/agent/utilization/GCP.java
Added `final` to certain variables:
- com.newrelic.agent.TransactionApiImpl.INSTANCE
- com.newrelic.agent.attributes.AgentAttributeSender.ATTRIBUTE_TYPE
- com.newrelic.agent.attributes.CustomAttributeSender.ATTRIBUTE_TYPE
- com.newrelic.agent.errors.ErrorMessageReplacer.NO_REPLACEMENT
- com.newrelic.agent.service.analytics.SpanEventFactory.DEFAULT_SYSTEM_TIMESTAMP_SUPPLIER
- com.newrelic.agent.tracers.AbstractTracer.ATTRIBUTE_TYPE
- com.newrelic.agent.tracers.jasper.GeneratorVisitTracerFactory.RUM_STATE_PROCESSOR_KEY
- com.newrelic.agent.utilization.GCP.PROVIDER
Other corrections:
-com.newrelic.agent.trace.RandomTransactionSampler.harvest(String)
- Comparision of String param using == or != , line 60
- com.newrelic.agent.TransactionApiImpl.clearTransaction()
- Null check of tx at line 477 …
> Spotbugs corrections from NR-118554 and NR-118558

- .github/workflows/GHA-Scala-Functional-Tests.yaml
- .github/workflows/GHA-Unit-Tests.yaml
This just reduces our footprint and runtime a little more by only uploading the jacoco coverage html archives for one Java test (one for the scala tests and one for the java units). These reports are all the same, so no need to save and upload for each JRE run.
> we only need 1 each archive

- .github/workflows/Create-Custom-Jar.yml
The custom jar workflow was missing an environment variable which prevented the AWS credentials from being set.
> Adding missing environment variable on Create Custom Jar workflow

- gradle/script/java.gradle
improve our coverage results by excluding the NoOp classes. These are just stubs with getters and setters.  There is no good reason to evaluate these classes.
> exclude pointless classes from cov

- utils/README.md
- utils/writeIndexPage.py
- utils/writeTestsFailuresPage.py
This PR adds utility scripts to the gh-pages branch. The scripts write .html files to display on our gh-pages hosted site.
There are two scripts in this PR:
- `writeIndexPage.py`: writes an index.html page for a resource listing and forwarding to its contents.
- `writeTestsFailuresPage.py`: parses the html files in a test folder for failures, then lists and forwards to failing test suites.
The included README.md summarizes the scripts and their usage.
> Gh pages utilities

- CHANGELOG.md
Full change log links was posted to the wrong version, which was missing the full change log link.
Fixes both issues.
> Fixing full changelog links

- newrelic-agent/src/main/java/com/newrelic/agent/Agent.java
- newrelic-agent/src/main/java/com/newrelic/agent/config/SecurityAgentConfig.java
In high_security mode request and message queue parameters can't be collected, without request and it's parameters IAST won't be able to work properly, hence disabling.
reference: https://docs.newrelic.com/docs/apm/agents/java-agent/configuration/java-agent-configuration-config-file/#cfg-enable_high_security
> Disable IAST if high_security is enabled.

- instrumentation/servlet-5.0/src/main/java/com/nr/instrumentation/servlet5/NRResponseWrapper.java
- instrumentation/servlet-6.0/src/main/java/com/nr/instrumentation/servlet6/NRResponseWrapper.java
NRResponseWrapper class in our Servlet 5 and Servlet 6 instrumentation doesn't implement the getStatus method.
This came up in testing Jakarata 10 EE.  Testing shows that the http.StatusCode method was not being added to agent attributes (an assertion on attribute map length revealed the issue).
The method in the wrapper always returns 0 causing the put to the attributes to be skipped.
https://github.com/newrelic/newrelic-java-agent/blob/aeb1c4e0d8d0852909d8012fc92721c57ade1136/newrelic-agent/src/main/java/com/newrelic/agent/dispatchers/WebRequestDispatcher.java#L107
> implement getStatus for nrwrapper

- agent-bridge-datastore/src/test/java/com/newrelic/agent/bridge/datastore/LegacyDatabaseMetricsTest.java
- agent-bridge-datastore/src/test/java/com/newrelic/agent/bridge/datastore/R2dbcObfuscatorTest.java
This PR adds tests to agent-bridge-datastore:
- A few additional tests for R2dbcObfuscator
- A new test class for LegacyDatabaseMetrics
> Add coverage agentbridgedatastore

- .github/workflows/GHA-Scala-Functional-Tests.yaml
remove scala codecov upload
These add little value. 76 lines of code covered at 100%.  We are removing because they cause the upload to codecov to inflate the coverage and causes confusion when trying to understand the coverage and trend.
> remove scala codecov upload

- .github/actions/setup-environment/action.yml
- instrumentation/aws-wrap-0.7.0/build.gradle
- instrumentation/jboss-7/build.gradle
- instrumentation/resin-4/lib/.gitignore
- instrumentation/solr-jmx-7.0.0/build.gradle
- Removes verify instrumentation configuration from aws-wrap and jboss-7, since these are no longer available, we cannot download the artifacts to test;
- Adds a .gitignore to `instrumentation/resin-4/lib/` to prevent any file there from being committed;
- Updates the setup environment composite action to use the new proprietary-jars file.
> JCenter fixes

- instrumentation/kafka-connect-spans-2.0.0/build.gradle
- instrumentation/kafka-connect-spans-3.3.0/build.gradle
Kafka Connect spans instrumentation aliases were `kafka-connect`. Which does not match the metrics instrumentation which is `kafka-connect-metrics`. This PR fixes that.
> Fixing alias for Kafka Connect instrumentations

- newrelic-agent/src/test/java/com/newrelic/agent/logging/Log4jLogManagerTest.java
This PR creates unit tests for the Log4jLogManager class, specifically for the method `configureLogger`. The tests assert on how the logger responds to the agentConfig.
> Add coverage nragent logging

- .github/actions/setup-environment/action.yml
- .github/workflows/Test-AITs.yml
- .github/workflows/VerifyInstrumentation.yml
- .github/workflows/X-Reusable-BuildAgent.yml
- .github/workflows/X-Reusable-VerifyInstrumentation.yml
Verify instrumentation uses an excessive amount of caching for its Gradle tasks.
This is causing some cache entries to be evicted before they should, due to size limit imposed by GHA.
Also, the GHA cache servers start sending 429 responses due to the amount of transfers this action makes.
By decreasing the amount of cache sent both issues should be decreased if not eliminated.
This PR changes how the Gradle cache is used. It will be read only for all workflows, except the build agent for the scheduled Verify Instrumentation run.
With this we should have a reasonable sized cache, which should be enough to help all the builds.
> Using read only Gradle cache for most workflows

- newrelic-agent/src/main/resources/META-INF/excludes
Exclude `com.ibm.ws.webcontainer.servlet.ServletWrapperImpl` class
> Add WAS specific servlet exclusion

- instrumentation/graphql-java-17.0/build.gradle
Verify Instrumentation workflow checked that the version 21 of this library will not work with the current instrumentation module.
#1375
> Capping graphql compatibility

- instrumentation/kafka-clients-metrics-3.0.0/src/main/java/com/nr/instrumentation/kafka/MetricsScheduler.java
- instrumentation/kafka-clients-metrics-3.0.0/src/main/java/com/nr/instrumentation/kafka/NewRelicMetricsReporter.java
- instrumentation/kafka-clients-metrics-3.0.0/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer_Instrumentation.java
- instrumentation/kafka-clients-metrics-3.0.0/src/main/java/org/apache/kafka/clients/producer/KafkaProducer_Instrumentation.java
- instrumentation/kafka-clients-metrics-3.0.0/src/test/java/com/nr/agent/instrumentation/kafka/Kafka3MessageTest.java
These changes are a second iteration of [PR#1130](https://github.com/newrelic/newrelic-java-agent/pull/1130).
Since a service could have multiple Kafka consumers and producers, and each one could connect to different clusters, we want to introduce these new metrics to understand the relationship between consumers/producers, topics and nodes.
Although `Kafka3MessageTest` is disabled because it's flaky on GHA, I added some more checks around the metrics I introduced and I checked that the tests pass locally.
✅ Are your contributions backwards compatible with relevant frameworks and APIs? Yes
✅ Does your code contain any breaking changes? No
✅ Does your code introduce any new dependencies? No
> Add new Nodes metrics that include the consumed/produced topics

- newrelic-agent/src/test/java/com/newrelic/agent/tracers/ExternalComponentNameFormatTest.java
- newrelic-agent/src/test/java/com/newrelic/agent/tracers/ExternalComponentTracerTest.java
- newrelic-agent/src/test/java/com/newrelic/agent/tracers/NewExternalComponentTracerTest.java
This PR 
- creates tests for ExternalComponentTracer (mostly testing the methods of its superclass AbstractComponentTracer)
- renames the previous ExternalComponentTracerTest file to ExternalComponentMetricNameTest.
> Add coverage nragent tracers

- gradle/script/java.gradle
- newrelic-agent/src/test/java/com/newrelic/agent/GCServiceTest.java
The additional exclusions are some of the classes identified as near impossible to unit test because of the nature of the class (class loading, byte code manipulation, non-mockable HTTP interactions).
> Test exclusions and GCService Test

- .github/workflows/GHA-Unit-Tests.yaml
- .github/workflows/Test-AITs.yml
- newrelic-agent/src/test/java/com/newrelic/agent/TransactionApiImplTest.java
- newrelic-agent/src/test/java/com/newrelic/agent/instrumentation/NonUrlClassLoadersTest.java
- newrelic-agent/src/test/java/com/newrelic/agent/stats/DataUsageStatsTest.java
Basic static mock example:
```
try (MockedStatic<com.newrelic.agent.Transaction> mockStaticTxn = mockStatic(com.newrelic.agent.Transaction.class)) {
mockStaticTxn.when(() -> com.newrelic.agent.Transaction.getTransaction(false)).thenReturn(mockTxn);
//Call the method under test ...
verify(mockTxn).requestDestroyed();
}
```
The mocking is enclosed in a try-with-resource block so the mocked gets "closed" when we're done with it. The `when` clauses are lambda that work like instance mocks.
> Test example with static mocks

- .github/workflows/Test-AITs.yml
Recently some tests that use testcontainers start failing.
The first one would blow up and give no clue to what was going on.
Then a few more started failing, but they provided logs which helped diagnose the problem.
It seems that the Docker was running out of its disk space. Looks like that is not hygienized between runs.
So this PR adds a step to clean that up. It also re enables a test that was recently disabled.
> Docker fix

- instrumentation/httpurlconnection/src/main/java/com/nr/agent/instrumentation/httpurlconnection/DefaultThreadFactory.java
HttpUrlConnection instrumentation has a thread pool where all the threads have a name with a number on the end, except the first thread.
This causes the first thread to report different metrics than the other ones.
This PR normalizes the name of the threads so all end in a number, so all will report under the same metrics.
> HttpUrlConnection cleanup thread name normalization

- instrumentation/graphql-java-17.0/src/main/java/com/nr/instrumentation/graphql/GraphQLObfuscator.java
On GraphQL 19.7 the Guava dependency was updated.
With that, a class from Guava that was used in GraphQL instrumentation is no longer available.
This PR removes the usage of that class.
> Removing use of Guava in GraphQL 17 instrumentation

- newrelic-agent/src/main/java/com/newrelic/agent/Agent.java
- newrelic-agent/src/main/java/com/newrelic/agent/config/JavaVersionUtils.java
- newrelic-agent/src/main/java/com/newrelic/bootstrap/BootstrapAgent.java
Resolves #1451 
To facilitate Java 21 testing by the community, we're publicizing a config option to allow unsupported java versions to be used with the agent. To enable experimental mode, set the following environment variable or system property to true:
Env variable: NEW_RELIC_EXPERIMENTAL_RUNTIME=true
Java system property: newrelic.config.experimental_runtime=true
These config options will also be output in the stdout log when attempting to use an unsupported Java version.
> Add experimental config option to unsupported java version message

- newrelic-agent/src/main/java/com/newrelic/agent/attributes/AttributeNames.java
- newrelic-agent/src/main/java/com/newrelic/agent/service/analytics/SpanEventFactory.java
- newrelic-agent/src/main/java/com/newrelic/agent/tracers/DefaultTracer.java
- newrelic-agent/src/test/java/com/newrelic/agent/metrics/JsonTraceSegment.java
- newrelic-agent/src/test/java/com/newrelic/agent/service/analytics/SpanEventFactoryTest.java
- newrelic-agent/src/test/java/com/newrelic/agent/tracers/DefaultSqlTracerClmTest.java
- newrelic-agent/src/test/java/com/newrelic/agent/tracers/DefaultSqlTracerTest.java
Knowing the thread id of different spans allows the UI to accurately calculate the exclusive time of segments.  `thread.id` is a standard OTel attribute and they recommend that it be reported for all spans.
https://opentelemetry.io/docs/specs/otel/trace/semantic_conventions/span-general/
Attribute | Type | Description | Examples | Requirement Level
-- | -- | -- | -- | --
thread.id | int | Current “managed” thread ID (as opposed to OS thread ID). | 42 | Recommended …
> feat: add thread.id attribute to Spans

- newrelic-agent/src/main/resources/META-INF/excludes
fixes #1348 
This PR addresses `classCircularityError` that appeared when running the agent with Sonarqube Server v.9.9 and Java 17. 
Proposed change: add the following four classes to default excludes file: 
```
java/util/AbstractList$RandomAccessSpliterator
java/util/stream/MatchOps$MatchOp
java/util/stream/MatchOps$BooleanTerminalSink
javax/security/auth/Subject$SecureSet$1
``` 
These are not known to be weaved by the agent or security agent but appear to fix the issue on SQ.
> Update class excludes list for Sonarqube9.9

- newrelic-agent/src/main/java/com/newrelic/agent/service/analytics/SpanEventFactory.java
- newrelic-agent/src/test/java/com/newrelic/agent/service/analytics/SpanEventFactoryTest.java
`thread.id` was added as an agent attribute. But it was supposed to be an intrinsic attribute.
> Setting thread.id as an intrinsic

- agent-model/src/main/java/com/newrelic/agent/model/SpanEvent.java
- newrelic-agent/src/main/java/com/newrelic/agent/service/analytics/SpanEventFactory.java
- newrelic-agent/src/main/java/com/newrelic/agent/service/analytics/TracerToSpanEvent.java
- newrelic-agent/src/test/java/com/newrelic/agent/service/analytics/SpanEventFactoryTest.java
This includes stack traces in client spans.  The attribute key name is `code.stacktrace`.
The DT and transaction trace UIs will be updated to display the stack traces.
You can use the UI builds from [this PR](https://source.datanerd.us/app-experience/apm-nerdlets/pull/1761) to test with an agent.
[ ] Does your code …
> Include stack traces in client spans

- instrumentation-test/src/main/java/com/newrelic/agent/introspec/internal/IgnoringJarCollectorService.java
- newrelic-agent/src/main/java/com/newrelic/agent/instrumentation/context/InstrumentationClassTransformer.java
- newrelic-agent/src/main/java/com/newrelic/agent/instrumentation/context/InstrumentationContextManager.java
- newrelic-agent/src/main/java/com/newrelic/agent/service/ServiceManagerImpl.java
- newrelic-agent/src/main/java/com/newrelic/agent/service/module/ClassToJarPathSubmitter.java
- newrelic-agent/src/main/java/com/newrelic/agent/service/module/ClassToJarPathSubmitterImpl.java
- newrelic-agent/src/main/java/com/newrelic/agent/service/module/JarCollectorInputs.java
- newrelic-agent/src/main/java/com/newrelic/agent/service/module/JarCollectorService.java
- newrelic-agent/src/main/java/com/newrelic/agent/service/module/JarCollectorServiceImpl.java
- newrelic-agent/src/test/java/com/newrelic/agent/MockServiceManager.java
- newrelic-agent/src/test/java/com/newrelic/agent/config/ClassTransformerConfigImplTest.java
- newrelic-agent/src/test/java/com/newrelic/agent/instrumentation/IncludeExcludeTest.java
- newrelic-agent/src/test/java/com/newrelic/agent/service/module/ClassToJarPathSubmitterTest.java
- newrelic-agent/src/test/java/com/newrelic/agent/service/module/JarCollectorInputsTest.java
- newrelic-agent/src/test/java/com/newrelic/agent/service/module/JarCollectorServiceImplTest.java
Resolves #1342 
Currently, the jar collector functionality is implemented via the ClassMatchVisitor pattern. The problem with this approach is that the registered visitors aren't executed when a class is excluded from transformation. In the case of certain jars (Spring Security for example), every single class in the jar is excluded, so the visitors are never executed, so the jar collector is never aware of the enclosing jar.
This PR keeps the exact same jar discovery logic in place, however the flow is no longer invoked after a class is transformed. Instead, all classes, prior to being checked for transformation eligibility are submitted to the jar collector. This means that no jars will be missed, even if every class within a jar is excluded, skipped, etc.
> Decouple jar scanning function from class match vistor collection

- newrelic-agent/src/main/java/com/newrelic/agent/utilization/CGroup.java
- newrelic-agent/src/main/java/com/newrelic/agent/utilization/DockerData.java
- newrelic-agent/src/test/java/com/newrelic/agent/utilization/DockerDataTest.java
- newrelic-agent/src/test/resources/com/newrelic/agent/uncross_agent_tests/cgroup_v2_docker_container_id/README.md
- newrelic-agent/src/test/resources/com/newrelic/agent/uncross_agent_tests/cgroup_v2_docker_container_id/cases.json
- newrelic-agent/src/test/resources/com/newrelic/agent/uncross_agent_tests/cgroup_v2_docker_container_id/cgroup_v2_expected.txt
- newrelic-agent/src/test/resources/com/newrelic/agent/uncross_agent_tests/cgroup_v2_docker_container_id/docker_id_invalid_characters.txt
- newrelic-agent/src/test/resources/com/newrelic/agent/uncross_agent_tests/cgroup_v2_docker_container_id/docker_id_too_long.txt
- newrelic-agent/src/test/resources/com/newrelic/agent/uncross_agent_tests/cgroup_v2_docker_container_id/docker_id_too_short.txt
- newrelic-agent/src/test/resources/com/newrelic/agent/uncross_agent_tests/cgroup_v2_docker_container_id/docker_linux2.6.26_v1_enabled.txt
- newrelic-agent/src/test/resources/com/newrelic/agent/uncross_agent_tests/cgroup_v2_docker_container_id/linux_prefix.txt
Resolves #1358 
This PR adds support for getting the containerId from a docker container with Linux cgroup v2. 
Previously, the containerId was grabbed from `proc/self/cgroup` for containers with cgroup V1. Now, the id is grabbed from `proc/self/mountinfo`, with fallthrough to `proc/self/cgroup` if that file is missing.  
- This is the widely accepted approach for now, though the API is expected to change and a long-term solution is supposedly in the works. 
- The current implementation is based on best-effort research towards the contents of `proc/self/mountinfo`. Because this solution is a bit hacky, there isn't clear documentation about what's supposed to be in there in different environments/providers. The matching logic may need to be updated in the future.
> Cgroupsv2 container

- newrelic-agent/src/main/java/com/newrelic/agent/config/AgentConfigImpl.java
This PR is aimed at relocating exclusion packages from "com.newrelic." and "com.nr.*" to "com.newrelic.agent.security.instrumentation.*" and "com.nr.agent.security.instrumentation.*" This change is specific to csec requirements, and it ensures that instrumentation only affects csec classes, aligning with our intended target.
> NR-164405 Fix Package Exclusion Issue with com.nr and com.newrelic

- newrelic-agent/src/main/java/com/newrelic/agent/service/analytics/SpanEventFactory.java
- newrelic-agent/src/test/java/com/newrelic/agent/service/analytics/SpanEventFactoryTest.java
- newrelic-agent/src/test/java/com/newrelic/agent/service/analytics/SpanEventsServiceTest.java
- newrelic-agent/src/test/java/com/newrelic/agent/tracers/DefaultSqlTracerClmTest.java
- newrelic-agent/src/test/java/com/newrelic/agent/tracers/DefaultSqlTracerTest.java
- newrelic-agent/src/test/java/com/newrelic/agent/tracers/DefaultTracerClmTest.java
- newrelic-agent/src/test/java/com/newrelic/agent/tracers/DefaultTracerTest.java
This is a duplicate of the following [PR](https://github.com/newrelic/newrelic-java-agent/pull/1504).
This adds attributes to Spans so that we can correlate aggregate database and external metric back to their related client spans.
* db.system
* db.operation
* db.collection
* server.address
* server.port
https://opentelemetry.io/docs/specs/otel/trace/semantic_conventions/http/
https://opentelemetry.io/docs/specs/otel/trace/semantic_conventions/database/
I added unit tests to cover the new attributes.  I can a couple of local apps with a local build and verified that the attributes were correctly added.
[ X ] Are your contributions backwards compatible with relevant frameworks and APIs?
[ ] Does your code contain any breaking …
> Add database and external span attributes to correlate to metric data (Duplicate)

- newrelic-agent/src/main/java/com/newrelic/agent/service/analytics/SpanEventFactory.java
- newrelic-agent/src/test/java/com/newrelic/agent/service/analytics/SpanEventFactoryTest.java
- newrelic-agent/src/test/java/com/newrelic/agent/service/analytics/SpanEventsServiceTest.java
- newrelic-agent/src/test/java/com/newrelic/agent/tracers/DefaultSqlTracerClmTest.java
- newrelic-agent/src/test/java/com/newrelic/agent/tracers/DefaultSqlTracerTest.java
- newrelic-agent/src/test/java/com/newrelic/agent/tracers/DefaultTracerClmTest.java
- newrelic-agent/src/test/java/com/newrelic/agent/tracers/DefaultTracerTest.java
This adds attributes to Spans so that we can correlate aggregate database and external metric back to their related client spans.
* db.system
* db.operation
* db.collection
* server.address
* server.port
https://opentelemetry.io/docs/specs/otel/trace/semantic_conventions/http/
https://opentelemetry.io/docs/specs/otel/trace/semantic_conventions/database/
I added unit tests to cover the new attributes.  I can a couple of local apps with a local build and verified that the attributes were correctly added.
[ X …
> Add database and external span attributes to correlate to metric data

- newrelic-agent/src/main/java/com/newrelic/agent/MetricNames.java
- newrelic-agent/src/main/java/com/newrelic/api/agent/NewRelicApiImplementation.java
- newrelic-agent/src/test/java/com/newrelic/api/agent/NewRelicApiImplementationTest.java
> add s12y metrics for setUserId API call

- instrumentation/tomcat-10/src/main/java/com/nr/agent/instrumentation/tomcat10/TomcatServletRequestListener.java
Resolves #1393 
As of Spring 6, when controller advice is used for controller exception handling, the caught exception is now stored in the servlet attribute map with the `org.springframework.web.servlet.DispatcherServlet.EXCEPTION` key. Other exceptions are still present in the `jakarta.servlet.error.exception` key.
With this change, exceptions now report properly to NR.
> Check for Spring6 specific servlet attribute for advice-handled exception 

- instrumentation/jetty-9.3/README.md
Adds a readme that describes how the Jetty instrumentation works with Jetty Continuations and the servlet async API.
> Add readme to jetty-9.3 instrumentation

- newrelic-agent/build.gradle
Resolves #1535 
Forces the `commons-codec` transitive dependency of `org.apache.httpcomponents:httpclient:4.5.13` to v1.13 to eliminate a [vulnerability](https://devhub.checkmarx.com/cve-details/Cxeb68d52e-5509/?utm_source=jetbrains&utm_medium=referral&utm_campaign=idea).
The dependency tree of `httpclient` for the `shadowIntoJar` config now look like:
```
+--- org.apache.httpcomponents:httpclient:4.5.13
|    +--- org.apache.httpcomponents:httpcore:4.4.13
|    +--- commons-logging:commons-logging:1.2
|    \--- commons-codec:commons-codec:1.11 -> 1.13
```
> Force commons-codec to v1.13

- newrelic-agent/src/main/java/com/newrelic/agent/instrumentation/custom/ScalaTraitFinalFieldTransformer.java
- newrelic-agent/src/main/java/com/newrelic/agent/util/asm/CustomClassLoaderClassWriter.java
- newrelic-agent/src/main/java/com/newrelic/agent/util/asm/PatchedClassWriter.java
- newrelic-agent/src/test/java/com/newrelic/agent/util/asm/CustomClassLoaderClassWriterTest.java
> Resolve missing class exception on Scala instrumentation.

- newrelic-agent/src/main/java/com/newrelic/agent/errors/DeadlockTraceError.java
- newrelic-agent/src/main/java/com/newrelic/agent/errors/ErrorServiceImpl.java
- newrelic-agent/src/main/java/com/newrelic/agent/errors/HttpTracedError.java
- newrelic-agent/src/main/java/com/newrelic/agent/errors/ThrowableError.java
- newrelic-agent/src/main/java/com/newrelic/agent/errors/TracedError.java
- newrelic-agent/src/test/java/com/newrelic/agent/RPMServiceTest.java
- newrelic-agent/src/test/java/com/newrelic/agent/errors/TracedErrorTest.java
This will add the transaction GUID to any TracedError instance that is created as part of a transaction. This will then propagate to the backend when data is sent via the `error_data` method. The resulting JSON for the payload is below.  The GUID will show up in the 6th element of the top level JSON array. For other TracedErrors, this element will be missing (the same behavior prior to the change).
```
[
[
1697737126134,
"WebTransaction/SpringController/withoutadvice (GET)",
"Request processing failed: java.lang.IllegalArgumentException: without advice",
"jakarta.servlet.ServletException",
{
"intrinsics": {
"traceId": "5b5891157fc73f504d9b4efc60fff1aa",
"error.expected": false,
"guid": "4afa298e0f244149",
"parent.transportType": "HTTP",
"priority": 1.191872,
"sampled": true
}, …
```
> Add transaction GUID to all applicable TracedError instances

- CHANGELOG.md
Update changelog to include release notes for 8.6.0 and 8.7.0
> Update CHANGELOG.md for releases 8.7.0 and 8.6.0

- newrelic-agent/build.gradle
Previous version of JFR Daemon was logging more than it should. Using a newer less verbose version.
> Bumping up JFR daemon version

- newrelic-agent/src/main/java/com/newrelic/agent/instrumentation/pointcuts/frameworks/spring/MethodInvokerPointCut.java
Resolves #1574 
With this change, transaction names that are composed of class name + method name from a controller that has a CGLIB proxy generated will no longer show the proxy class name but the original class name.  This image shows an example of transactions names with and without this change:
> Normalize CGLIB proxied class names

- agent-bridge/src/main/java/com/newrelic/agent/bridge/NoOpAgent.java
- agent-bridge/src/main/java/com/newrelic/agent/bridge/NoOpErrorApi.java
- agent-bridge/src/main/java/com/newrelic/agent/bridge/NoOpPublicApi.java
- agent-bridge/src/main/java/com/newrelic/agent/bridge/PublicApi.java
- functional_test/src/test/java/com/newrelic/agent/extension/FakeExtensionAgent.java
- functional_test/src/test/java/com/newrelic/agent/instrumentation/weaver/WeaveTest.java
- newrelic-agent/src/main/java/com/newrelic/agent/AgentImpl.java
- newrelic-agent/src/main/java/com/newrelic/api/agent/NewRelicApiImplementation.java
- newrelic-api/src/main/java/com/newrelic/api/agent/Agent.java
- newrelic-api/src/main/java/com/newrelic/api/agent/ErrorApi.java
- newrelic-api/src/main/java/com/newrelic/api/agent/NewRelic.java
- newrelic-api/src/main/java/com/newrelic/api/agent/NoOpAgent.java
Years ago we refactored many of our agent APIs to have interfaces.  For example, static methods on `NewRelic` like `incrementCounter` exist on the `MetricAggregator`.  We never created an interface for our error apis.  Having an interface is helpful to customers because they can reference the interface in their code, mock it out and verify that it's called in their tests.  Multiple New Relic teams have actually created their own `ErrorApi` interface to wrap our static `NewRelic` implementation for testing purposes.
I'd like to update our `NewRelic` static apis to …
> Add an interface for our error API

- instrumentation/spring-webflux-6.0.0/build.gradle
Limiting the range that `spring-webflux-6.0.0` should apply to.
> Capping verification of spring-webflux-6.0.0 module

- .github/workflows/X-Reusable-VerifyInstrumentation.yml
Around once per week, the Verify Instrumentation job has failed because the cache server returns a 429 (Too Many Requests).
To prevent that, this PR limits the number of jobs that  the workflow can run concurrently. GHA limits the number of parallel jobs in a repository(?) to 20. This PR sets the number of parallel jobs in a matrix to 7. Since there are 2 instances of that matrix running in parallel, it effectively caps the number of parallel jobs to 14.
> Decreasing verify instrumentation parallelism

- instrumentation/mule-3.7/build.gradle
- instrumentation/mule-base/build.gradle
- instrumentation/mule-ei1/build.gradle
- instrumentation/mule-ei2/build.gradle
The configuration for verification of some Mule instrumentation modules was too restrictive and were not testing versions it should apply to.
This PR opens up the range and adds exclusions as necessary.
> Updating mule verification

- .github/workflows/publish_main_snapshot.yml
- .github/workflows/publish_release.yml
- newrelic-opentelemetry-agent-extension/build.gradle.kts
Resolves https://github.com/newrelic/newrelic-java-agent/issues/1594
Publishes `newrelic-opentelemetry-agent-extension`:
- Snapshots artifacts on merges to `main`
- Staged artifacts to Sonatype on agent release
> Nr 180859 publish otel extension

- CHANGELOG.md
Fixing typos in changelog `http.responseCode` -> `httpResponseCode`.
> Typo in changelog

- newrelic-agent/src/main/java/com/newrelic/agent/AgentImpl.java
We occasionally get an NPE in our logs
```
java.lang.NullPointerException: Cannot invoke "com.newrelic.agent.RPMServiceManager.getRPMService()" because the return value of "com.newrelic.agent.service.ServiceManager.getRPMServiceManager()" is null
at com.newrelic.agent.service.ServiceFactory.getRPMService(ServiceFactory.java:103)
at com.newrelic.agent.AgentImpl.getLinkingMetadata(AgentImpl.java:154)
at com.newrelic.agent.bridge.logging.AppLoggingUtils.getLinkingMetadataBlob(AppLoggingUtils.java:57)
```
It looks like it comes from here, so I added a guard. `AgentLinkingMetadata.getLinkingMetadata` already handles the case if `IRPMService` is null, but I figured _some_ linking metadata was better than none.
An alternative implementation would simply bypass this entirely if there was no …
> Don't throw if no RPMServiceManager

- instrumentation/apache-log4j-1/src/test/java/org/apache/log4j/ContextDataTest.java
Log4J1 has a quirky when checking Java versions that caused the MDC functionality to fail when running with Java 21(.0.0).
After Java 21.0.1 was released, this issue is gone.
Fixes #1547
> Reenable Log4J1 MDC test

- instrumentation/spring-webclient-5.0/src/main/java/com/nr/agent/instrumentation/spring_webclient/Util.java
- instrumentation/spring-webclient-5.0/src/test/java/com/nr/instrumentation/WebClientTest.java
- instrumentation/spring-webclient-5.0/src/test/resources/spans.yml
In the current version, we dont have http status code for http clients using spring webclient.
> adding httstatus in segment

- newrelic-agent/src/main/java/com/newrelic/agent/config/SlowTransactionsConfigImpl.java
Resolves #1562 
Slow Transaction Detection:
- Default enabled is now `true`
- Default threshold is now `600000 ms` (10 minutes)
> SlowTxnDetection - default to true and bump threshold to 10 minutes

- instrumentation/reactor-3.3.0/README.md
Updates reactor-3.3.0 readme to reflect that it only works when the Mono/Flux is subscribed on a Scheduler.
> Adding some functionality info on reactor-3.3.0 readme

- .github/workflows/publish_release.yml
- newrelic-opentelemetry-agent-extension/build.gradle.kts
Comment out task to publish otel extensions. This is required to publish our 8.8.0 release.
> Comment Out Publish Step for Otel Extension

- .github/workflows/publish_main_snapshot.yml
- .github/workflows/publish_release.yml
It looks like the `Publish release` task was inadvertently doing the work of the `Publish apis for Security agent` and `Publish New Relic OpenTelemetry API Extension` tasks, instead of omitting them. Ditto for the snapshot workflow. This shouldn't have been actually causing any problems but it does mean that we couldn't effectively control those tasks by commenting them out.
> Configure publishing workflows correctly

- .github/workflows/Test-AITs.yml
Swap the version of the download-artifact action to not fail on no files.
> Swap to v3 for download-artifact in the Test AIT workflow

- instrumentation/akka-http-2.11_2.4.5/src/test/java/com/agent/instrumentation/akka/http/AkkaHttpRoutesTest.java
- instrumentation/akka-http-2.13_10.1.8/src/test/java/com/agent/instrumentation/akka/http/AkkaHttpRoutesTest.java
- instrumentation/grpc-1.22.0/src/main/java/com/nr/agent/instrumentation/grpc/GrpcConfig.java
- instrumentation/grpc-1.22.0/src/main/java/io/grpc/internal/ServerStream_Instrumentation.java
- instrumentation/grpc-1.22.0/src/test/java/ValidationHelper.java
- instrumentation/grpc-1.30.0/src/main/java/com/nr/agent/instrumentation/grpc/GrpcConfig.java
- instrumentation/grpc-1.30.0/src/main/java/io/grpc/internal/ServerStream_Instrumentation.java
- instrumentation/grpc-1.30.0/src/test/java/ValidationHelper.java
- instrumentation/grpc-1.4.0/src/main/java/com/nr/agent/instrumentation/grpc/GrpcConfig.java
- instrumentation/grpc-1.4.0/src/main/java/io/grpc/internal/ServerStream_Instrumentation.java
- instrumentation/grpc-1.4.0/src/test/java/ValidationHelper.java
- instrumentation/grpc-1.40.0/src/main/java/com/nr/agent/instrumentation/grpc/GrpcConfig.java
- instrumentation/grpc-1.40.0/src/main/java/com/nr/agent/instrumentation/grpc/GrpcUtil.java
- instrumentation/grpc-1.40.0/src/test/java/ValidationHelper.java
- newrelic-agent/src/main/java/com/newrelic/agent/attributes/AttributeNames.java
- newrelic-agent/src/main/java/com/newrelic/agent/config/AttributesConfig.java
- newrelic-agent/src/main/java/com/newrelic/agent/config/AttributesConfigImpl.java
- newrelic-agent/src/main/java/com/newrelic/agent/dispatchers/WebRequestDispatcher.java
- newrelic-agent/src/main/java/com/newrelic/agent/service/analytics/SpanEventFactory.java
- newrelic-agent/src/main/resources/newrelic.yml
- newrelic-agent/src/test/java/com/newrelic/agent/service/analytics/SpanEventFactoryTest.java
- newrelic-agent/src/test/java/com/newrelic/agent/service/analytics/TracerToSpanEventTest.java
Restores removed http attributes from Transactions and Spans under a configuration option.
By default sends both legacy and standard attributes.
Fixes #1662
> Reintroduce previously deprecated transaction/span attributes

- instrumentation/grpc-1.40.0/src/main/java/io/grpc/ClientCall_Instrumentation.java
The grpc-1.40.0 instrumentation was missing a line that set the status code/message on grpc client spans.
This PR adds that line.
> Adding status code to grpc-1.40.0 client instrumentation

- instrumentation/ning-async-http-client-1.0/src/main/java/com/nr/agent/instrumentation/asynchttpclient/NRAsyncHandler.java
- instrumentation/ning-async-http-client-1.1/src/main/java/com/nr/agent/instrumentation/asynchttpclient/NRAsyncHandler.java
- instrumentation/ning-async-http-client-1.6.1/src/main/java/com/nr/agent/instrumentation/asynchttpclient/NRAsyncHandler.java
We've tried to reproduce the issue with the ning instrumentation, but were not able to.
The evidence shows that objects of the extension class that holds the new fields were left behind.
While reviewing the code for the ning instrumentation, it was noticed that one of the new fields was not nulled like the others. While this will not make the extension objects eligible for GC, it might at least make the response objects eligible, possibly lessening the problem.
#783
> Memory Heap issue with ning instrumentation #783

- newrelic-agent/src/main/java/com/newrelic/agent/config/AttributesConfig.java
Initially those methods were supposed to go into the 8.8.1 release, but they made it into the 8.8.0 release.
> Fix since in AttributesConfig#{isLegacyHttpAttr, isStandardHttpAttr}

- newrelic-agent/src/main/java/com/newrelic/agent/service/slowtransactions/SlowTransactionService.java
Some debug code was not removed when slow transaction tracking was introduced.
Fixes #1680
> Removing printing of stack trace in SlowTransactionManager

- .github/workflows/publish_release.yml
- newrelic-opentelemetry-agent-extension/build.gradle.kts
This PR will enable publishing of the `newrelic-opentelemetry-agent-extension` artifact, including Javadoc and sources artifacts to make Sonatype happy.
> Enable Otel API extension publishing

- newrelic-agent/src/main/java/com/newrelic/agent/config/AgentConfigImpl.java
- newrelic-agent/src/main/java/com/newrelic/agent/config/SystemPropertyProvider.java
- newrelic-agent/src/test/java/com/newrelic/agent/config/AgentConfigImplTest.java
- newrelic-agent/src/test/java/com/newrelic/agent/config/BaseConfigTest.java
Resolves https://github.com/newrelic/newrelic-java-agent/issues/781
Stop looking at env vars with dotted property names. The current warning log message is inaccurate and I have provided a repro case that illustrates it.
*edit* I also simplified …
> No dotted env vars

- newrelic-agent/src/main/java/com/newrelic/agent/attributes/AttributeValidator.java
- newrelic-agent/src/main/java/com/newrelic/agent/attributes/CustomAttributeSender.java
- newrelic-agent/src/main/java/com/newrelic/agent/attributes/CustomEventAttributeValidator.java
- newrelic-agent/src/main/java/com/newrelic/agent/attributes/LogAttributeValidator.java
- newrelic-agent/src/main/java/com/newrelic/agent/config/InsightsConfig.java
- newrelic-agent/src/main/java/com/newrelic/agent/config/InsightsConfigImpl.java
- newrelic-agent/src/main/java/com/newrelic/agent/service/analytics/InsightsServiceImpl.java
- newrelic-agent/src/main/java/com/newrelic/agent/service/logging/LogSenderServiceImpl.java
- newrelic-agent/src/test/java/com/newrelic/agent/attributes/AttributeValidatorTest.java
- newrelic-agent/src/test/java/com/newrelic/agent/attributes/CustomEventAttributeValidatorTest.java
- newrelic-agent/src/test/java/com/newrelic/agent/attributes/LogAttributeValidatorTest.java
- newrelic-agent/src/test/java/com/newrelic/agent/service/analytics/CustomInsightsEventsConfigUtilsTest.java
Following the agent specs, this PR allows the size of custom event's attributes to be configurable. It uses the current size (255) by default.
#1612
> Allow custom event's attribute values to have a configurable size #1612

- newrelic-agent/src/main/java/com/newrelic/agent/InboundHeaderState.java
- newrelic-agent/src/main/java/com/newrelic/agent/Transaction.java
- newrelic-agent/src/test/java/com/newrelic/agent/TransactionTest.java
> Add Null Checks for Synthetics-Info Header Attributes

- gradle.properties
- newrelic-agent/src/main/resources/META-INF/excludes
CSEC version bump to 1.1.0
[NR-214326]: Fix class circularity error by introducing excludes
> CSEC Java Agent Public Release 1.1.0

- instrumentation/httpclient-5.0/src/main/java/com/nr/agent/instrumentation/httpclient50/InstrumentationUtils.java
- instrumentation/httpclient-5.0/src/main/java/com/nr/agent/instrumentation/httpclient50/WrappedFutureCallback.java
- instrumentation/httpclient-5.0/src/test/java/com/nr/agent/instrumentation/httpclient/HttpClient5Test.java
instanceof checks when handling the response
and another null check
> 1715 http client5 fixes

- instrumentation/httpclient-5.0/src/main/java/org/apache/hc/client5/http/classic/HttpClient_Instrumentation.java
Resolves #1717 
Retrieve the URI instance from the `HttpPost` instance unless it's null, then pull the required info from the `HttpRequest` instance.
> Check HttpHost instance for null prior to dereferencing it

- newrelic-agent/src/main/java/com/newrelic/agent/HarvestServiceImpl.java
- newrelic-agent/src/main/java/com/newrelic/agent/config/AgentConfigFactory.java
- newrelic-agent/src/test/java/com/newrelic/agent/config/AgentConfigFactoryTest.java
To solve the problems on #1572 this PR adds a server property to the base config. The property `application_logging.forwarding.enabled` will be set to false when the harvest limit for log events is 0.
It was added as a property rather than calculated in `ApplicationLoggingForwardingConfig` because the instrumentation modules do not have access to the config objects and have to query for the properties using the Config interface.
Fixes #1572
> Decrease log instrumentation overhead when log forwarding is disabled account wide #1572

- instrumentation-test/src/main/java/com/newrelic/agent/introspec/internal/IntrospectorLogSenderService.java
- newrelic-agent/src/main/java/com/newrelic/agent/Transaction.java
- newrelic-agent/src/main/java/com/newrelic/agent/service/logging/LogSenderService.java
- newrelic-agent/src/main/java/com/newrelic/agent/service/logging/LogSenderServiceImpl.java
- newrelic-agent/src/test/java/com/newrelic/agent/service/logging/LogSenderServiceImplTest.java
When a transaction log reservoir is created, its max size is retrieved from `application_logging.forwarding.max_samples_stored`.
This configuration value is the number of log lines that should be sent per minute. But log events are in a fast harvest cycle and are harvested every 5 seconds.
So this PR changes the way that these reservoirs are created to use the `maxSamplesStored` in `LogSenderServiceImpl` which already has the correct value.
> Making sure that Transaction Log reservoir is no bigger than it needs

- instrumentation/newrelic-scala-zio-api/src/main/scala/com/newrelic/zio/api/Util.scala
- instrumentation/zio/src/main/java/zio/internal/Utils.java
- newrelic-scala-zio-api/src/test/scala/com/newrelic/zio/api/TraceOpsDSLTest.scala
**WIP: Do not merge**
Explicitly kill the tokens when the tracer around a ZIO transaction finishes. Do not increment a refcount. 
Adds a unit test with back-to-back transactions.
> Zio 1 update

- newrelic-agent/src/main/java/com/newrelic/agent/service/analytics/DistributedSamplingPriorityQueue.java
- newrelic-agent/src/main/java/com/newrelic/agent/service/logging/LogSenderServiceImpl.java
- newrelic-agent/src/main/java/com/newrelic/agent/util/NoOpQueue.java
- newrelic-agent/src/test/java/com/newrelic/agent/service/logging/LogSenderServiceImplTest.java
When the agent is configured to allow log forwarding but the max_samples_stored is configured to 0, a BlockingQueue was instantiated with size 0, which is illegal.
This PR changes the implementation being instantiated to a NoopQueue instead.
> Allowing TransactionLog to be instantiated with max_samples_stored = 0

- newrelic-agent/src/main/java/com/newrelic/agent/attributes/AgentAttributeSender.java
- newrelic-agent/src/test/java/com/newrelic/api/agent/NewRelicApiImplementationTest.java
Resolves #1749 
Add an NPE check prior to calling `.remove()` on the return value from `getAttributeMap()`.
This corrects the issue where `NewRelicApiImplementation.setUserId()` was throwing an exception when called outside of a transaction.
> NPE guard in AgentAttributeSender.removeAttribute()

- newrelic-agent/src/main/java/com/newrelic/agent/InitProblemClasses.java
Resolves #1760 
Load `MessageFormat` class early to prevent `ClassCircularityError` exceptions.
> Add MessageFormat class to InitProblemClasses

- instrumentation/kafka-clients-metrics-3.0.0/build.gradle
Related verifier failures: https://github.com/newrelic/newrelic-java-agent/issues/1766
> Cap kafka-clients-metrics-3.0.0 supported version

- .github/workflows/GHA-Scala-Functional-Tests.yaml
- .github/workflows/GHA-Unit-Tests.yaml
- .github/workflows/publish_main_snapshot.yml
- .github/workflows/publish_release.yml
- newrelic-scala-zio-api/src/test/scala/com/newrelic/zio/api/TraceOpsDSLTest.scala
- newrelic-scala3-api/build.gradle.kts
- newrelic-scala3-api/src/main/scala/com/newrelic/scala/api/TraceOps.scala
- newrelic-scala3-api/src/test/scala/com/newrelic/scala/api/TraceOpsDSLTest.scala
- settings.gradle
Resolves #1667 
- Produces a new artifact: `newrelic-scala3-api_3-x.y.z.jar` that is the vanilla scala API that supports scala 3
- Updates GHA workflows for publishing the artifact to staging/production maven and running the unit tests
Note that the Java 8/11/17/21 test failures will be resolved once this PR is merged because the necessary GHA changes for the new module don't exist in the main branch's GHAs.
> Produce newrelic-scala3-api_3 artifact

- instrumentation/zio-2/build.gradle
- instrumentation/zio/build.gradle
The zio instrumentation modules have the wrong implementation titles. This PR simply fixes that so the ZIO 1 and ZIO 2 modules are compiled correctly
> Fix implementation title for the zio modules

- newrelic-agent/src/main/java/com/newrelic/agent/instrumentation/context/InstrumentationContextClassMatcherHelper.java
- newrelic-agent/src/test/java/com/newrelic/agent/instrumentation/context/InstrumentationContextClassMatcherHelperTest.java
Resolves #1759 
Add `$$Lambda/` to list of generated lambda class name patterns. Thrown `MissingResourceException` instances are ignored if the target class matches one of these defined patterns.
> Update lambda regex to ignore missing resource exceptions

- agent-bridge-datastore/src/main/java/com/newrelic/agent/bridge/datastore/JdbcHelper.java
This is a stop gap change to reduce the size of the `ExpiringValueMap` used by a couple of the JDBC caches until we can implement #1791.
> Reduce hardcoded interval for JDBC caches

- newrelic-agent/src/main/java/com/newrelic/agent/config/JmxConfig.java
- newrelic-agent/src/main/java/com/newrelic/agent/config/JmxConfigImpl.java
- newrelic-agent/src/main/java/com/newrelic/agent/jmx/JmxApiImpl.java
- newrelic-agent/src/main/java/com/newrelic/agent/jmx/JmxService.java
- newrelic-agent/src/main/java/com/newrelic/agent/jmx/create/JmxGet.java
- newrelic-agent/src/main/java/com/newrelic/agent/jmx/metrics/BaseJmxValue.java
- newrelic-agent/src/main/java/com/newrelic/agent/jmx/values/LegacySolr7JmxValues.java
- newrelic-agent/src/main/java/com/newrelic/agent/jmx/values/NonIteratedSolr7JmxValues.java
- newrelic-agent/src/main/java/com/newrelic/agent/jmx/values/Solr7JmxValues.java
- newrelic-agent/src/test/java/com/newrelic/agent/jmx/JmxApiImplTest.java
- newrelic-agent/src/test/java/com/newrelic/agent/jmx/create/JmxGetTest.java
- newrelic-agent/src/test/java/com/newrelic/agent/jmx/values/JmxFrameworkValueImplTest.java
Allow the agent to capture clustered Solr cores via our JMX API . 
Single instances of Solr will contain function the same. 
In clustered Solr cores, their JMX MBeans will look like `solr:dom1=core,dom2=dummy_collection,dom3=shard2,dom4=replica_n2,category=CACHE,scope=searcher,name=documentCache` which the agent did not capture. 
Now the agent will export Solr values with nested DOM (i.e. clustered cores) in the formats:
- JMX/solr/{collection name}.{shard}.{core name}/{name_value}/%/{attribute}/
- JMX/solr/{collection name}.{shard}.{core name}/updateHandler/%/{attribute}
Fpr example: 
`JMX/solr/dummy_collection.shard2.replica_n2/documentCache/%/`
The Solr UI will recognize the cores in the format `{collection name}.{shard}.{core name}`
This is done by adding new iteration syntax for …
> Enhance Solr 7+ JMX metrics by including clustered Solr collections which include the collection name, shard name, and (replica) core

- agent-model/src/main/java/com/newrelic/agent/model/ErrorEvent.java
- agent-model/src/test/java/com/newrelic/agent/model/ErrorEventTest.java
- newrelic-agent/src/main/java/com/newrelic/agent/errors/ErrorServiceImpl.java
- newrelic-agent/src/test/java/com/newrelic/agent/errors/ErrorServiceTest.java
Errors inbox team validated that both the `ErrorEvent` and `TracedError` payloads contain the transaction GUID in the proper spots when DT is disabled.
> Add transaction GUID to ErrorEvent instances

- newrelic-agent/src/main/java/com/newrelic/agent/config/SlowTransactionsConfig.java
- newrelic-agent/src/main/java/com/newrelic/agent/config/SlowTransactionsConfigImpl.java
- newrelic-agent/src/main/java/com/newrelic/agent/service/slowtransactions/SlowTransactionService.java
- newrelic-agent/src/main/resources/newrelic.yml
- newrelic-agent/src/test/java/com/newrelic/agent/service/slowtransactions/SlowTransactionServiceTest.java
Currently, slow transactions are only checked for during a harvest cycle. This change adds the ability to check every transaction against the defined threshold upon transaction completion. The setting to enable this is `evaluate_completed_transactions` (default is false).
```yaml
slow_transactions:
enabled: true
threshold: 600000
evaluate_completed_transactions: false
```
> Slow txn update

- instrumentation/opentelemetry-sdk-extension-autoconfigure-1.28.0/build.gradle
The original range for which the instrumentation applies was missing a few versions.
> Updating range for otel-autoconfigure verify instrumentation

- .github/workflows/Test-AITs.yml
Pekko was excluded because the AITs were merged too early. Adding back in.
> Add pekko back to Test-AITs.yml

- CHANGELOG.md
- gradle.properties
> 8.10.0 release notes

- instrumentation/netty-reactor-0.9.0/src/main/java/reactor/core/publisher/FluxMapFuseable_Instrumentation.java
This instrumentation should catch call chaining in regards to external calls being made in those chains.
> 1780 spring reactor chaining

- instrumentation/opentelemetry-sdk-extension-autoconfigure-1.28.0/src/main/java/io/opentelemetry/sdk/autoconfigure/AutoConfiguredOpenTelemetrySdk.java
This allows the agent's Opentelemetry SDK autoconfiguration feature to be disabled with this setting:
opentelemetry.sdk.autoconfigure.enabled=false
For instance, start a process with this added: `-Dnewrelic.config.opentelemetry.sdk.autoconfigure.enabled=false`
This feature can currently be disabled by disabling the instrumentation, but this is a nicer looking switch.
> Add a switch to allow the OTel SDK integration to be completely disabled

- instrumentation/jax-rs-3.0/build.gradle
Preventing verify instrumentation from failing on unsupported jax-rs version.
> Capping jax-rs-3.0 instrumentation

- instrumentation/httpurlconnection/src/main/java/com/nr/agent/instrumentation/httpurlconnection/InboundWrapper.java
- instrumentation/httpurlconnection/src/test/java/com/nr/agent/instrumentation/httpurlconnection/InboundTest.java
Reverts the `httpurlconnection` changes that went into the 8.10.0 release due to overhead issues described in https://github.com/newrelic/newrelic-java-agent/issues/1838
> Revert httpurlconnection InboundWrapper changes

- functional_test/build.gradle
- functional_test/src/test/java/test/newrelic/test/agent/TraceAnnotationTest.java
- newrelic-agent/src/main/java/com/newrelic/agent/config/ClassTransformerConfigImpl.java
NR-134815
There is a java OpenTelemetry library that contains a `WithSpan` annotation designed to work the same as our `Trace` annotation.  By adding support for this annotation we increase our adoption of Otel.  It allows customers to use this open source annotation instead of our proprietary annotation (in many cases).
I think we can defer suppressing this instrumentation (`otel.instrumentation.opentelemetry-instrumentation-annotations.exclude-methods`) and adding support for `otel.instrumentation.methods.include` until later.
Note that OTel properties can be set through environment or system properties, like our agent, and eventually through a config file.  We can use our existing otel instrumentation model to get access to the normalized version of the instrumentation settings to …
> NR-134815 Treat OTel WithSpan annotation as Trace

- newrelic-agent/src/main/java/com/newrelic/agent/service/analytics/SpanEventFactory.java
- newrelic-agent/src/test/java/com/newrelic/agent/service/analytics/SpanEventFactoryTest.java
- newrelic-agent/src/test/java/com/newrelic/agent/tracers/DefaultSqlTracerClmTest.java
- newrelic-agent/src/test/java/com/newrelic/agent/tracers/DefaultSqlTracerTest.java
Increases db.statement max size to reduce truncating long statements
[Issue #1486](https://github.com/newrelic/newrelic-java-agent/issues/1486)
> Increase Size of db.statement Attribute in Span Events

- instrumentation/apache-log4j-1/src/main/java/com/nr/agent/instrumentation/log4j1/Log4j1ExceptionUtil.java
- instrumentation/apache-log4j-1/src/test/java/com/nr/agent/instrumentation/log4j1/Log4j1ExceptionUtilTest.java
- instrumentation/apache-log4j-2.11/src/main/java/com/nr/agent/instrumentation/log4j2/ExceptionUtil.java
- instrumentation/apache-log4j-2.11/src/test/java/com/nr/agent/instrumentation/log4j2/ExceptionUtilTest.java
- instrumentation/apache-log4j-2.6/src/main/java/com/nr/agent/instrumentation/log4j2/ExceptionUtil.java
- instrumentation/apache-log4j-2.6/src/test/java/com/nr/agent/instrumentation/log4j2/ExceptionUtilTest.java
- instrumentation/java.logging-jdk8/src/main/java/com/nr/instrumentation/jul/ExceptionUtil.java
- instrumentation/java.logging-jdk8/src/test/java/com/nr/instrumentation/jul/ExceptionUtilTest.java
- instrumentation/logback-classic-1.2/src/main/java/com/nr/agent/instrumentation/logbackclassic12/ExceptionUtil.java
- instrumentation/logback-classic-1.2/src/test/java/com/nr/agent/instrumentation/logbackclassic12/ExceptionUtilTest.java
Resolves #1189 
This change will add the `caused by` portion of a stack trace, if available, when decorating logs for forwarding. Note that the maximum stack trace size of 300 is still enforced so stack traces can still be truncated. Added unit tests to verify the new functionality. 
This logic is same used when generating stack traces for TracedErrors/ErrorEvents.
Changed instrumentation:
- log4j1
- log4j2
- logback
- JUL
> Add "caused by"  section(s) when forwarding logs

- instrumentation/glassfish-6/build.gradle
The verifier has failed for the last four glassfish releases, looks like it's time to officially cap this instrumentation and create a new module.
Related: https://github.com/newrelic/newrelic-java-agent/issues/1806
> Cap glassfish-6 instrumentation ranges

- newrelic-agent/src/main/java/com/newrelic/agent/Agent.java
Customers are seeing this message:
New Relic Security is completely disabled by one of the user provided config `security.enabled`, `security.agent.enabled` or `high_security`. Not loading security capabilities.
But they believe they have configured the agent to enable IAST.  This PR logs `security.enabled`, `security.agent.enabled` and `high_security` at `FINE` so that the config values can be scrutinized.
> Log IAST related config variables

- functional_test/src/test/java/com/newrelic/agent/instrumentation/APISupportabilityTest.java
`APISupportabilityTest` is unnecessarily complicated.  It uses `InstrumentTestUtils.createTransformerAndRetransformClass`, passing in a string method descriptor, when it can use `InstrumentTestUtils.retransformClass` instead.  Given that many tests are added by copying existing tests, we should clean up this unnecessary pattern.
> Simplify test

- newrelic-agent/src/main/java/com/newrelic/agent/Agent.java
- newrelic-agent/src/main/java/com/newrelic/agent/config/SecurityAgentConfig.java
- newrelic-agent/src/test/java/com/newrelic/agent/config/SecurityAgentConfigTest.java
When IAST is disabled, this logs the following at `FINE` level:
* Environment keys and their values when the key contains `NEW_RELIC` and `SECURITY`
* System property keys and their values when the key contains `newrelic.config.` and `security`
I pulled all of this logging out of the main `Agent` class and into `SecurityAgentConfig`.
> When IAST is disabled log security related env and system properties

- instrumentation/jax-rs-3.0/build.gradle
Fixes the following verifier failure. https://github.com/newrelic/newrelic-java-agent/actions/runs/8981808490/job/24668263806
```
* What went wrong:
Execution failed for task ':instrumentation:jax-rs-3.0:verifyFail_jakarta.ws.rs_jakarta.ws.rs-api_4.0.0'.
> A failure occurred while executing com.newrelic.agent.instrumentation.verify.VerifyWorkAction
> Verification FAILED. Instrumentation module jax-rs-3.0-1.0.jar SHOULD NOT HAVE applied to jakarta.ws.rs:jakarta.ws.rs-api:4.0.0 but it did. You may need to adjust the range "jakarta.ws.rs:jakarta.ws.rs-api:[0,)".
Verifier output:
Creating user classloader with custom classpath:
/home/runner/.gradle/caches/modules-2/files-2.1/jakarta.ws.rs/jakarta.ws.rs-api/4.0.0/c27a67f84ca491efcb3fa68f4df926e8a110069e/jakarta.ws.rs-api-4.0.0.jar
```
> Fix verifier range for jax-rs-3.0

- agent-bridge-datastore/src/main/java/com/newrelic/agent/bridge/datastore/R2dbcOperation.java
- instrumentation/r2dbc-mssql/src/main/java/io/r2dbc/mssql/client/R2dbcUtils.java
This PR incorporates the changes from the custom jar we built to prevent unnecessary regex checks when parsing SQL. A customer had reported latency with r2dbc drivers, and removing the extra regex checks resolved their issue. 
Instead of performing a regex check for all operations, we now do a simple String `contains` on the operation name, before continuing with the match.
> Non-regex SQL checks

- newrelic-agent/src/main/java/com/newrelic/agent/logging/ClearExpiredLogsRunnable.java
- newrelic-agent/src/main/java/com/newrelic/agent/logging/FileAppenderFactory.java
- newrelic-agent/src/test/java/com/newrelic/agent/logging/ClearExpiredLogsRunnableTest.java
Resolves #1884 
Refactor of the `ClearExpiredLogsRunnable` constructor to remove the Path param. Uses an alternative method for grabbing the log file name and path.
Update tests.
> Minor refactoring of daily logfile rolling job to support all platforms.

- gradle.properties
Bump csec version to [1.3.0](https://github.com/newrelic/csec-java-agent/releases/tag/1.3.0)
> Bump csec version to 1.3.0

- .github/workflows/Test-AITs.yml
Both pekko AIT tests are intermittently stalling after the update to GHA shas. Need to look into why.
> Exclude pekko AITs

- instrumentation/r2dbc-postgresql-0.9.2/src/main/java/com/nr/instrumentation/r2dbc/postgresql092/EndpointData.java
- instrumentation/r2dbc-postgresql-0.9.2/src/main/java/io/r2dbc/postgresql/R2dbcUtils.java
- instrumentation/r2dbc-postgresql-0.9.2/src/main/java/io/r2dbc/postgresql/client/ReactorNettyClient_Instrumentation.java
Changes to the Postgres R2DBC 9.2+ instrumentation that improve memory usage. In particular, runs of this branch of the agent did not cause a growth in heap usage compared to the old agent over time.
https://github.com/newrelic/newrelic-java-agent/issues/1702
> R2dbc postgresql 0.9.2 memleak fix

- newrelic-agent/src/main/java/com/newrelic/agent/config/AgentConfigImpl.java
- newrelic-agent/src/main/java/com/newrelic/agent/config/ClassTransformerConfigImpl.java
- newrelic-agent/src/main/resources/META-INF/excludes
- newrelic-agent/src/test/java/com/newrelic/agent/config/ClassTransformerConfigImplTest.java
Resolves #1917 
Refactor `ClassTransformerConfigImpl` to add security related class exclusions (if applicable) while parsing user defined class exclusions.
> Add security related class excludes during normal class transformer creation

- instrumentation/glassfish-6/build.gradle
Glassfish-6 instrumentation module applies to the newly released 8.0.0 milestones. Since this version of Glassfish will include a newer version of Jakarta, it is likely that we will indeed need a new instrumentation module. So for now, the milestones that allow the instrumentation module to be applied are going to be excluded.
#1806
> glassfish-6: excluding some milestones

- instrumentation/jsp-3/README.md
- instrumentation/jsp-3/build.gradle
- instrumentation/jsp-3/src/main/java/com/nr/agent/instrumentation/jsp3/JspContextWrapper.java
- instrumentation/jsp-3/src/main/java/com/nr/agent/instrumentation/jsp3/JspUtils.java
- instrumentation/jsp-3/src/main/java/com/nr/agent/instrumentation/jsp3/JspWriterWrapper.java
- instrumentation/jsp-3/src/main/java/com/nr/agent/instrumentation/jsp3/PageContextWrapper.java
- instrumentation/jsp-3/src/main/java/jakarta/servlet/jsp/HttpJspPage.java
- instrumentation/jsp-3/src/main/java/jakarta/servlet/jsp/tagext/SimpleTagSupport_Instrumentation.java
- instrumentation/jsp-3/src/main/java/jakarta/servlet/jsp/tagext/TagSupport_Instrumentation.java
- newrelic-agent/src/main/resources/newrelic.yml
Resolves #1695 
Prior to the additions to this instrumentation module, the only way to inject the RUM script into JSPs was during the 
compilation phase of the Jasper compiler, which injects the script into the HTML `<head>` element, if present in the page
source.
Some applications use custom JSP tag libraries to create the head tag (and other HTML page elements). In this scenario, the RUM script will not be injected because of the way the Jasper compiler instrumentation detects the head tag. This
instrumentation module weaves the `SimpleTagSupport` and `TagSupport` classes to detect the creation of head elements via the tag execution and inject the RUM script at that time.
See the included README for more information.
> JSP v3 Tag library instrumentation for RUM script injection

- newrelic-agent/src/main/java/com/newrelic/agent/utilization/AwsFargateMetadataFetcher.java
- newrelic-agent/src/main/java/com/newrelic/agent/utilization/DockerData.java
- newrelic-agent/src/test/java/com/newrelic/agent/utilization/DockerDataTest.java
Resolves #1904 
See: https://source.datanerd.us/agents/agent-specs/pull/676
> Fetch the container ID for ECS Fargate instances

- gradle.properties
Bump CSEC Version to [1.4.0](https://github.com/newrelic/csec-java-agent/releases/tag/1.4.0)
> CSEC Version bump to 1.4.0

- instrumentation/vertx-web-3.8.0/src/main/java/io/vertx/core/http/impl/HttpServerConnection_Instrumentation.java
- instrumentation/vertx-web-3.8.3/src/main/java/io/vertx/core/http/impl/HttpServerConnection_Instrumentation.java
Fixes a gap in the `vertx-web` instrumentation where transactions weren't getting started when handling HTTP/2 requests.
Weaves the `io.vertx.core.http.impl.HttpServerConnection` interface instead of just the `Http1xServerConnection` implementation. This results in `Http1xServerConnection` being weaved as well as the previously un-instrumented `Http2ServerConnection` implementation.
> Refactor vertx-web to weave Http2ServerConnection

- agent-bridge/src/main/java/com/newrelic/agent/bridge/aimonitoring/AiMonitoringUtils.java
- instrumentation/aws-bedrock-runtime-2.20/src/test/java/software/amazon/awssdk/services/bedrockruntime/AIM_Disabled_ServerSide_BedrockRuntimeAsyncClient_InstrumentationTest.java
- instrumentation/aws-bedrock-runtime-2.20/src/test/java/software/amazon/awssdk/services/bedrockruntime/AIM_Disabled_ServerSide_BedrockRuntimeClient_InstrumentationTest.java
- instrumentation/aws-bedrock-runtime-2.20/src/test/resources/llm_disabled_server_side.yml
- newrelic-agent/src/main/java/com/newrelic/agent/aimonitoring/AiMonitoringImpl.java
- newrelic-agent/src/main/java/com/newrelic/agent/config/AgentConfigFactory.java
Resolves https://github.com/newrelic/newrelic-java-agent/issues/1963
> Disable AIM when collect_ai=false is sent in connect response

- instrumentation/netty-reactor-0.9.0/src/main/java/reactor/core/publisher/FluxMapFuseable_Instrumentation.java
- instrumentation/netty-reactor-0.9.0/src/main/java/reactor/core/publisher/LambdaMonoSubscriber_Instrumentation.java
- instrumentation/netty-reactor-0.9.0/src/main/java/reactor/core/publisher/LambdaSubscriber_Instrumentation.java
- instrumentation/netty-reactor-0.9.0/src/main/java/reactor/core/publisher/MonoSubscribeOn_Instrumentation.java
Specifically for when a publisher has generated a token, but is cancelled before emitting anything.
Fixes https://github.com/newrelic/newrelic-java-agent/issues/1970
> Plugged a few gaps in token handling for error path cases

- instrumentation/hikaricp-2.4.0/README.md
- instrumentation/hikaricp-2.4.0/src/main/java/com/zaxxer/hikari/pool/PooledDataSourceSampler.java
Resolves #1965 
Adds additional metrics pulled from the `HikariPool` and `HikariConfig` classes. The full list:
- `Database Connection/HikariCP/Busy Count[connections]`: Retrieved from HikariPool.getActiveConnections()
- `Database Connection/HikariCP/Idle Count[connections]`: Retrieved from HikariPool.getIdleConnections()
- `Database Connection/HikariCP/Total Count[connections]`: Retrieved from HikariPool.getTotalConnections()
- `Database Connection/HikariCP/Threads Awaiting Count[connections]`: Retrieved from HikariPool.getThreadsAwaitingConnection()
- `Database Connection/HikariCP/Max Pool Size[connections]`: Retrieved from HikariConfig.getMaximumPoolSize()
- `Database Connection/HikariCP/Minimum Idle Size[connections]`: Retrieved from HikariConfig.getMinimumIdle()
- `Database …
> Additional metrics for HikariCP module

- instrumentation/jdbc-sqlserver/build.gradle
Excludes `mssql-jdbc-12.7.0 Pre-Release` from being verified.
Updates the range of `mssql-jdbc` versions to be verified.
Resolves [Issue 1844](https://github.com/newrelic/newrelic-java-agent/issues/1844)
> Exclude mssql-jdbc-12.7.0 Pre-Release From VerifyInstrumentation

- instrumentation/mongodb-3.7/build.gradle
Verifies that the mongodb-3.7 instrumentation module applies to the new artifact name being released by Mongo.
#2034
> MongoDB - verify instrumentation using new artifact name

- dev-tools/live-templates
Small update to live templates to fix the scope where they apply to.
This would prevent some templates from appearing where they would "break" the code.
For instance when nr is typed in the following location:
```
String someString = nr
```
any template that creates a variable, or add a return statement will not appear.
> Live templates - fixing identation and scope

- instrumentation/netty-4.1.16/src/main/java/com/agent/instrumentation/netty4116/Http2RequestHeaderWrapper.java
- instrumentation/netty-4.1.16/src/main/java/com/agent/instrumentation/netty4116/Http2ResponseHeaderWrapper.java
Fixes https://github.com/newrelic/newrelic-java-agent/issues/2024
It looks like there are some unexpected implementations of `Http2Headers` (e.g. with gRPC) that throw `UnsupportedOperationException`s for many of the method implementations. This PR adds logic to handle any such exceptions.
> Protect against Http2Headers methods throwing exceptions

- newrelic-agent/src/main/java/com/newrelic/agent/tracers/DefaultTracer.java
Fixes an issue where ERROR logs were generated by the Kinesis instrumentation due to a NullPointerException.
```
2024-09-16T13:37:08,315-0400 [10984 66] com.newrelic ERROR: An error occurred recording external metrics for class putRecord : java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "value" is null
```
> Fix an issue where the Kinesis instrumentation is generating ERROR logs due to a NullPointerException

- instrumentation/mongodb-reactive-streams-4.8/build.gradle
Cap mongo-reactive-4.8 module to exclude v5.20+
> Cap mongo-reactive-4.8 module

- newrelic-agent/src/main/java/com/newrelic/agent/utilization/DockerData.java
- newrelic-agent/src/main/java/com/newrelic/agent/utilization/UtilizationData.java
- newrelic-agent/src/main/java/com/newrelic/agent/utilization/UtilizationService.java
- newrelic-agent/src/test/java/com/newrelic/agent/utilization/DockerDataTest.java
- newrelic-agent/src/test/java/com/newrelic/agent/utilization/UtilizationCrossAgentTests.java
- newrelic-agent/src/test/java/com/newrelic/agent/utilization/UtilizationDataTest.java
- newrelic-agent/src/test/java/com/newrelic/agent/utilization/UtilizationServiceTest.java
Resolves #2047 
Updates to the way ECS Fargate docker ids are detected:
- The ECS fargate endpoint must be checked, even if a docker id was found using cgroups
- If found, it must reported as a new vendor in the utilization payload (details in the spec) 
- Both the cgroup docker id and ECS fargate docker id will be reported if both are present
The metadata environment variables which specify the endpoints are unchanged, as is the order in which to check them (ie: check the v4 endpoint prior to checking the un-versioned endpoint). The response JSON is also unchanged.
This will be merged after full stack testing on AWS is performed.
> ECS Fargate Docker id updates

- instrumentation/httpurlconnection/src/main/java/com/nr/agent/instrumentation/httpurlconnection/MetricState.java
Within the HttpUrlConnection instrumentation module inside the Metric State class, TracedMethod member variables are replaced with weak references. This can help reduce memory usage because the TracedMethod instances can be garbage collected sooner.
https://github.com/newrelic/newrelic-java-agent/issues/2048
> httpurlconnection metric state use weakref tracers

- newrelic-agent/src/main/java/com/newrelic/agent/trace/TransactionGuidFactory.java
- newrelic-agent/src/main/java/com/newrelic/agent/tracers/DefaultTracer.java
Closes #2057 from @yuzawa-san 
The GUID for a tracer is only necessary if it's going to be reported up to NR. This change defers the creation of the GUID until the `getGuid()` call is made.
Another minor optimization was moving the `hexchars` const to a class level member.
> Lazy init of GUIDs on DefaultTracers

- instrumentation/httpclient-jdk11/src/main/java/com.nr.agent.instrumentation.httpclient/Java11HttpClientUtil.java
Resolves #2085 
Externals reported when using the Java Http Client now properly report the HTTP status code.
Note that the response text will still be null.
> Java HttpClient - Addition of status code to reported externals

- newrelic-agent/src/main/java/com/newrelic/agent/MetricNames.java
- newrelic-agent/src/main/java/com/newrelic/agent/environment/Environment.java
Resolves #2092 
When the agent is installed with the Azure site extension, the following environment variable will be present: NEW_RELIC_METADATA_AZURE_APP_SERVICE_NAME
If this environment variable is present, the following must be added to the environment section of the connect payload
```
[
"AzureSiteExtension",
"AzureSiteExtension"
]
```
Additionally a supportability metric of `Supportability/Java/InstallType/AzureSiteExtension` must be reported.
> Report if agent was installed via Azure site extension

- instrumentation/aws-java-sdk-dynamodb-1.11.106/src/main/java/com/amazonaws/services/dynamodbv2/AmazonDynamoDBClient_Instrumentation.java
- instrumentation/aws-java-sdk-dynamodb-1.11.106/src/main/java/com/nr/instrumentation/dynamodb_1_11_106/DynamoDBMetricUtil.java
- instrumentation/aws-java-sdk-dynamodb-1.11.106/src/test/java/com/agent/instrumentation/awsjavasdkdynamodb1_11_106/DynamoApiTest.java
- instrumentation/aws-java-sdk-dynamodb-1.11.106/src/test/java/com/nr/instrumentation/dynamodb_1_11_106/DynamoDBMetricUtilTest.java
- instrumentation/aws-java-sdk-dynamodb-2.15.34/build.gradle
- instrumentation/aws-java-sdk-dynamodb-2.15.34/src/main/java/com/nr/instrumentation/dynamodb_v2/DynamoDBMetricUtil.java
- instrumentation/aws-java-sdk-dynamodb-2.15.34/src/main/java/software/amazon/awssdk/services/dynamodb/DefaultDynamoDbAsyncClient_Instrumentation.java
- instrumentation/aws-java-sdk-dynamodb-2.15.34/src/main/java/software/amazon/awssdk/services/dynamodb/DefaultDynamoDbClient_Instrumentation.java
- instrumentation/aws-java-sdk-dynamodb-2.15.34/src/test/java/com/agent/instrumentation/awsjavasdkdynamodb_v2/DefaultDynamoDbClient_InstrumentationTest.java
- instrumentation/aws-java-sdk-dynamodb-2.15.34/src/test/java/com/agent/instrumentation/awsjavasdkdynamodb_v2/LocalTestDynamoDb.java
- instrumentation/aws-java-sdk-dynamodb-2.15.34/src/test/java/com/nr/instrumentation/dynamodb_v2/DynamoDBMetricUtilTest.java
- newrelic-agent/src/main/java/com/newrelic/agent/service/analytics/SpanEventFactory.java
- newrelic-agent/src/test/java/com/newrelic/agent/service/analytics/SpanEventFactoryTest.java
- newrelic-api/src/main/java/com/newrelic/api/agent/DatastoreParameters.java
Changes to the DynamoDB instrumentation to populate the cloud.resource_id attribute.
This attribute will allow an instrumented DynamoDB table to be linked to an APM that calls it.
Fixes #1802
> DynamoDB: populate cloud.resource_id

- instrumentation/aws-java-sdk-dynamodb-2.15.34/src/main/java/com/nr/instrumentation/dynamodb_v2/DynamoDBMetricUtil.java
- instrumentation/aws-java-sdk-dynamodb-2.15.34/src/test/java/com/nr/instrumentation/dynamodb_v2/DynamoDBMetricUtilTest.java
While retrieving the region for the DynamoDB table, to check whether the endpoint was custom, the field `SdkClientOption.ENDPOINT_OVERRIDDEN` was used. But this field is not available in older versions of the instrumentation.
So to increase the compatibility of the instrumentation, this verification is being dropped and the region the sdk client is configured is used instead.
> dynamodb: removing reference to field only available in newer versions

- newrelic-agent/src/main/java/com/newrelic/agent/service/analytics/SpanEventFactory.java
SpanEventFactory#setServerPort received an int, but the methods that provided this int returned an Integer.
A case was found where the port received was null and caused an NPE.
Adding a null check to prevent it.
> SpanEventFactory - adding null check on server port

- instrumentation/httpurlconnection/src/main/java/com/nr/agent/instrumentation/httpurlconnection/MetricState.java
Continuation of the previous [PR](https://github.com/newrelic/newrelic-java-agent/pull/2082) to replace TracedMethod instances with weak references in HttpUrlConnection. This just adds an additional null guard.
https://github.com/newrelic/newrelic-java-agent/issues/2048
> Null guard for dtTracer in httpurlconnection MetricState

- newrelic-api/src/main/java/com/newrelic/api/agent/NewRelic.java
Test run PR of #2128 from @matzz
`com.newrelic.api.agent.NewRelic::recordResponseTimeMetric` is calling the wrong method on the `metricAggregator` instance:
```
public static void recordResponseTimeMetric(String name, long millis) {
getAgent().getMetricAggregator().recordMetric(name, millis);
}
```
> Use recordResponseTimeMetric instead recordMetric in NewRelic agent API layer

- newrelic-api/src/main/java/com/newrelic/api/agent/NewRelic.java
It seams that 
```
public static void recordResponseTimeMetric(String name, long millis) {
getAgent().getMetricAggregator().recordMetric(name, millis);
}
```
recordResponseTimeMetric calls recordMetric in MetricAggregator instead of recordResponseTimeMetric.
> Use recordResponseTimeMetric instead recordMetric in NewRelic agent.

- newrelic-agent/build.gradle
- newrelic-agent/src/test/java/com/newrelic/agent/language/SourceLibraryDetectorTest.java
This will update the version of the JFR daemon used by the Java agent with the changes listed here:
https://github.com/newrelic/newrelic-jfr-core/releases/tag/v1.13.0
> Update to JFR daemon 1.13.0

- instrumentation/jetty-12/src/main/java/com/nr/agent/instrumentation/jetty12/JettyRequest.java
Resolves an issue in the Jetty 12 instrumentation module where the JettyRequest class does not have the method implementation for `String getHeader(String name)`.
https://github.com/newrelic/newrelic-java-agent/issues/2139
> Jetty12 missing headers impl

- newrelic-agent/src/main/java/com/newrelic/agent/instrumentation/InstrumentationImpl.java
Resolves https://github.com/newrelic/newrelic-java-agent/issues/2141
There's a point early in the agent's lifecycle where the `ProfilerService` service is not yet initialized that can result in the agent logging the following exception stack:
```
2024-11-12T16:05:05,468-0800 [22649 36] com.newrelic.agent.instrumentation.ClassTransformerServiceImpl FINEST: exception in noticeTracer: null. This may affect thread profile v2.
java.lang.NullPointerException: Cannot invoke "com.newrelic.agent.profile.ProfilerService.getTransactionProfileService()" because the return value of "com.newrelic.agent.service.ServiceFactory.getProfilerService()" is null
at com.newrelic.agent.instrumentation.InstrumentationImpl.noticeTracer(InstrumentationImpl.java:381) [newrelic-agent-8.15.0.jar:8.15.0]
at …
```
> Don't log full exception stack for expected NPE in noticeTracer

- agent-bridge/src/main/java/com/newrelic/agent/bridge/CloudApi.java
- agent-bridge/src/main/java/com/newrelic/agent/bridge/DefaultCollectionFactory.java
- agent-bridge/src/main/java/com/newrelic/agent/bridge/NoOpCloud.java
- agent-bridge/src/test/java/com/newrelic/agent/bridge/DefaultCollectionFactoryTest.java
- instrumentation/aws-java-sdk-dynamodb-1.11.106/src/main/java/com/amazonaws/services/dynamodbv2/AmazonDynamoDBClient_Instrumentation.java
- instrumentation/aws-java-sdk-dynamodb-1.11.106/src/main/java/com/nr/instrumentation/dynamodb_1_11_106/DynamoDBMetricUtil.java
- instrumentation/aws-java-sdk-dynamodb-1.11.106/src/test/java/com/agent/instrumentation/awsjavasdkdynamodb1_11_106/DynamoApiTest.java
- instrumentation/aws-java-sdk-dynamodb-1.11.106/src/test/java/com/nr/instrumentation/dynamodb_1_11_106/DynamoDBMetricUtilTest.java
- instrumentation/aws-java-sdk-dynamodb-2.15.34/src/main/java/com/nr/instrumentation/dynamodb_v2/DynamoDBMetricUtil.java
- instrumentation/aws-java-sdk-dynamodb-2.15.34/src/main/java/software/amazon/awssdk/services/dynamodb/DefaultDynamoDbAsyncClient_Instrumentation.java
- instrumentation/aws-java-sdk-dynamodb-2.15.34/src/main/java/software/amazon/awssdk/services/dynamodb/DefaultDynamoDbClient_Instrumentation.java
- instrumentation/aws-java-sdk-dynamodb-2.15.34/src/test/java/com/nr/instrumentation/dynamodb_v2/DynamoDBMetricUtilTest.java
- newrelic-agent/src/main/java/com/newrelic/agent/cloud/AwsAccountDecoder.java
- newrelic-agent/src/main/java/com/newrelic/agent/cloud/AwsAccountDecoderImpl.java
- newrelic-agent/src/main/java/com/newrelic/agent/cloud/CloudApiImpl.java
- newrelic-agent/src/main/java/com/newrelic/agent/service/analytics/SpanEventFactory.java
- newrelic-agent/src/main/java/com/newrelic/agent/tracers/DefaultTracer.java
- newrelic-agent/src/test/java/com/newrelic/agent/cloud/AwsAccountDecoderImplTest.java
- newrelic-agent/src/test/java/com/newrelic/agent/cloud/AwsUtilDecoderDisabledTest.java
- newrelic-agent/src/test/java/com/newrelic/agent/cloud/AwsUtilDecoderEnabledTest.java
- newrelic-agent/src/test/java/com/newrelic/agent/cloud/CloudApiImplTest.java
- newrelic-agent/src/test/java/com/newrelic/agent/service/analytics/SpanEventFactoryTest.java
- newrelic-agent/src/test/java/com/newrelic/agent/tracers/DefaultTracerTest.java
Allows the DynamoDB instrumentation to auto-discover the AWS account ID, so it does not have to be provided using the Cloud API nor configuration.
Closes #2124
> dynamodb: Auto discover AWS Account

- newrelic-agent/src/main/java/com/newrelic/agent/tracing/W3CTraceParentParser.java
Resolves #2126 
Based on the logic in method and the associated comment, multiple TraceParent headers is only an issue if the headers differ. If all the headers are the same value, that's ok.
This moves the log statement and associated supportability metric to execute only if the headers are different values.
> Correct multiple traceparent header logging

- newrelic-agent/src/main/java/com/newrelic/agent/config/SuperAgentIntegrationConfigImpl.java
- newrelic-agent/src/main/java/com/newrelic/agent/service/ServiceManagerImpl.java
- newrelic-agent/src/main/java/com/newrelic/agent/superagent/SuperAgentIntegrationService.java
Only log SuperAgent related info if the SA is in fact enabled.
> Only log if superagent is enabled

- instrumentation/aws-java-sdk-lambda-1.11.280/src/main/java/com/agent/instrumentation/awsjavasdk1/services/lambda/FunctionRawData.java
- instrumentation/aws-java-sdk-lambda-1.11.280/src/main/java/com/agent/instrumentation/awsjavasdk1/services/lambda/LambdaUtil.java
- instrumentation/aws-java-sdk-lambda-1.11.280/src/main/java/com/agent/instrumentation/awsjavasdk1/services/lambda/TokenLinkingAsyncHandler.java
- instrumentation/aws-java-sdk-lambda-1.11.280/src/main/java/com/amazonaws/services/lambda/AWSLambdaAsyncClient_Instrumentation.java
- instrumentation/aws-java-sdk-lambda-1.11.280/src/main/java/com/amazonaws/services/lambda/AWSLambdaClient_Instrumentation.java
- instrumentation/aws-java-sdk-lambda-1.11.280/src/test/java/com/agent/instrumentation/awsjavasdk1/services/lambda/LambdaUtilTest.java
- instrumentation/aws-java-sdk-lambda-1.11.280/src/test/java/com/agent/instrumentation/awsjavasdk1/services/lambda/LambdaUtilTest_ProcessData.java
- instrumentation/aws-java-sdk-lambda-2.1/src/main/java/com/agent/instrumentation/awsjavasdk2/services/lambda/FunctionRawData.java
- instrumentation/aws-java-sdk-lambda-2.1/src/main/java/com/agent/instrumentation/awsjavasdk2/services/lambda/LambdaUtil.java
- instrumentation/aws-java-sdk-lambda-2.1/src/main/java/software/amazon/awssdk/services/lambda/DefaultLambdaClient_Instrumentation.java
- instrumentation/aws-java-sdk-lambda-2.1/src/test/java/com/agent/instrumentation/awsjavasdk2/services/lambda/LambdaUtilTest_ProcessData.java
- newrelic-agent/src/main/java/com/newrelic/agent/cloud/AwsAccountDecoderImpl.java
- newrelic-agent/src/test/java/com/newrelic/agent/cloud/AwsUtilDecoderDisabledTest.java
Allows `cloud.resource_id` to be populated without configuration.
Close #2125
> Lambda: auto decode account id

- newrelic-agent/src/main/java/com/newrelic/agent/MetricNames.java
- newrelic-agent/src/main/java/com/newrelic/agent/config/JfrConfig.java
- newrelic-agent/src/main/java/com/newrelic/agent/config/JfrConfigImpl.java
- newrelic-agent/src/main/java/com/newrelic/agent/jfr/JfrService.java
- newrelic-agent/src/main/resources/newrelic.yml
- newrelic-agent/src/test/java/com/newrelic/agent/jfr/JfrServiceTest.java
Resolves #1511 
This is a continuation of @meiao 's [PR](https://github.com/newrelic/newrelic-java-agent/pull/371) to:
- Configure JFR queue size via `jfr.queue_size` - default of 250000
- Configure JFR harvest interval via `jrf.harvest_interval` - default of 10 seconds
- Send up supportability metrics with the configured JFR queue size and interval values
> Allow JFR queue size and harvest interval to be configured via agent config

- gradle.properties
Update csec agent dependency to version 1.6.0
> Bump csec agent to version 1.6.0

- newrelic-agent/src/main/java/com/newrelic/agent/language/SourceLibraryDetector.java
Minor change to add a bit of detection for apps using scala 3. 
This has some significant limitations:
- **This feature detects only the major version**. Scala 3 removed the API methods exposing the version number, so we no longer can read that in-code. An app running with Scala 3.3.4 and Scala 3.5.0 will both report the same supportability metric, `Supportability/SourceVersion/scala/3.x`.
- **(Existing limitation with scala <=2.13 detection): This feature only detects scala libraries present on the system classloader**. This means that apps launched with the `sbt` and `scala` CLIs, which load core scala classes into special Scala Class Loaders, will not capture this metric. Apps launched with `java`, or any other CLI that doesn't treat scala libraries special, will be ok.
> Add scala3 source detection

- instrumentation/netty-4.1.16/src/main/java/com/agent/instrumentation/netty4116/Http2RequestHeaderWrapper.java
When the Java Agent attempts to read headers from io.grpc.netty.GrpcHttp2HeadersUtils.GrpcHttp2RequestHeaders it throws an exception because the get method expects an io.netty.util.AsciiString input but receives a String from the agent.  
This fixes
https://github.com/newrelic/newrelic-java-agent/issues/2177
This code check to see if the Http2Headers class that is passed into the constructor for com.agent.instrumentation.netty4116.Http2RequestHeaderWrapper is GrpcHttp2RequestHeaders.  If it is it sets a flag.   
In both the getHeader and getHeaders methods, it checks if the GRPC flag is set and if true then creates an AsciiString to use.
> added checks for GRPC because it expects ASCIIString

- CHANGELOG.md
- gradle.properties
Post release tasks for the Java Agent to update the agent snapshot version to 8.18.0 and to update the changelog
> Post release tasks for 8.17.0 release

- instrumentation/vertx-core-3.8.0/README.md
- instrumentation/vertx-core-3.8.0/src/main/java/com/nr/vertx/instrumentation/VertxCoreUtil.java
- instrumentation/vertx-core-3.8.0/src/main/java/io/vertx/core/impl/FutureImpl_Instrumentation.java
- instrumentation/vertx-core-3.8.0/src/test/java/io/vertx/core/impl/FutureTokenTest.java
- instrumentation/vertx-core-3.9.0/src/main/java/com/nr/vertx/instrumentation/VertxCoreUtil.java
- instrumentation/vertx-core-3.9.0/src/main/java/io/vertx/core/impl/FutureImpl_Instrumentation.java
- instrumentation/vertx-core-3.9.0/src/test/java/io/vertx/core/impl/FutureTokenTest.java
- instrumentation/vertx-core-4.0.0/src/main/java/com/nr/vertx/instrumentation/VertxCoreUtil.java
- instrumentation/vertx-core-4.0.0/src/main/java/io/vertx/core/impl/future/FutureImpl_Instrumentation.java
- instrumentation/vertx-core-4.0.0/src/test/java/io/vertx/core/impl/future/FutureTokenTest.java
- instrumentation/vertx-core-4.1.0/src/main/java/com/nr/vertx/instrumentation/VertxCoreUtil.java
- instrumentation/vertx-core-4.1.0/src/main/java/io/vertx/core/impl/future/FutureImpl_Instrumentation.java
- instrumentation/vertx-core-4.1.0/src/test/java/io/vertx/core/impl/future/FutureTokenTest.java
- instrumentation/vertx-core-4.3.2/src/main/java/com/nr/vertx/instrumentation/VertxCoreUtil.java
- instrumentation/vertx-core-4.3.2/src/main/java/io/vertx/core/impl/future/FutureImpl_Instrumentation.java
- instrumentation/vertx-core-4.3.2/src/test/java/io/vertx/core/impl/future/FutureTokenTest.java
- instrumentation/vertx-core-4.5.0/src/main/java/com/nr/vertx/instrumentation/VertxCoreUtil.java
- instrumentation/vertx-core-4.5.0/src/main/java/io/vertx/core/impl/future/FutureImpl_Instrumentation.java
- instrumentation/vertx-core-4.5.0/src/test/java/io/vertx/core/impl/future/FutureTokenTest.java
- instrumentation/vertx-core-4.5.1/src/main/java/com/nr/vertx/instrumentation/VertxCoreUtil.java
- instrumentation/vertx-core-4.5.1/src/main/java/io/vertx/core/impl/future/FutureImpl_Instrumentation.java
- instrumentation/vertx-core-4.5.1/src/test/java/io/vertx/core/impl/future/FutureTokenTest.java
When a FutureImpl receives its first listener, it adds it to it's listener reference. When a second listener is received, it creates a ListenerArray, that will hold both received listeners and all future ones, and sets in its listener reference.
The agent used to create a token for each received listener. With this PR, it will create one token for the first listener, then if a second one is added, the first token will be expired and a new one will be created for the ListenerArray. Then if any other listener is received, no new tokens will be created.
The token linking will work as it used to, but now there is only the token from the ListenerArray to be linked. Thus preventing multiple linkings.
Closes #2171
> vertx: decrease amount of tokens created

- instrumentation/apache-log4j-layout-template-json-2.14.0/src/main/java/com/nr/agent/instrumentation/log4j2/layout/template/json/AgentUtils.java
- instrumentation/apache-log4j-layout-template-json-2.14.0/src/test/java/com/nr/agent/instrumentation/log4j2/layout/template/json/AgentUtilsTest.java
Resolves #2184 
- Use compiled regex pattern to detect un-escaped `",` sequences
- New unit tests
Regarding the use of regex, I ran several tests iterating over the `getIndexToModifyJson` method 1 million times, and the total time was around 450ms for each test.
> Fix edge case in JsonTemplateLayout with certain escaped sequences

- newrelic-agent/src/main/java/com/newrelic/agent/TransactionData.java
- newrelic-agent/src/test/java/com/newrelic/agent/TransactionDataTest.java
This fix will properly assign an apdex of `Frustrating` if an non-ignored and unexpected error is present on the transaction. This mirrors the behavior of the [`WebRequestDispatcher`](https://github.com/newrelic/newrelic-java-agent/blob/070441920e3b06df69d45187588308ebb5ed56bf/newrelic-agent/src/main/java/com/newrelic/agent/dispatchers/WebRequestDispatcher.java#L453) when reporting Apdex metrics on a transaction.
Resolves #2104
> Correct Apdex on transaction event if an error is present

- newrelic-agent/src/main/java/com/newrelic/agent/jfr/JfrService.java
Fix for https://new-relic.atlassian.net/browse/NR-345540
It appears that if the Java agent cannot obtain the port associated with a host then it will set it to `null`, resulting in a `host.hostname` attribute with a value like `4326afc46b32:null` being added to JFR events (where `4326afc46b32` is the hostname and `null` is the port number). This seems to be causing errors with GraphQL queries related to the Flame graph.
The approach that we follow with other agent data forms is to omit the port if it is `null`, so this PR follows that approach rather than setting a dummy port value.
> Don't add null port to hostname attribute on JFR events

- .github/workflows/Test-AITs.yml
Some AITs have failed many times in a row due to the runner running out of space.
This PR adds some clean up commands to try to free up more space.
> AIT: clean up disk

- instrumentation/kafka-clients-metrics-3.0.0/src/main/java/com/nr/instrumentation/kafka/ClientType.java
- instrumentation/kafka-clients-metrics-3.0.0/src/main/java/com/nr/instrumentation/kafka/MetricsScheduler.java
- instrumentation/kafka-clients-metrics-3.0.0/src/main/java/com/nr/instrumentation/kafka/NewRelicMetricsReporter.java
- instrumentation/kafka-clients-metrics-3.0.0/src/main/java/com/nr/instrumentation/kafka/NodeTopicRegistry.java
- instrumentation/kafka-clients-metrics-3.0.0/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer_Instrumentation.java
- instrumentation/kafka-clients-metrics-3.0.0/src/main/java/org/apache/kafka/clients/producer/KafkaProducer_Instrumentation.java
- instrumentation/kafka-clients-metrics-3.0.0/src/test/java/com/nr/agent/instrumentation/kafka/NodeTopicRegistryTest.java
- instrumentation/kafka-clients-metrics-3.7.0/src/main/java/com/nr/instrumentation/kafka/ClientType.java
- instrumentation/kafka-clients-metrics-3.7.0/src/main/java/com/nr/instrumentation/kafka/MetricsScheduler.java
- instrumentation/kafka-clients-metrics-3.7.0/src/main/java/com/nr/instrumentation/kafka/NewRelicMetricsReporter.java
- instrumentation/kafka-clients-metrics-3.7.0/src/main/java/com/nr/instrumentation/kafka/NodeTopicRegistry.java
- instrumentation/kafka-clients-metrics-3.7.0/src/main/java/org/apache/kafka/clients/consumer/internals/AsyncKafkaConsumer_Instrumentation.java
- instrumentation/kafka-clients-metrics-3.7.0/src/main/java/org/apache/kafka/clients/consumer/internals/LegacyKafkaConsumer_Instrumentation.java
- instrumentation/kafka-clients-metrics-3.7.0/src/main/java/org/apache/kafka/clients/producer/KafkaProducer_Instrumentation.java
- instrumentation/kafka-clients-metrics-3.7.0/src/test/java/com/nr/agent/instrumentation/kafka/NodeTopicRegistryTest.java
The previous code executed more verifications than needed for its functionality, it also stored duplicate data for those verifications. This PR simplifies the implementation by reducing the number of verifications and data stored.
The functionality being altered is to generate metrics (or event attributes) with the format:
1. MessageBroker/Kafka/Nodes/<node>
2. MessageBroker/Kafka/Nodes/<node>/<Produce|Consume>/<topic>
For each node a client connects to, a metric of the first format will be created. Then for the cartesian product of the sets of node x topic, a metric of the second format will be created.
So, for a producer client connecting  to nodes (n1, n2) and producing for the topics (t1, t2), the following metrics will be created:
- MessageBroker/Kafka/Nodes/n1
- …
> kafka-clients-metrics: Refactor node topic metrics

- instrumentation/glassfish-6/build.gradle
Add glassfish 8 verify instrumentation exclude: `org.glassfish.main.web:web-core:8.0.0-JDK17-M7`
> Add new exclude to glassfish6 verify instrumentation

- instrumentation/aws-java-sdk-dynamodb-1.11.106/src/main/java/com/amazonaws/services/dynamodbv2/AmazonDynamoDBClient_Instrumentation.java
- instrumentation/aws-java-sdk-dynamodb-2.15.34/src/main/java/software/amazon/awssdk/services/dynamodb/DefaultDynamoDbAsyncClient_Instrumentation.java
- instrumentation/aws-java-sdk-dynamodb-2.15.34/src/main/java/software/amazon/awssdk/services/dynamodb/DefaultDynamoDbClient_Instrumentation.java
- instrumentation/aws-java-sdk-firehose-2.1.0/src/main/java/software/amazon/awssdk/core/client/handler/AsyncClientHandler_Instrumentation.java
- instrumentation/aws-java-sdk-firehose-2.1.0/src/main/java/software/amazon/awssdk/core/services/firehose/DefaultFirehoseClient_Instrumentation.java
- instrumentation/aws-java-sdk-kinesis-1.11.106/src/main/java/com/amazonaws/services/kinesis/AmazonKinesisClient_Instrumentation.java
- instrumentation/aws-java-sdk-kinesis-1.11.272/src/main/java/com/amazonaws/services/kinesis/AmazonKinesisClient_Instrumentation.java
- instrumentation/aws-java-sdk-kinesis-2.1.0/src/main/java/software/amazon/awssdk/core/client/handler/AsyncClientHandler_Instrumentation.java
- instrumentation/aws-java-sdk-kinesis-2.1.0/src/main/java/software/amazon/awssdk/services/kinesis/DefaultKinesisClient_Instrumentation.java
- instrumentation/aws-java-sdk-kinesis-2.18.40/src/main/java/software/amazon/awssdk/core/client/handler/AsyncClientHandler_Instrumentation.java
- instrumentation/aws-java-sdk-kinesis-2.18.40/src/main/java/software/amazon/awssdk/services/kinesis/DefaultKinesisClient_Instrumentation.java
Removes `leaf=true` from aws sdk instrumentation so http requests made from the sdk are recorded.
Closes #2193
> aws-*: do not hide http request

- newrelic-agent/src/main/java/com/newrelic/agent/config/AgentControlIntegrationConfig.java
- newrelic-agent/src/main/java/com/newrelic/agent/config/AgentControlIntegrationConfigImpl.java
- newrelic-agent/src/main/java/com/newrelic/agent/config/AgentControlIntegrationHealthConfig.java
- newrelic-agent/src/main/java/com/newrelic/agent/service/ServiceManagerImpl.java
- newrelic-agent/src/test/java/com/newrelic/agent/config/AgentControlIntegrationConfigTest.java
Resolves #2210 
The following changes are being made to the Agent Control configuration variables:
- Removal of the agent_control.fleet_id config setting.
- Addition of agent_control.enabled to control whether health data is generated or not (replaces the fleet_id check used previously). Default value is false if not explicitly provided.
- A default value has been added for the agent_control.health.delivery_location: file:///newrelic/apm/health This value should be used if no value is supplied for the agent_control.health.delivery_location setting.
This allows all config settings to have default values if enabled is true.
> Refactor Agent Control config options

- instrumentation/kafka-clients-metrics-3.9.0/build.gradle
The new Kafka module was written with the wrong dependency, causing verify instrumentation to fail on classpath.
Fixing that.
> kafka-client-metrics-3.9.0: fixing dependency

- .github/workflows/Test-AITs.yml
- .github/workflows/X-Reusable-BuildAgent.yml
- .github/workflows/X-Reusable-VerifyInstrumentation.yml
The AIT cache is updated to v4.2.0 because the older version will lose support on 2/1/2025/
https://github.com/newrelic/newrelic-java-agent/issues/2214
> Update ait cache to v4.2.0

- .github/workflows/Create-Release-Tags.yml
- .github/workflows/publish_release.yml
We are getting rid of the internal [auto-layer-releases repo](https://source.datanerd.us/aws-lambda/auto-layer-releases/blob/master/app.py) and moving creating of the release tags into each agent's GHA deploy flow.
> Move init container release from lambda to GHA

- newrelic-agent/src/main/java/com/newrelic/agent/config/AgentConfigImpl.java
- newrelic-agent/src/test/java/com/newrelic/agent/config/AgentConfigImplTest.java
- newrelic-agent/src/test/java/com/newrelic/agent/jfr/JfrServiceTest.java
Resolves #2224 
Default `proxy_scheme` config setting to `http` (was previously `null`). If JFR is enabled, this will allow a proper default value to be set and sent to the underlying JFRDaemon component.
This won't effect the proxy settings in the agent itself - The proxy scheme was already being set to `http` in the underlying Apache `HttpHost` instance if the supplied scheme was null.
Update tests.
> Default proxy_scheme setting to "http"

- .github/workflows/Create-Custom-Jar.yml
There was a little typo in the custom jar workflow. 
Apparently the summary step is supposed to show the input ref. But it hasn't been doing that. Oops
> Update Create-Custom-Jar.yml with correct input

- newrelic-agent/src/test/java/com/newrelic/agent/language/SourceLibraryDetectorTest.java
- newrelic-weaver/build.gradle
- newrelic-weaver/src/main/java/com/newrelic/weave/ClassWeave.java
- newrelic-weaver/src/main/java/com/newrelic/weave/MethodCallInlinerAdapter.java
- newrelic-weaver/src/main/java/com/newrelic/weave/PreparedMatch.java
- newrelic-weaver/src/main/java/com/newrelic/weave/utils/ReturnInsnProcessor.java
- newrelic-weaver/src/main/java/com/newrelic/weave/utils/WeaveUtils.java
- newrelic-weaver/src/test/java/com/newrelic/weave/WeaveCoroutineTest.java
- newrelic-weaver/src/test/java/com/newrelic/weave/utils/ReturnInsnProcessorTest.java
- newrelic-weaver/src/test/java/com/newrelic/weave/utils/WeaveUtilsTest.java
- newrelic-weaver/src/test/java/com/newrelic/weave/weavepackage/testclasses/SampleCoroutine.kt
- newrelic-weaver/src/test/java/com/newrelic/weave/weavepackage/testclasses/Weave_SampleCoroutine.java
Resolves #2201 
This PR addresses a bug we found when attempting to weave `invokeSuspend` in Kotlin Coroutines. 
The weaver replaces RETURN instructions with GOTO instructions. This replacement can be unsafe if the operand stack prior to the RETURN instruction is not tidied up (ie, has more operands than needed to perform the return). This issue was previously unknown to us, because most compilers already clear their return stacks. However, the Kotlin compiler intentionally adds extra operands to Coroutines methods (for debugging purposes) and doesn't clean them up. 
The purpose of this PR is to check the offending method (`invokeSuspend`) and tidy up its return stacks before the return instructions are replaced with gotos.  
Here is how a method will be processed with this fix:
1. The …
> invokeSuspend edge case fix

- instrumentation/http4s-blaze-server-2.12_0.21/src/main/scala/com/nr/instrumentation/http4s/TransactionMiddleware.scala
- instrumentation/http4s-blaze-server-2.12_0.21/src/test/scala/com/nr/http4s/BlazeServerBuilderTest.scala
- instrumentation/http4s-blaze-server-2.12_0.22/src/main/scala/com/nr/instrumentation/http4s/TransactionMiddleware.scala
- instrumentation/http4s-blaze-server-2.12_0.22/src/test/scala/com/nr/http4s/BlazeServerBuilderTest.scala
- instrumentation/http4s-blaze-server-2.12_0.23/src/main/scala/com/nr/instrumentation/http4s/TransactionMiddleware.scala
- instrumentation/http4s-blaze-server-2.12_0.23/src/test/scala/com/nr/http4s/BlazeServerBuilderTest.scala
- instrumentation/http4s-blaze-server-2.13_0.21/src/main/scala/com/nr/instrumentation/http4s/TransactionMiddleware.scala
- instrumentation/http4s-blaze-server-2.13_0.21/src/test/scala/com/nr/http4s/BlazeServerBuilderTest.scala
- instrumentation/http4s-blaze-server-2.13_0.22/src/main/scala/com/nr/instrumentation/http4s/TransactionMiddleware.scala
- instrumentation/http4s-blaze-server-2.13_0.22/src/test/scala/com/nr/http4s/BlazeServerBuilderTest.scala
- instrumentation/http4s-blaze-server-2.13_0.23/src/main/scala/com/nr/instrumentation/http4s/TransactionMiddleware.scala
- instrumentation/http4s-blaze-server-2.13_0.23/src/test/scala/com/nr/http4s/BlazeServerBuilderTest.scala
- instrumentation/http4s-ember-server-2.12_0.23/src/main/scala/com/nr/instrumentation/http4s/TransactionMiddleware.scala
- instrumentation/http4s-ember-server-2.12_0.23/src/test/scala/com/nr/http4s/EmberServerBuilderTest.scala
- instrumentation/http4s-ember-server-2.13_0.23/src/main/java/org/http4s/ember/server/EmberServerBuilder_Instrumentation.java
- instrumentation/http4s-ember-server-2.13_0.23/src/main/scala/com/nr/instrumentation/http4s/TransactionMiddleware.scala
- instrumentation/http4s-ember-server-2.13_0.23/src/test/scala/com/nr/http4s/EmberServerBuilderTest.scala
Resolves #2150
Our http4s modules for blaze and ember server were not setting a web response in transactions (they were only setting the request attributes). 
This PR adds a small bit of code to each of the server modules to add the response attributes. It also adds a test for these attributes to all the tests.
> Add response attributes for http4s server modules

- newrelic-agent/src/main/java/com/newrelic/agent/jfr/JfrService.java
Resolves #2205 
We heard from a customer that their Tomcat process wasn't terminating when they ran the agent with JFR turned on. 
Turns out that although the external JFR *Controller* (responsible for sending JFR data) [runs on daemon threads](https://github.com/newrelic/newrelic-jfr-core/blob/6225c7ed6babfcccf72f67ac513ee7253814ee08/jfr-daemon/src/main/java/com/newrelic/jfr/daemon/JfrController.java#L33), the JFR *Service* inside the agent (responsible for turning the controller on and off) does not. So the JFR Service kept the JVM alive.
This PR makes the JFR Service use a daemon thread for its lifecycle like the rest of our services.
> Update JFR service to run as a daemon

- newrelic-agent/src/main/java/com/newrelic/agent/MetricNames.java
- newrelic-agent/src/main/java/com/newrelic/agent/config/ApplicationLoggingConfig.java
- newrelic-agent/src/main/java/com/newrelic/agent/config/ApplicationLoggingConfigImpl.java
- newrelic-agent/src/main/java/com/newrelic/agent/config/ApplicationLoggingForwardingConfig.java
- newrelic-agent/src/main/java/com/newrelic/agent/config/ApplicationLoggingLabelsConfig.java
- newrelic-agent/src/main/java/com/newrelic/agent/service/logging/LogSenderServiceImpl.java
- newrelic-agent/src/test/java/com/newrelic/agent/config/ApplicationLoggingLabelsConfigTest.java
Allows the user to add custom tags (labels) to agent-forwarded logs. 
Resolves Issue #2037
> Support Adding Labels to APM Forwarded Logs

- .github/workflows/Test-AITs.yml
the tests started timing out again. Disabling.
> exclude pekko AITs again

- instrumentation/aws-java-sdk-sqs-1.10.44/build.gradle
- instrumentation/aws-java-sdk-sqs-2.1.0/build.gradle
Remove "Enabled": false from the sqs modules. 
This was accidentally introduced in v8.18.
> Rename and reenable aws sqs modules

- newrelic-agent/src/main/java/com/newrelic/agent/config/AgentConfigFactory.java
- newrelic-agent/src/main/java/com/newrelic/agent/config/ApplicationLoggingConfigImpl.java
- newrelic-agent/src/test/java/com/newrelic/agent/config/MergeServerDataTest.java
Add support for server-side configs for `application_logging.enabled` and additional logging server-side configs provided by the collector
https://github.com/newrelic/newrelic-java-agent/issues/2174
> Add support for server-side application logging configs

- instrumentation/reactor-3.3.0/README.md
Some clarification on the `reactor-3.3.0` module. Why it is the way it is and when it should be loaded.
> Reactor module readme update

- newrelic-agent/src/main/java/com/newrelic/bootstrap/BootstrapAgent.java
This new configuration allows users to override the agent's logic that defines whether the `java.sql.*` classes are loaded by the platform class loader.
Fixes #2264
> Config to set whether java.sql is loaded by platform classloader

- newrelic-agent/src/main/java/com/newrelic/agent/utilization/AwsFargateMetadataFetcher.java
Refactor the code used to fetch the AWS Fargate docker ID to use `URLConnection`, which allows a sane timeout value to be assigned for the connect sequence.
Resolves #2247
> Refactor AWS docker id fetch

- instrumentation/kafka-clients-metrics-3.9.0/build.gradle
Cap kafka-clients-metrics-3.9.0 module to 4.0.0
> Cap kafka-clients-metrics-3.9.0 up to 4.0.0

- newrelic-agent/src/main/java/com/newrelic/agent/HeadersUtil.java
- newrelic-agent/src/main/java/com/newrelic/agent/Transaction.java
- newrelic-agent/src/main/java/com/newrelic/agent/TransactionApiImpl.java
- newrelic-agent/src/main/java/com/newrelic/agent/config/DistributedTracingConfig.java
- newrelic-agent/src/main/resources/newrelic.yml
- newrelic-agent/src/test/java/com/newrelic/agent/HeadersUtilTest.java
- newrelic-agent/src/test/java/com/newrelic/agent/tracers/DefaultTracerClmTest.java
- newrelic-agent/src/test/java/com/newrelic/agent/tracers/DefaultTracerTest.java
- newrelic-agent/src/test/java/com/newrelic/agent/tracing/W3CTraceStateSupportTest.java
New config options for how to sample when we have sampling data from an upstream entity.
Possible values:
default: New Relic's standard sampling rules will be used.
always_on: Always sample spans in this case.
always_off: Always skip sampling in this case.
YML config
```
distributed_tracing:
sampler:
remote_parent_sampled: default
remote_parent_not_sampled: default
```
So, setting `remote_parent_sampled` to `always_on` would tell the agent to try and always sample anything that an upstream entity told us was sampled, until the sampling reservoir is full.
Or, setting `remote_parent_not_sampled` to `always_off` would tell the agent to not bother sampling anything if the upstream entity told us that it was not sampled.
> Added sampling options when an inbound traceparent exists

- instrumentation/netty-4.1.16/src/main/java/com/agent/instrumentation/netty4116/NettyUtil.java
- instrumentation/netty-4.1.16/src/main/java/io/netty/handler/codec/http2/FrameReadListener_Instrumentation.java
- instrumentation/netty-4.1.16/src/main/java/io/netty/handler/codec/http2/Http2FrameCodec_Instrumentation.java
The default start point for starting netty HTTP2 transactions were reverted to use `io.netty.handler.codec.http2.Http2FrameCodec`. This will stop the 'unknown' http2 transactions at a loss possible coverage of http2 requests in niche scenarios. To add such granularity at the cost of possibly receiving 'unknown', a new feature flag is added via the config:
```yml
common: &default_settings
...
netty:
http2:
frame_read_listener:
start_transaction: true
```
https://github.com/newrelic/newrelic-java-agent/issues/2106
> Fix netty 'unknown' transactions

- newrelic-agent/src/main/java/com/newrelic/agent/instrumentation/context/InstrumentationClassTransformer.java
- newrelic-weaver/src/main/java/com/newrelic/weave/MethodCallInlinerAdapter.java
- newrelic-weaver/src/test/java/com/newrelic/weave/WeaveCoroutineTest.java
Resolves #2285 
This PR refactors our check for applying additional return insn processing to depend completely on the feature flag `-Dnewrelic.config.class_transformer.clear_return_stacks`. When this flag is set to `true`, the kotlin weaver fix will apply to **all methods**. When the flag is set to `false` (default/when the flag is unset), the kotlin weave fix will apply to **no methods**. A new warning message will appear in the agent logs instructing users to turn the flag on if the class transformer encounters the AIOOBE. 
This refactor was made because there isn't a consistent method signature that the Weaver can recognize as having the Kotlin problem; this is only known at the bytecode insn level, once the frames have been analyzed.
> Broaden suspends fix

- newrelic-agent/src/main/java/com/newrelic/agent/config/DistributedTracingConfig.java
Simple fix for the order on the config name
> Fixed the order on the sampler config name string

- newrelic-weaver/src/main/java/com/newrelic/weave/ClassWeave.java
- newrelic-weaver/src/main/java/com/newrelic/weave/utils/WeaveUtils.java
Resolves #2290 
This PR resolves the Illegal Access Error that has plagued environments using the agent with Scala 2.12 and JDK 11. 
The fix is to avoid bumping class file versions to the runtime version, as the agent does normally, for apps that have Scala 2.12 in the environment. Since Scala 2.12 is not always detectable by the agent (we check the system classloader for this - notably, sbt will load Scala classes into custom Scala loaders), there is also a feature flag to manually enable the fix via system property `-Dnewrelic.config.class_transformer.illegal_access_fix=true`. 
I added an AIT for the IllegalAccessError. The branch for that is [here](https://github.com/newrelic/java-agent-integration-tests/compare/illegal-access-ait?expand=1) with AITs run results …
> Fix Illegal Access Error

- instrumentation/netty-4.1.16/src/main/java/com/agent/instrumentation/netty4116/NettyUtil.java
- instrumentation/netty-4.1.16/src/main/java/io/netty/handler/codec/http2/FrameReadListener_Instrumentation.java
Fixes a bug in the internal netty config where setting the below config to `false` (i.e. the default value) causes 'Unknown' transactions to show up again. 
```
netty:
http2:
frame_read_listener:
start_transaction: false
```
Setting the above config to `true` disables HTTP2 support.
The fix sets up the config such that HTTP2 support is enabled when the config is `true`, setting it to `false` removes the `unknown` transaction issue but setting it to `true` increases granularity for catching HTTP2 requests while still risking the `unknown` transaction issue showing up.
> Fixes configuration logic for netty-4.1.16 module

- THIRD_PARTY_NOTICES.md
- newrelic-agent/build.gradle
Resolves #2328 
Upgrading to snakeyaml 2.4 causes startup failures for Glassfish and Wildfly, related to configuration of their respective loggers.
A drop in replacement for snakeyaml exists - [SafeYaml](https://github.com/Konloch/SafeYAML). This is a fork of snakeyaml v1.33 with the security fixes from snakeyaml 2.0 back ported.
> Drop in replacement for snakeyaml

- instrumentation/aws-java-sdk-sqs-2.1.0/src/main/java/com/newrelic/utils/SqsV2Util.java
- instrumentation/aws-java-sdk-sqs-2.1.0/src/main/java/software/amazon/awssdk/services/sqs/DefaultSqsAsyncClient_Instrumentation.java
- instrumentation/aws-java-sdk-sqs-2.1.0/src/main/java/software/amazon/awssdk/services/sqs/DefaultSqsClient_Instrumentation.java
- instrumentation/aws-java-sdk-sqs-2.1.0/src/test/java/com/newrelic/utils/SqsV2UtilTest.java
Adds a restriction on when to add distributed trace headers for SQS messages. This is based on how large the contents of a message is in bytes and the and the size of attributes. Messages with size greater than 251 KB and/or with 9 or more attributes are excluded from getting distributed trace headers added.
https://github.com/newrelic/newrelic-java-agent/issues/2292
> Add restrictions on when to add distributed trace headers for SQS messages. 

- instrumentation/kafka-clients-config-1.1.0/src/main/java/org/apache/kafka/kafka/common/config/AbstractConfig_Instrumentation.java
The existing code to emit KafkaConsumerConfig events, when enabled, has not worked for versions of Kafka 3.7 and onwards. Apache Kafka release versions since then have used a delegation pattern for KafkaConsumer instances, breaking the existing stack-based analysis that the integration applied to confirm that we were only emitting config events attached to actual clients, and not instantiated independently for whatever reason.
A separately maintained integration test confirmed the existing agent code failed to emit KafkaConsumerConfig events for versions 3.7.0 onwards, as did manual testing. That integration testing confirmed that the agent, with these fixes, produces the expected KafkaConsumerConfig events. Specific versions of kafka-clients tested: 2.6.2, 2.8.1, 3.3.2, 3.4.1, 3.5.0, …
> KafkaConsumerConfig event support for Kafka 3.7+ 

- instrumentation/vertx-postgres-sqlclient-4.4.2/build.gradle
Cap the verify range for vertx-postgres-sqlclient-4.4.2 to v5.0.0
> Cap vertx-postgres-sqlclient-4.4.2 to 5.0

- instrumentation/vertx-core-4.0.0/src/main/java/com/nr/vertx/instrumentation/AsyncHandlerWrapper.java
- instrumentation/vertx-core-4.0.0/src/main/java/io/vertx/core/impl/AbstractContext_Instrumentation.java
- instrumentation/vertx-core-4.0.0/src/test/java/com/nr/vertx/instrumentation/VertxBlockingTest.java
- instrumentation/vertx-core-4.1.0/src/main/java/com/nr/vertx/instrumentation/AsyncHandlerWrapper.java
- instrumentation/vertx-core-4.1.0/src/main/java/io/vertx/core/impl/AbstractContext_Instrumentation.java
- instrumentation/vertx-core-4.1.0/src/test/java/com/nr/vertx/instrumentation/VertxBlockingTest.java
- instrumentation/vertx-core-4.3.2/src/main/java/com/nr/vertx/instrumentation/AsyncHandlerWrapper.java
- instrumentation/vertx-core-4.3.2/src/main/java/io/vertx/core/impl/ContextBase_Instrumentation.java
- instrumentation/vertx-core-4.3.2/src/test/java/com/nr/vertx/instrumentation/VertxBlockingTest.java
- instrumentation/vertx-core-4.5.0/src/main/java/com/nr/vertx/instrumentation/AsyncHandlerWrapper.java
- instrumentation/vertx-core-4.5.0/src/main/java/io/vertx/core/impl/ContextImpl_Instrumentation.java
- instrumentation/vertx-core-4.5.0/src/test/java/com/nr/vertx/instrumentation/VertxBlockingTest.java
- instrumentation/vertx-core-4.5.1/src/test/java/com/nr/vertx/instrumentation/VertxBlockingTest.java
This PR contains a backport of the changes made in #1927 to older versions of the vertx-core implementation, to prevent the NPE to also happen when using an older version than 4.5.1.
> Backporting changes made in PR #1927 to older versions of the vertx-core implementation

- agent-bridge/src/main/java/com/newrelic/agent/bridge/NoOpTracedMethod.java
- agent-bridge/src/main/java/com/newrelic/agent/bridge/TracedMethod.java
- functional_test/src/test/java/com/newrelic/agent/bridge/MockTracer.java
- instrumentation/httpurlconnection/src/main/java/com/nr/agent/instrumentation/httpurlconnection/HttpURLConnectionConfig.java
- instrumentation/httpurlconnection/src/main/java/com/nr/agent/instrumentation/httpurlconnection/MetricState.java
- newrelic-agent/src/main/java/com/newrelic/agent/instrumentation/tracing/FlyweightTraceMethodVisitor.java
- newrelic-agent/src/main/java/com/newrelic/agent/trace/TransactionTrace.java
- newrelic-agent/src/main/java/com/newrelic/agent/tracers/AbstractTracer.java
- newrelic-agent/src/main/java/com/newrelic/agent/tracers/DefaultTracer.java
- newrelic-agent/src/main/java/com/newrelic/agent/tracers/NoOpTracer.java
- newrelic-agent/src/main/java/com/newrelic/agent/tracers/OtherRootSqlTracer.java
- newrelic-agent/src/main/java/com/newrelic/agent/tracers/OtherRootTracer.java
- newrelic-agent/src/main/java/com/newrelic/agent/tracers/UltraLightTracer.java
- newrelic-agent/src/test/java/com/newrelic/agent/instrumentation/sql/NoOpTrackingSqlTracer.java
- newrelic-agent/src/test/java/com/newrelic/agent/trace/TransactionTraceTest.java
- newrelic-agent/src/test/java/com/newrelic/agent/tracers/DefaultTracerTest.java
Resolves #2337 
Our HttpUrlConnection instrumentation creates a tracer for each response handler called by the HttpUrlConnection instance. We do this to ensure we have *some* tracer available to report the external call. This isn't ideal, because only the first tracer gets used to report the external, but it is not known at the time each tracer is created (via `@Trace` annotation) whether it is the first one. The result is that HttpUrlConnection transaction traces/DTs may be cluttered with a great number of response handler segments (such as `getInputStream`) that weren't chosen to become externals. 
This PR introduces a low-verbose mode to give users the option of suppressing these non-external segments in transaction traces and DTs. This can be enabled by setting: …
> Suppress segments in HttpUrlConnection

- .github/workflows/GHA-Spotbugs.yml
The spotbugs workflow seems to be timing out suddenly. This increases the timeout to 30 minutes
> Increase spotbugs workflow timeout

- newrelic-agent/build.gradle
Some dependency is bringing `org.jetbrains:annotations` and its contents are not being relocated. This could cause incompatibilities if an applications uses a different version of the artifact.
None
No new testing was created.
> Relocate IntelliJ annotations

- newrelic-agent/src/main/java/com/newrelic/agent/config/AgentConfigFactory.java
- newrelic-agent/src/test/java/com/newrelic/agent/config/AgentConfigFactoryTest.java
When the agent connects to NR, there will be a connect response with server side configuration data from NR. The agent takes this config data and merges it with the local config. One of the server side configuration settings is `sampling_target`.
This change adds support for the `sampling_target` server side config.
Resolves #447
> Support server side sampling_target config

- CHANGELOG.md
\### Overview
Remove redundant line in release notes for kafka consumers. It was confusing for users because we support adding auto-adding distributed traces for Kafka Clients in kafka-clients 2.0 and up.
https://github.com/newrelic/docs-website/pull/21014
> Remove redundant line in release notes for kafka consumers

- .github/workflows/publish_release.yml
- buildSrc/src/main/java/com/nr/builder/publish/PublishConfig.java
This PR fulfills our requirement to publish to the new Sonatype platform. It:
- updates our publish config to point to the OSSRH-Staging-API service
- updates our publish workflow to run a curl request that will deploy our repos from the OSSRH-Staging-API service to the Central Portal, where they can be reviewed, deleted, or released.
> Migrate release process

- newrelic-agent/build.gradle
This version bump mitigates (per dependabot):
```
Uncontrolled Recursion vulnerability in Apache Commons Lang.
This issue affects Apache Commons Lang: Starting with commons-lang:commons-lang 2.0 to 2.6, 
and, from org.apache.commons:commons-lang3 3.0 before 3.18.0.
The methods ClassUtils.getClass(...) can throw StackOverflowError on very long inputs. 
Because an Error is usually not handled by applications and libraries, a 
StackOverflowError could cause an application to stop.
Users are recommended to upgrade to version 3.18.0, which fixes the issue.
```
> Bump commons-lang version to 3.18.0

- instrumentation/graphql-java-22.0/build.gradle
- instrumentation/graphql-java-22.0/src/main/java/com/nr/instrumentation/graphql/GraphQLErrorHandler.java
Resolves #2301 
It seems that the only change to support v24+ of graphql is to update the method call on the [FieldValueInfo](https://github.com/graphql-java/graphql-java/blob/76f32f6c206a6f775f0ef0a95ab6f6a7ed539ffb/src/main/java/graphql/execution/FieldValueInfo.java#L71) instance. The `getFieldValue` method was marked for deprecation in v22 and removed in v24. The replacement call is `getFieldValueFuture` which still returns a `CompletableFuture`, although the generic typing changed.
Note that the verification explicitly skips v23.x since this was marked as "Do not use" by the maintainers.
https://github.com/graphql-java/graphql-java/releases/tag/v23.0
> Update to support v24 of graphql

- .github/workflows/TestSuite-PR.yml
Adds concurrency control to `TestSuite-PR.yml` workflow using `${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}` with `cancel-in-progress: true` to prevent overlapping test runs and optimize resource usage.
This workflow need an average of ~52min to complete. Analysis of **200 recent workflow runs from 692 total executions** reveals significant inefficiencies: 60 overlapping run pairs were identified, with 35 same-branch overlaps being most problematic. The `sqs-dt-truncate` branch had 19 overlapping runs, `main` had 7, and `spring-kafka` had 5. This resulted in approximately 1,649 minutes (27.5 hours) of overlapping execution time where resources were duplicated, representing 30% of all runs experiencing overlaps. Real-world examples include main branch runs …
> [CI Energy Waste] Add concurrency control testsuite pr

- instrumentation/opentelemetry-sdk-extension-autoconfigure-1.28.0/src/main/java/io/opentelemetry/sdk/autoconfigure/AutoConfiguredOpenTelemetrySdk.java
Add a default value that forces the `opentelemetry.sdk.autoconfigure.enabled` config to be treated as a `Boolean`. Otherwise it was being treated as a `String` and causing a `ClassCastException`.
```
2025-08-08T14:20:27,682-0700 [70724 1] com.newrelic.agent.instrumentation.ClassTransformerServiceImpl FINEST: An error was thrown from instrumentation library com.newrelic.instrumentation.opentelemetry-sdk-extension-autoconfigure-1.28.0
java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Boolean (java.lang.String and java.lang.Boolean are in module java.base of loader 'bootstrap')
```
> Fix AutoConfiguredOpenTelemetrySdk config

- instrumentation/couchbase-client-3.0.0/build.gradle
- instrumentation/couchbase-client-3.0.0/src/main/java/com/nr/instrumentation/couchbase/SamplingScan$Built_Skip.java
- instrumentation/couchbase-client-3.4.3/build.gradle
Add the `SamplingScan$Built_Skip.java` skip class to prevent double instrumentation with module version 3.0.0 and version 3.4.3.
Updated gradle file to utilize `passesOnly` rather than `passes` to properly verify the instrumentation ranges.
> Add skip class to prevent double instrumentation

- instrumentation/aws-java-sdk-dynamodb-2.15.34/build.gradle
- instrumentation/aws-java-sdk-s3-2.0/build.gradle
Update the verification ranges on DynamoDB and S3 SDKs so we only verify the full range of the latest minor version and the latest revision of each minor version.  This dramatically cuts down on the verification task runtime.
Details are in the comments of each build file.
> Optimize verification ranges for AWS DynamoDB and S3 SDKs

- instrumentation/lettuce-6.0/src/main/java/io/lettuce/core/Skip_RedisJsonCommandBuilder.java
... just like it's required for the 6.5 instrumentation.
> Skip the 6.0 instrumentation if the RedisJsonCommandBuilder exists

- newrelic-agent/src/main/java/com/newrelic/agent/config/ErrorCollectorConfigImpl.java
- newrelic-agent/src/test/java/com/newrelic/agent/config/ErrorCollectorConfigImplTest.java
Updated `ErrorCollectorConfigImpl.java` to trim whitespace from error class names during configuration parsing  
Resolves #2494 
Added 4 new test cases in `ErrorCollectorConfigImplTest.java` to verify proper handling of:
- Leading spaces in class names
- Trailing spaces in class names  
- Both leading and trailing spaces
- Newline prefixes in class names
[NR-465573]: https://new-relic.atlassian.net/browse/NR-465573?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> #2494: Fix parsing of error class names to handle whitespace and newlines
