.github/workflows/functional_test.yml, .github/workflows/unit_test.yml, gradle/script/java.gradle, infinite-tracing/build.gradle.kts, newrelic-agent/build.gradle
Adds a workflow for running Unit Tests in the PR Build workflow.
=> PR Build / Unit Test + Functional Test workflows

CHANGELOG.md, gradle.properties
update to next release version
=> update for 6.1.0

.github/workflows/functional_test.yml, .github/workflows/publish_main_snapshot.yml, .github/workflows/unit_test.yml
run test actions on PR request to branch
publish snapshot on merge to branch
=> run actions for dynamic-attach branch

.github/workflows/functional_test.yml, .github/workflows/publish_main_snapshot.yml, .github/workflows/unit_test.yml, gradle.properties
setup dynamic attach snapshot repo
=> change version to create dynamic attach snapshot repo

README.md
=> update README.md header for compliance

newrelic-agent/src/main/java/com/newrelic/agent/utilization/CloudUtility.java, newrelic-agent/src/test/java/com/newrelic/agent/utilization/CloudUtilityTest.java
I think that adding a unit test to cover the new behavior is helpful.  
This also lays the foundation of possibly leveraging mocks in the other tests in the future.
=> Add a test to confirm socket timeout behavior

newrelic-api/src/main/java/com/newrelic/api/agent/Agent.java
_Before contributing, please read our [contributing guidelines](https://github.com/newrelic/newrelic-java-agent/blob/main/CONTRIBUTING.md) and [code of conduct](https://github.com/newrelic/newrelic-java-agent/blob/main/CODE_OF_CONDUCT.md)._
Spell check.
N/A
[x] Does your code contain any breaking changes? Please describe. 
[x] Does your code introduce any new dependencies? Please describe.
=> Fix javadoc typo

buildSrc/build.gradle, functional_test/build.gradle, functional_test/src/test/java/com/newrelic/agent/instrumentation/ClassLoaderTest.java, functional_test/src/test/java/com/newrelic/agent/instrumentation/ClassRetransformBootstrapTest.java, functional_test/src/test/java/com/newrelic/agent/instrumentation/CustomExtensionTestAddition.java, gradle/script/java.gradle, instrumentation/async-http-client-2.1.0/src/test/java/com/nr/agent/instrumentation/asynchttpclient/AsyncHttpClient2_1_0Tests.java, newrelic-agent/build.gradle, newrelic-agent/src/main/java/com/newrelic/agent/config/JavaVersionUtils.java, newrelic-agent/src/test/java/com/newrelic/agent/config/JavaVersionUtilsTest.java, newrelic-weaver-scala/build.gradle, newrelic-weaver/build.gradle, newrelic-weaver/src/main/java/com/newrelic/weave/utils/SynchronizedAnnotationNode.java, newrelic-weaver/src/main/java/com/newrelic/weave/utils/SynchronizedClassNode.java, newrelic-weaver/src/main/java/com/newrelic/weave/utils/SynchronizedFieldNode.java, newrelic-weaver/src/main/java/com/newrelic/weave/utils/SynchronizedInnerClassNode.java, newrelic-weaver/src/main/java/com/newrelic/weave/utils/SynchronizedMethodNode.java, newrelic-weaver/src/main/java/com/newrelic/weave/utils/SynchronizedModuleExportNode.java, newrelic-weaver/src/main/java/com/newrelic/weave/utils/SynchronizedModuleNode.java, newrelic-weaver/src/main/java/com/newrelic/weave/utils/SynchronizedModuleOpenNode.java, newrelic-weaver/src/main/java/com/newrelic/weave/utils/SynchronizedModuleProvideNode.java, newrelic-weaver/src/main/java/com/newrelic/weave/utils/SynchronizedModuleRequireNode.java, newrelic-weaver/src/main/java/com/newrelic/weave/utils/SynchronizedTypeAnnotationNode.java, test-annotations/src/main/java/com/newrelic/test/marker/Java15IncompatibleTest.java
Adds support for Java 15 and upgrade ASM to version 8. Issue: https://github.com/newrelic/newrelic-java-agent/issues/53
=> Java 15 support

agent-bridge/src/main/java/com/newrelic/agent/bridge/NoOpPublicApi.java, agent-bridge/src/main/java/com/newrelic/agent/bridge/PublicApi.java, agent-bridge/src/main/java/com/newrelic/api/agent/NewRelic.java, functional_test/src/test/java/test/newrelic/test/agent/api/ApiTest.java, newrelic-agent/src/main/java/com/newrelic/api/agent/NewRelicApiImplementation.java, newrelic-agent/src/test/java/com/newrelic/agent/attributes/AgentAttributeSenderTest.java, newrelic-api/src/main/java/com/newrelic/api/agent/NewRelic.java
=> Fixes #69 by adding addCustomParameter(String, Boolean) api

CHANGELOG.md
=> update changelog for 6.1.0

README.md
For context:
https://docs.google.com/document/d/1JIog8rJL9MT6_AbIji8VK_RT3mOuIxC2Xb_xQsVksKk/edit#
https://newrelic.atlassian.net/browse/DOC-6121
_Before contributing, please read our [contributing guidelines](https://github.com/newrelic/newrelic-java-agent/blob/main/CONTRIBUTING.md) and [code of conduct](https://github.com/newrelic/newrelic-java-agent/blob/main/CODE_OF_CONDUCT.md)._
[here](https://github.com/newrelic/newrelic-java-agent/blob/main/ …
=> Updated README to match the current template

CHANGELOG.md
Update changelog about mbean fix
=> add note about mbean fix

gradle.properties
=> update to 6.2.0

instrumentation/scala-2.12.0/src/test/scala/com/nr/agent/instrumentation/scala/ProducerConsumerWithFutures.scala
New instrumentation causes a test failure. This change fixes the test failure.
=> fix scala instrumentation test

CHANGELOG.md
Changelog update for 6.2.0 release.
=> update changelog for 6.2.0

.github/workflows/functional_test.yml, .github/workflows/publish_main_snapshot.yml, .github/workflows/publish_release.yml, .github/workflows/unit_test.yml, CHANGELOG.md, gradle.properties, instrumentation/spring-webflux-5.0.0/src/main/java/com/nr/agent/instrumentation/spring/reactive/Util.java, instrumentation/spring-webflux-5.1.0/src/main/java/com/nr/agent/instrumentation/spring/reactive/Util.java
Bump version and update changelog for 6.2.1 point release.
=> 6.2.1 release

functional_test/src/test/java/test/newrelic/test/agent/servlet/ServletUserTest.java, infinite-tracing/src/main/java/com/newrelic/ChannelSupplier.java, instrumentation-build/src/main/java/com/nr/instrumentation/builder/CacheWeaveAttributesInManifest.java, newrelic-agent/src/main/java/com/newrelic/agent/Transaction.java, newrelic-agent/src/main/java/com/newrelic/agent/TransactionActivity.java, newrelic-agent/src/main/java/com/newrelic/agent/config/BaseConfig.java, newrelic-agent/src/main/java/com/newrelic/bootstrap/BootstrapAgent.java
I noticed a few issues small opportunities for improvement while I was perusing the code. 
=> cleanup a handful of small things

instrumentation-test/build.gradle, newrelic-agent/build.gradle
_Before contributing, please read our [contributing guidelines](https://github.com/newrelic/newrelic-java-agent/blob/main/CONTRIBUTING.md) and [code of conduct](https://github.com/newrelic/newrelic-java-agent/blob/main/CODE_OF_CONDUCT.md)._
Update org.apache.httpcomponents:httpclient dependency form `4.5.9` to `4.5.13`
fixes:
https://github.com/newrelic/newrelic-java-agent/issues/144
Ran existing tests
Updates existing dependency version
=> update apache httpclient to fixed version

instrumentation/jboss-jmx-7/build.gradle
This should have been included in #141
=> Cap jboss-jmx-7 verifier range

.github/pull_request_template.md, CODE_OF_CONDUCT.md, CONTRIBUTING.md
=> Fix repolinter failures

CHANGELOG.md
Update changelog for 6.3.0 release.
=> update changelog for 6.3.0 release

gradle.properties
Bump snapshot version after releasing 6.3.0
=> Bump snapshot version to 6.4.0

newrelic-agent/build.gradle
https://github.com/newrelic/newrelic-java-agent/issues/181 …
=> update snakeyaml dependency to 1.27

CHANGELOG.md, gradle.properties
Bump snapshot version and update changelog.
=> 6.4.0 post release cleanup

CHANGELOG.md
=> Update changelog for 6.5.0 release

gradle.properties
=> 6.5.0 post release

CHANGELOG.md, gradle.properties
=> Update changelog and bump version

newrelic-agent/src/main/java/com/newrelic/agent/config/JavaVersionUtils.java, newrelic-agent/src/test/java/com/newrelic/agent/config/JavaVersionUtilsTest.java
Some cleanup to reflect that the agent no longer supports Java 7.
=> Cleanup JavaVersionUtils and test

build.gradle, buildSrc/src/main/java/com/nr/builder/publish/PublishConfig.java, instrumentation/scala-2.12.0/src/main/java/scala/concurrent/impl/CallbackRunnable_Instrumentation.java, instrumentation/scala-2.13.0/src/main/java/scala/concurrent/impl/Transformation_Instrumentation.java, newrelic-scala-api/build.gradle.kts, newrelic-scala-api/src/main/scala/com/newrelic/scala/api/TraceOps.scala, newrelic-scala-api/src/test/scala/com/newrelic/scala/api/TraceOpsDSLTest.scala, settings.gradle
…nctions used across multiple threads
[N ] Does your …
=> Scala API to to capture transaction information in anonymous functions

CHANGELOG.md, gradle.properties
=> Updating changelog, bumping up version

newrelic-agent/src/main/java/com/newrelic/agent/config/JfrConfigImpl.java, newrelic-agent/src/main/resources/newrelic.yml
This reverts commit 8c1e5d8645e71a13e214541cc6f047db8cd682bd.
Disabling JFR by default
Are your contributions backwards compatible with relevant frameworks and APIs?
Yes
Does your code contain any breaking changes? Please describe. 
No
Does your code introduce any new dependencies? Please describe.
No
=> Revert "JFR on-by-default (#333)"

instrumentation/http4s-blaze-server-2.12_0.21/src/main/scala/com/nr/instrumentation/http4s/TransactionMiddleware.scala, instrumentation/http4s-blaze-server-2.13_0.21/src/main/scala/com/nr/instrumentation/http4s/TransactionMiddleware.scala
=> ensure error in txn doesn't affect calling code

instrumentation/play-2.5/build.gradle, instrumentation/play-2.6.13/build.gradle, instrumentation/play-2.6/build.gradle, instrumentation/play-2.7/build.gradle, instrumentation/play-ws-2.6.0/build.gradle, instrumentation/slick-2.11_3.2.0/build.gradle, instrumentation/slick-2.12_3.2.0/build.gradle, instrumentation/slick-3.0.0/build.gradle, newrelic-scala-api/build.gradle.kts, newrelic-scala-zio-api/build.gradle.kts
=> fix gradle scala compiler issue

CHANGELOG.md
Update CHANGELOG.md for 7.2.0 release
=> Update CHANGELOG.md for 7.2.0

newrelic-agent/src/test/java/com/newrelic/agent/service/analytics/TracerToSpanEventTest.java
=> add test for graphql attributes and clean up

CHANGELOG.md
Documentation fixes per Doc Team
=> Fix documentation per feedback

gradle.properties
Update version for next release per Java Agent Release Process
=> Update version to 7.3.0 for next release

newrelic-agent/src/main/java/com/newrelic/agent/HarvestServiceImpl.java, newrelic-agent/src/main/java/com/newrelic/agent/Harvestable.java, newrelic-agent/src/main/java/com/newrelic/agent/MetricNames.java, newrelic-agent/src/main/java/com/newrelic/agent/config/AgentConfigFactory.java, newrelic-agent/src/main/java/com/newrelic/agent/config/AgentConfigImpl.java, newrelic-agent/src/main/java/com/newrelic/agent/config/SpanEventsConfig.java, newrelic-agent/src/test/java/com/newrelic/agent/config/AgentConfigImplTest.java, newrelic-agent/src/test/java/com/newrelic/agent/config/SpanEventsConfigTest.java
looking at testing and confirming SpanEventConfig is set to respect server props
=> configure span event max samples 

CHANGELOG.md
Updates change log with release notes for 7.3.0
=> Update  CHANGELOG.md for 7.3.0

gradle.properties
bump to next agentVersion 7.4.0 snapshot
=> bump to next agentVersion 7.4.0 snapshot

newrelic-agent/build.gradle
Changes here: https://github.com/newrelic/newrelic-jfr-core/releases/tag/v1.6.0
=> Update to jfr-daemon 1.6.0

.github/workflows/GHA-AIT-functionality-basic_features--datastore-tests.yaml, .github/workflows/GHA-AIT-functionality-framework-tests.yaml, .github/workflows/GHA-AIT-functionality-security-tests.yaml, .github/workflows/GHA-AIT-functionality-server-tests.yaml
Remaining AIT workflows for PR
[Ticket: GHA-89]
https://newrelic.atlassian.net/browse/GHA-89
Remaining AIT workflows:
1. GHA-AIT-functionality-server-tests.yaml
2. GHA-AIT-functionality-security-tests.yaml
3. GHA-AIT-functionality-framework-tests.yaml
4. GHA-AIT-functionality-basic_features--datastore-tests.yaml
Github Actions when a pull request is made. More details …
=> GHA-89: transfer of all AIT assets

.github/workflows/GHA-Functional-Tests.yaml, .github/workflows/GHA-Instrumentation-Tests.yaml, .github/workflows/GHA-Unit-Tests.yaml
Change GHA workflows for java to use 17 instead of 16
=> Run Java tests against 17 instead of 16

.github/workflows/Java-11-Instrumentation-Tests.yml, .github/workflows/Java-17-Instrumentation-Tests.yml, .github/workflows/Java-8-Instrumentation-Tests.yml, .github/workflows/X-Reusable-Test.yml
Trying out reusable workflow for Java instrumentation tests
=> Add reusable workflow for Java instrumentation tests

.github/workflows/Java-11-Instrumentation-Tests.yml, .github/workflows/Java-17-Instrumentation-Tests.yml, .github/workflows/Java-8-Instrumentation-Tests.yml
Need to point to reusable workflow on 'main'
=> Point to resusable workflow on 'main'

settings.gradle
GHA isn't pulling latest settings.gradle so can't get it to publish scans
=> Add Gradle Enterprise plugin

settings.gradle
GHA won't see this config change unless its on main as well.
=> Add Gradle remote caching config

settings.gradle
Set default values for build scan tags
=> Set default values for build scan tags

.github/workflows/Java-11-Instrumentation-Tests.yml, .github/workflows/Java-17-Instrumentation-Tests.yml, .github/workflows/Java-8-Instrumentation-Tests.yml, .github/workflows/X-Reusable-Test.yml, settings.gradle
Send build scans for Java instrumentation tests
=> Send build scans for Java instrumentation tests

.github/workflows/GHA-AIT-functionality-basic_features--datastore-tests.yaml, .github/workflows/GHA-AIT-functionality-framework-tests.yaml, .github/workflows/GHA-AIT-functionality-security-tests.yaml, .github/workflows/GHA-AIT-functionality-server-tests.yaml, .github/workflows/GHA-AIT-functionality-trace-tests.yaml, .github/workflows/GHA-Functional-Tests.yaml, .github/workflows/Java-11-Instrumentation-Tests.yml, .github/workflows/Java-17-Instrumentation-Tests.yml, .github/workflows/Java-8-Instrumentation-Tests.yml, settings.gradle
Add Java Functional build scans to Gradle Enterprise
=> Add functional to ge

.github/workflows/GHA-Functional-Tests.yaml, .github/workflows/GHA-Unit-Tests.yaml
Send unit test build scan data to Gradle Enterprise
=> Send unit test build scan data to Gradle Enterprise

.github/workflows/GHA-Functional-Tests.yaml, .github/workflows/GHA-Scala-Functional-Tests.yaml
Add Scala functional test build scan data to GE
Scala functional test to be sent to GE
=> Add Scala functional test build scan data to GE

.github/workflows/GHA-Scala-Functional-Tests.yaml, .github/workflows/GHA-Scala-Instrumentation-Tests.yaml
Add Scala instrumentation tests to GE build scans
=> Add Scala instrumentation test build scan data to GE

settings.gradle
Fix scala version to nothing when not specified
=> Fix scala version to nothing when not specified

instrumentation/newrelic-cats-effect3-api/src/main/scala/com/newrelic/cats3/api/Util.scala, instrumentation/newrelic-scala-cats-api/src/main/scala/com/newrelic/cats/api/Util.scala, instrumentation/newrelic-scala-zio-api/src/main/scala/com/newrelic/zio/api/Util.scala
=> additional null check for transaction tracer

.github/workflows/GHA-Scala-Instrumentation-Tests.yaml
Minor fix to running of tests from forks on GHA
[Y ] Are your contributions backwards compatible with relevant frameworks and APIs?
=> Fix AWS key cond in Scala instr workflow

.github/workflows/GHA-Functional-Tests.yaml, .github/workflows/GHA-Scala-Functional-Tests.yaml, .github/workflows/GHA-Scala-Instrumentation-Tests.yaml, .github/workflows/GHA-Unit-Tests.yaml, .github/workflows/X-Reusable-Test.yml
Disable Gradle wrapper validation for GHA
=> Comment out gradle wrapper validation

.github/workflows/GHA-Functional-Tests.yaml, .github/workflows/GHA-Scala-Functional-Tests.yaml, .github/workflows/GHA-Scala-Instrumentation-Tests.yaml, .github/workflows/GHA-Unit-Tests.yaml, .github/workflows/X-Reusable-Test.yml, settings.gradle
Fixed the IP address for remainder of trial
=> Adjust GE IP Address

instrumentation/akka-2.2/build.gradle, instrumentation/akka-2.2/src/test/java/com/nr/instrumentation/akka22/test/AkkaTest.java
Scala version upgrade for Akka library fixes issue
#483 …
=> fix failing java 11 Akka tests #483

instrumentation/monix-2.13_3.4.0/build.gradle
Space was causing the instrumentation verifier to fail on the monix instrumentation.
=> Fix syntax breaking instrumentation verifier

newrelic-agent/src/main/java/com/newrelic/agent/config/JavaVersionUtils.java
Updating the suggested version for a Java 7 compatible agent to a point release not affected by Log4Shell.
=> Updating suggested agent version for Java 7

newrelic-agent/src/test/java/com/newrelic/agent/config/JavaVersionUtilsTest.java
=> Fix for broken unsupportedJavaVersionMessageWhenLessThanJava8 test

.github/workflows/AITs-Basic-Features-Flaky.yml, .github/workflows/AITs-Basic-Features-Special-JREs.yml, .github/workflows/AITs-Basic-Features.yml, .github/workflows/AITs-Datastores.yml, .github/workflows/AITs-Frameworks.yml, .github/workflows/AITs-Security.yml, .github/workflows/AITs-Servers.yml, .github/workflows/AITs-Traces.yml, .github/workflows/GHA-Functional-Tests.yaml, .github/workflows/GHA-Scala-Functional-Tests.yaml, .github/workflows/GHA-Scala-Instrumentation-Tests.yaml, .github/workflows/GHA-Unit-Tests.yaml, .github/workflows/Java-11-Instrumentation-Tests.yml, .github/workflows/Java-17-Instrumentation-Tests.yml, .github/workflows/Java-8-Instrumentation-Tests.yml
Want to get this in before I forget.
=> Remove 'assigned' state to cause GHA workflows during PRs

.github/workflows/Java-18-ea-Instrumentation-Tests.yml, .github/workflows/X-Reusable-Test.yml
Add Java 18 early access instrumentation test run
=> Add Java 18 ea Instrumentation test run

.github/workflows/AITs-Basic-Features.yml, .github/workflows/Java-17-Instrumentation-Tests.yml, .github/workflows/Java-18-ea-Instrumentation-Tests.yml, .github/workflows/X-Reusable-Test.yml
We need to move reusable workflow to a different repo
=> Fix Java 17 Instrumentation tests

.github/workflows/AITs-Basic-Features-Special-JREs.yml, .github/workflows/AITs-Basic-Features.yml, .github/workflows/AITs-Datastores.yml, .github/workflows/AITs-Frameworks.yml, .github/workflows/AITs-Security.yml, .github/workflows/AITs-Servers.yml, .github/workflows/AITs-Traces.yml, .github/workflows/GHA-Functional-Tests.yaml, .github/workflows/GHA-Scala-Functional-Tests.yaml, .github/workflows/GHA-Scala-Instrumentation-Tests.yaml, .github/workflows/X-Reusable-Test.yml
Add Java 18 EA support for AITs on GHA
=> Add Java 18 EA for current AITs

newrelic-agent/src/main/java/com/newrelic/agent/config/JavaVersionUtils.java, newrelic-agent/src/test/java/com/newrelic/agent/config/JavaVersionUtilsTest.java
Minor refactor and renaming to make it easier to add major Java versions.
=> JavaVersionUtil refactor

newrelic-agent/src/main/java/com/newrelic/agent/config/ConfigConstant.java, newrelic-agent/src/main/java/com/newrelic/agent/service/analytics/ErrorEventFactory.java, newrelic-agent/src/test/java/com/newrelic/agent/errors/ExpectedErrorFactoryTest.java
AIT: 🟢  https://javaagent-build.pdx.vm.datanerd.us/job/AIT_Configurable/235/
This addresses #581
=> Increase error message length

instrumentation/logback-classic-1.2/src/main/java/ch/qos/logback/classic/spi/LoggingEvent_Instrumentation.java
Use formatted message instead the raw message when forwarding logs from logback
N/A
TODO
=> Send formatted message on logback

instrumentation/apache-log4j-1/src/main/java/com/nr/agent/instrumentation/log4j1/AgentUtil.java, instrumentation/apache-log4j-2/src/main/java/com/nr/agent/instrumentation/log4j2/AgentUtil.java, instrumentation/apache-log4j-2/src/main/java/org/apache/logging/log4j/core/layout/StringBuilderEncoder_Instrumentation.java, instrumentation/java.logging-jdk8/src/main/java/com/nr/instrumentation/jul/AgentUtil.java, instrumentation/logback-classic-1.2/src/main/java/ch/qos/logback/classic/spi/LoggingEvent_Instrumentation.java, instrumentation/logback-classic-1.2/src/main/java/com/nr/agent/instrumentation/logbackclassic12/AgentUtil.java
Resolves https://github.com/newrelic/newrelic-java-agent/issues/752
=> Refactor metadata blob

instrumentation-test/src/main/java/com/newrelic/agent/introspec/Introspector.java, instrumentation-test/src/main/java/com/newrelic/agent/introspec/internal/IntrospectorImpl.java, instrumentation-test/src/main/java/com/newrelic/agent/introspec/internal/IntrospectorLogSenderService.java, newrelic-agent/src/main/java/com/newrelic/agent/service/logging/LogSenderService.java
Resolves https://github.com/newrelic/newrelic-java-agent/issues/727
=> Update Introspector to test LogEvents

instrumentation/jedis-3.0.0/build.gradle
this just cleans up a comment that should not have been merged.
=> forgot to drop a comment

instrumentation/apache-log4j-1/src/test/resources/application_logging_enabled.yml, instrumentation/apache-log4j-2/src/test/java/com/nr/agent/instrumentation/log4j2/LoggerConfig_InstrumentationTest.java, instrumentation/apache-log4j-2/src/test/resources/application_logging_enabled.yml, instrumentation/logback-classic-1.2/src/test/resources/application_logging_enabled.yml
Resolves https://github.com/newrelic/newrelic-java-agent/issues/728
=> Log4j2 instrumentation test

newrelic-agent/src/test/java/com/newrelic/agent/MockDataSender.java, newrelic-agent/src/test/java/com/newrelic/agent/RPMServiceTest.java
I'm happy to add more tests but didn't know if I should spend more time getting more granular here or get other tests written.
Updated RPMServiceTests to test log events
https://github.com/newrelic/newrelic-java-agent/issues/730
=> Add send log event tests

instrumentation/logback-classic-1.2/src/test/java/com/nr/agent/instrumentation/logbackclassic12/LoggingEvent_InstrumentationTest.java
Resolves https://github.com/newrelic/newrelic-java-agent/issues/729
=> Add instrumentation test for Logback 1.2 LogEvents

agent-model/src/test/java/com/newrelic/agent/model/LogEventTest.java
Add tests to LogEventTest
https://github.com/newrelic/newrelic-java-agent/issues/726
=> Implement LogEventTest

newrelic-agent/src/test/java/com/newrelic/agent/config/AgentConfigImplTest.java
These tests are for:
U/F/I Tests: Implement AgentConfigImplTest getApplicationLoggingConfig tests #732
https://github.com/newrelic/newrelic-java-agent/issues/732
=> add tests for logging config

newrelic-agent/src/test/java/com/newrelic/agent/attributes/AttributeValidatorTest.java
Implement attribute validator test for log event attributes
[Include a link to the related GitHub issue, if applicable](https://github.com/newrelic/newrelic-java-agent/issues/731)
=> Implement AttributeValidatorTest testVerifyTruncatedValue for LogEvent attributes

newrelic-agent/src/test/java/com/newrelic/agent/config/ApplicationLoggingConfigImplTest.java
This adds tests for `ApplicationLoggingConfigImpl`
It address part of: https://github.com/newrelic/newrelic-java-agent/issues/733
[The agent includes a suite of tests which should be used to
](https://github.com/newrelic/newrelic-java-agent/blob/6f45eec3c20287cda7a1ea418d4fb4c44f2bc6f7/newrelic-agent/src/test/java/com/newrelic/agent/config/ApplicationLoggingConfigImplTest.java#L5-L7)
=> Logging config impl tests (ApplicationLoggingConfigImpl)

instrumentation-test/src/main/java/com/newrelic/agent/introspec/internal/IntrospectorRPMService.java, newrelic-agent/src/main/java/com/newrelic/agent/IRPMService.java, newrelic-agent/src/main/java/com/newrelic/agent/RPMService.java, newrelic-agent/src/main/java/com/newrelic/agent/service/logging/LogSenderServiceImpl.java, newrelic-agent/src/main/java/com/newrelic/agent/transport/DataSender.java, newrelic-agent/src/main/java/com/newrelic/agent/transport/DataSenderImpl.java, newrelic-agent/src/test/java/com/newrelic/agent/BaseRPMService.java, newrelic-agent/src/test/java/com/newrelic/agent/MockDataSender.java, newrelic-agent/src/test/java/com/newrelic/agent/MockRPMService.java, newrelic-agent/src/test/java/com/newrelic/agent/RPMServiceTest.java, newrelic-agent/src/test/java/com/newrelic/agent/transport/DataSenderImplTest.java
Add tests for send log events with too big of a payload
https://github.com/newrelic/newrelic-java-agent/issues/735
=> Add send log events payload too big 2 data sender imple test test max payload test

newrelic-agent/src/main/java/com/newrelic/agent/HarvestServiceImpl.java
Resolves https://github.com/newrelic/newrelic-java-agent/issues/743
=> Implement event_harvest_config.harvest_limits for log_event_data

newrelic-agent/src/test/java/com/newrelic/agent/config/ApplicationLoggingForwardingConfigTest.java
Tests for `ApplicationLoggingForwardingConfigImpl`
https://github.com/newrelic/newrelic-java-agent/issues/733
=> log forwarding tests (ApplicationLoggingForwardingConfigImpl)

newrelic-agent/src/test/java/com/newrelic/agent/config/ApplicationLoggingLocalDecoratingConfigTest.java
Tests for ApplicationLoggingLocalDecoratingConfig
Resolves part of:
https://github.com/newrelic/newrelic-java-agent/issues/733
=> local decorating config tests added (ApplicationLoggingLocalDecoratingConfig)

newrelic-agent/src/main/resources/newrelic.yml
Confirmed with PM that this is how we want to ship the default yaml.
=> Update default yaml

newrelic-agent/src/main/java/com/newrelic/agent/HarvestServiceImpl.java
Just adds a log line to clarify how/why the maxSamplesStored has been set.
=> Clarify how and why maxSamplesStored is being set to 0 by the collector

.github/workflows/AITs-Basic-Features.yml
Include AIT logging test in AIT basic features AIT workflow.
For the logging initiative a collection of tests for logging was added to the AIT project.
This changes includes them in the basic feature workflow run.
This will need to be committed at the end
https://github.com/newrelic/newrelic-java-agent/issues/737
https://github.com/newrelic/newrelic-java-agent/issues/738
Ran branch featuring the added test.
[X] Are your contributions backwards compatible with relevant frameworks and APIs?
[X] Does your code contain any breaking changes? Please describe. 
[X] Does your code introduce any new dependencies? Please describe.
=> Include AIT logging test in AIT basic features AIT workflow

instrumentation/r2dbc-mysql/build.gradle
MySQL R2DBC driver verify instrumentation fix to exclude unsupported versions.
Ran verify instrumentation gradle task locally
[X] Does your code contain any breaking changes? Please describe. No
=> MySQL R2DBC driver verify instrumentation fix

instrumentation/apache-log4j-1/src/main/java/com/nr/agent/instrumentation/log4j1/AgentUtil.java, instrumentation/apache-log4j-2/src/main/java/com/nr/agent/instrumentation/log4j2/AgentUtil.java, instrumentation/java.logging-jdk8/src/main/java/com/nr/instrumentation/jul/AgentUtil.java, instrumentation/logback-classic-1.2/src/main/java/com/nr/agent/instrumentation/logbackclassic12/AgentUtil.java
There was a recent [change](https://source.datanerd.us/agents/agent-specs/commit/88b582f520980b52299461a2a03abe76343dac61#diff-22ea975b3218ea7ba317770796151db7a25e9e8a59ef0799d8223ee8506802c9) to the [Application Logging spec](https://source.datanerd.us/agents/agent-specs/blob/main/Application-Logging.md#log-forwarding) to refactor the `log.level` attribute to just `level`. This PR makes that change.
Related to: https://github.com/newrelic/java-agent-integration-tests/pull/35
---
Log event in payload using `level`
```
{"trace.id":"1fad5f1a14ae7e95a4353df8bd6460cc","hostname":"192.168.1.17","level":"INFO","entity.guid":"OTk4ODc5fEFQTXxBUFBMSUNBVElPTnwxODE1NjY5Mg","entity.name":"LoggingApp","span.id":"878f8f2a25962c11","message":"This was logged at INFO with a message from a Supplier<T>: …
```
=> Refactor log.level attribute to level

.github/workflows/AITs-Clients.yml, .github/workflows/AITs-Datastores.yml, .github/workflows/AITs-R2DBC.yml
Adds H2, HTTP4S, Cassandra tests to workflow
=> Add H2, HTTP4S, Cassandra tests to workflow

.github/workflows/Create-Custom-Jar.yml, .github/workflows/README.md
A new GHA workflow to generate custom jars. This will centralize the building and storage of custom jars.
=> Create custom jar workflow

.github/workflows/Create-Custom-Jar.yml
The first commit for the Create Custom Jar workflow had a syntax error.
=> Fix Create-Custom-Jar.yml

.github/workflows/AITs-Clients.yml, .github/workflows/AITs-Frameworks.yml, .github/workflows/AITs-R2DBC.yml
Add additional client and framework AIT tests to workflows
https://github.com/newrelic/java-agent-integration-tests/issues/21
Additional tests
[X] Does your code contain any breaking changes? Please describe.  No
=> Add additional client and framework AIT tests to workflows

instrumentation/jax-rs-1.0/build.gradle
=> back jax-rs for jak ee8

instrumentation/jax-rs-1.0/build.gradle, instrumentation/jersey-client-2.26/build.gradle
=> more errors in changes

instrumentation/jax-rs-1.0/build.gradle, instrumentation/jersey-client-2.26/build.gradle, settings.gradle
=> Fix jax rs again

instrumentation/jersey-2/build.gradle
Reverts newrelic/newrelic-java-agent#912
=> Revert "jersey build wth jakartajar"

instrumentation/jersey-2/build.gradle
Update dependencies. Use jetty 9x for testImplementation
=> revert jetty version change

instrumentation/jersey-2/build.gradle
=> Fix jersey

.github/workflows/AITs-Frameworks.yml
Enabling some AITs after some issues were fixed in the cache repos.
=> Enabling AITs

newrelic-agent/src/main/java/com/newrelic/agent/config/AgentConfigImpl.java, newrelic-agent/src/main/java/com/newrelic/agent/util/Strings.java, newrelic-agent/src/test/java/com/newrelic/agent/util/StringsTest.java
This change replaces a regex-based replaceAll for `[.-]` with `_` to use an explicitly written method. 
Prior to this change, any call to lookup configuration values within `AgentConfigImpl` would incur the allocation cost of a `java.util.regex.Matcher` object in addition to its internal objects (notably a `int[]`). This was improved in #592 but still requires the use of regex to do the replace. The problem here is that this function can be called in the hot path of stat collection.
This PR adds an explicit function to replace the regex utilization in this path. …
=> Replacing regex replace with iterative char replace

instrumentation/jetty-10/build.gradle, instrumentation/jetty-10/src/main/java/com/nr/agent/instrumentation/jetty10/AsyncListenerFactory.java, instrumentation/jetty-10/src/main/java/com/nr/agent/instrumentation/jetty10/JettyRequest.java, instrumentation/jetty-10/src/main/java/com/nr/agent/instrumentation/jetty10/JettyResponse.java, instrumentation/jetty-10/src/main/java/com/nr/agent/instrumentation/jetty10/ServerHelper.java, instrumentation/jetty-10/src/main/java/org/eclipse/jetty/server/HttpTransport.java, instrumentation/jetty-10/src/main/java/org/eclipse/jetty/server/JettySampler.java, instrumentation/jetty-10/src/main/java/org/eclipse/jetty/server/Request.java, instrumentation/jetty-10/src/main/java/org/eclipse/jetty/server/Server.java, instrumentation/jetty-10/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java, instrumentation/jetty-10/src/main/java/org/eclipse/jetty/server/handler/ErrorHandler.java, instrumentation/jetty-9.3/src/main/java/com/nr/agent/instrumentation/jetty93/AsyncListenerFactory.java, newrelic-scala-cats-api/src/test/scala/com/newrelic/cats/api/TraceOpsDSLTest.scala, settings.gradle
Adds instrumentation support for Jetty 10
Tests will be in AITs.
=> Jetty 10 instrumentation support updated

.github/workflows/AITs-Clients.yml
Add GRPC client test suite to client AIT workflow.
[NR-2426](https://issues.newrelic.com/browse/NR-2426) - Support for GRPC 1.42.1.
[NR-2427](https://issues.newrelic.com/browse/NR-2427) - GRPC Bi-directional stream support
Additional tests
[X] Does your code contain any breaking changes? Please describe.  No
=> NR-2426, NR-2427 - Add GRPC client test suite to client AIT workflow

instrumentation/jakarta-ws-rs-3.0.0/build.gradle, instrumentation/jakarta-ws-rs-3.0.0/src/main/java/com/nr/instrumentation/jakarta/ws/rs/api/Request_Instrumentation.java, instrumentation/jakarta-ws-rs-3.0.0/src/test/java/com/nr/instrumentation/jakarta/ws/rs/api/SubResourceTest.java, instrumentation/jax-rs-1.0/build.gradle, instrumentation/jax-rs-1.0/src/main/java/com/nr/instrumentation/javax/ws/rs/api/Request_Instrumentation.java, instrumentation/jersey-3/src/main/java/org/glassfish/jersey/server/ContainerResponse.java, instrumentation/jersey-3/src/main/java/org/glassfish/jersey/server/RequestImpl.java, instrumentation/jersey-3/src/main/java/org/glassfish/jersey/server/ServerRuntime_Instrumentation.java, instrumentation/jersey-3/src/test/java/com/nr/instrumentation/jersey/JerseyTests.java, instrumentation/jersey-3/src/test/java/com/nr/instrumentation/jersey/resources/AsyncResource.java, instrumentation/jersey-3/src/test/java/com/nr/instrumentation/jersey/resources/SyntheticIOException.java, instrumentation/jersey-3/src/test/java/com/nr/instrumentation/jersey/resources/SyntheticIOExceptionWriterInterceptor.java, settings.gradle
jersey-3 to work with jakarta.ws.rs
also weaves Request (NoOp) for jakarta.ws.rs and jax.ws.rs modules so that verifier can be used in those modules.
=> Jaxrstojakarta

instrumentation/jakarta-ws-rs-3.0.0/build.gradle, instrumentation/jakarta-ws-rs-3.0.0/src/test/java/com/nr/instrumentation/jakarta/ws/rs/api/JakartaRsTests.java, instrumentation/jersey-3/build.gradle
rolls dependencies a bit to use java 8 compatible and drop forcing java 11 compile
=> java 8 compatible dep versions

instrumentation/jakarta-ws-rs-3.0.0/build.gradle, instrumentation/jakarta-ws-rs-3.0.0/src/test/java/com/nr/instrumentation/jakarta/ws/rs/api/JaxRsTests.java, instrumentation/jersey-3/build.gradle
Reverts newrelic/newrelic-java-agent#958
=> Revert "java 8 compatible dep versions"

CHANGELOG.md, gradle.properties, gradle.properties.gha
Updated the agent snapshot version from 7.9.0 to 7.10.0
=> Java Agent Version 7.9.0 Post Release Tasks

instrumentation/jersey-client-3/build.gradle, instrumentation/jersey-client-3/src/main/java/com/nr/instrumentation/jersey/client/InboundWrapper.java, instrumentation/jersey-client-3/src/main/java/com/nr/instrumentation/jersey/client/JerseyClientUtils.java, instrumentation/jersey-client-3/src/main/java/com/nr/instrumentation/jersey/client/OutboundWrapper.java, instrumentation/jersey-client-3/src/main/java/org/glassfish/jersey/client/ClientRuntime_Instrumentation.java, instrumentation/jersey-client-3/src/main/java/org/glassfish/jersey/client/ResponseCallback_Instrumentation.java, instrumentation/jersey-client-3/src/test/java/com/nr/agent/instrumentation/jerseyclient3/JerseyClient3Test.java
Implementation of the Jakarta 9 compatible Jersey Client 3.
=> Jersey Client 3

newrelic-agent/src/main/java/com/newrelic/agent/instrumentation/context/InstrumentationContextManager.java
I didn't try to be clever here.
=> Fix EJB annotation vistor

build.gradle, instrumentation/akka-http-2.11_2.4.5/build.gradle, instrumentation/akka-http-2.13_10.1.8/build.gradle, instrumentation/akka-http-core-0.4/build.gradle, instrumentation/akka-http-core-0.7/build.gradle, instrumentation/akka-http-core-10.0/build.gradle, instrumentation/akka-http-core-10.2.0/build.gradle, instrumentation/akka-http-core-2.11_10.0.11/build.gradle, instrumentation/akka-http-core-2.13_10.1.8/build.gradle, instrumentation/akka-http-core-2.13_10.2.0/build.gradle, instrumentation/grails-2/build.gradle, instrumentation/jboss-7/build.gradle, instrumentation/jdbc-embedded-derby-10.15.1.3/build.gradle, instrumentation/jsp-3/build.gradle, instrumentation/mule-3.6/build.gradle, instrumentation/mule-3.7/build.gradle, instrumentation/mule-base/build.gradle, instrumentation/spray-can-1.3.1/build.gradle, instrumentation/spray-can-http-client-1.3.1/build.gradle, instrumentation/spray-client-1.3.1/build.gradle, instrumentation/spray-http-1.3.1/build.gradle, instrumentation/spring-ws-2.0/build.gradle, module_test_10/build.gradle, module_test_9/build.gradle, settings.gradle
This should be merged AFTER the verification plugin is updated an published to 3.3
=> Fix verification to use implementation

newrelic-agent/src/main/resources/newrelic.yml
I removed depreciated features from the default newrelic.yml file according to the [java agent docs](https://docs.newrelic.com/docs/apm/agents/java-agent/configuration/java-agent-configuration-config-file/#distributed-tracing).
This is related to the jira issue [NEWRELIC-651](https://issues.newrelic.com/browse/NEWRELIC-651).
=> removed depreciated features from config

CHANGELOG.md
=> changelog 7.10

gradle.properties, gradle.properties.gha
=> Updating dev version

.github/ISSUE_TEMPLATE/story.md
Adds the story.md file needed by the Workato integration script
N/A
[ Y ] Are your contributions backwards compatible with relevant frameworks and APIs?
[ N ] Does your code contain any breaking changes? Please describe. 
[ N ] Does your code …
=> Add new story.md file to support Workato Jira-GitHub integration

instrumentation/jedis-3.0.0/src/main/java/redis/clients/jedis/Connection_Instrumentation.java, instrumentation/jedis-4.0.0/src/main/java/redis/clients/jedis/Connection_Instrumentation.java
Addresses https://github.com/newrelic/newrelic-java-agent/issues/773
=> Prevent ArrayIndexOutOfBoundsException

.github/ISSUE_TEMPLATE/story.md
Modified the story.md template file to remove reference to "estimates"
N/A
[ Y ] Are your contributions backwards compatible with relevant frameworks and APIs?
[ N ] Does your code contain any breaking changes? Please describe. 
[ N ] Does your …
=> Cleanup story.md template file

instrumentation/spring-webflux-5.0.0/README.md, instrumentation/spring-webflux-5.1.0/README.md
Verified it works around 5.1.0 issue as well but 5.0.x has bigger issues.
https://staging.onenr.io/08dQeqNDdQe
=> NEWRELIC-3249 Add README.md to Spring Webflux 5.1 instrumentation

newrelic-agent/src/main/java/com/newrelic/agent/config/InsightsConfigImpl.java
Increases the default amount of forwarded [custom events](https://docs.newrelic.com/docs/data-apis/custom-data/custom-events/report-custom-event-data/).
=> NEWRELIC-4447 - Increase the Custom Event Reservoir Limit

README.md
=> Update README - Correct stale links

newrelic-agent/src/main/java/com/newrelic/agent/config/CodeLevelMetricsConfigImpl.java, newrelic-agent/src/main/resources/newrelic.yml, newrelic-agent/src/test/java/com/newrelic/agent/config/CodeLevelMetricsConfigImplTest.java, newrelic-agent/src/test/java/com/newrelic/agent/metrics/JsonTraceSegment.java, newrelic-agent/src/test/resources/com/newrelic/agent/config/span_events.yml
=> NR-57169 - Enable CLM by default

instrumentation/jdbc-generic/build.gradle, instrumentation/jdbc-mysql-8.0.11/build.gradle, instrumentation/jdbc-mysql-connection-8.0.11/build.gradle, instrumentation/jdbc-mysql-multihost-connections-8.0.11/build.gradle
Testing the new artifact where the Mysql connector is deployed to.
The old artifact was still updated and caused some hiccups, but seems to have stabilized.
=> NR-00000 - Adding new Mysql package to verify instrumentation

instrumentation/akka-http-core-2.11_10.0.11/.snyk, instrumentation/akka-http-core-2.13_10.1.8/.snyk
Critical and High severity only
=> Add .snyk files to suppress false positives

.github/workflows/README.md, .github/workflows/Release-CopyToS3-prod.yml, .github/workflows/Release-CopyToS3-staging.yml, .github/workflows/Z-sandbox-job.yml, automation/release/send-zip-to-s3.sh
Some release jobs ran in an internal Jenkins instance. That is being decomissioned so those jobs are being migrated to GHA.
NR-26418
=> NR-26418 - migrating release jobs

newrelic-weaver/src/main/java/com/newrelic/weave/utils/WeaveUtils.java
Makes change to @jeffalder commits to include max version.
We provide support and tests for the latest non-lts version.  
=> Run aits for jalder patch 1

CHANGELOG.md, README.md, gradle.properties, gradle.properties.gha
Updates dev version, changelog and header on readme.
=> NR-00000 - Post release updates

newrelic-agent/src/main/java/com/newrelic/bootstrap/BootstrapAgent.java
This PR just cleans up some code in BootstrapAgent premain. There were some print jobs and sys and envvar checks that I think clutter the flow in premain. I just moved all that out into methods and reworded the print statements a little.
I also cleaned up some comments in the same class that needed some editing.
[ ] Are your contributions backwards compatible with …
=> clean premain and some comments

CHANGELOG.md, newrelic-agent/build.gradle
Update snakeyaml lib to v1.33
[X ] Are your contributions backwards compatible with relevant frameworks and APIs?
[ ] …
=> Update snakeyaml lib to v1.33

CHANGELOG.md
This just updates change log to reflect the coming maintenance release for 7.11.1
=> change log for the 7.11.1 changes

functional_test/build.gradle, functional_test/src/test/java/com/newrelic/test/repro1/SpringBootTest.java
Updating some dependency versions.
=> Functional test version bumps

buildSrc/build.gradle, infinite-tracing/build.gradle.kts, newrelic-agent/build.gradle
Upgrading test dependencies to patch security vulnerabilities.
=> NR-66804 - Upgrading test dependencies

CHANGELOG.md, gradle.properties, gradle.properties.gha
Update agent version and changelog
Hold until release is done
=> Post 8.0.0 release

automation/angler/instrumentation_modules.groovy
Adds a script to easily generate the instrumentation module metric names.
=> NR-00000 - Script to generate supportability metric names for angler

newrelic-agent/src/main/java/com/newrelic/bootstrap/BootstrapAgent.java
This is to run the tests on https://github.com/newrelic/newrelic-java-agent/pull/1137
=> NR-84187 Fix ClassCircularityError when agent attaches

CHANGELOG.md
=> CHANGELOG.md updates

CHANGELOG.md
=> update 8.0.0 CHANGELOG

README.md
Updates the header in the README.md
=> Update readme header

newrelic-agent/src/main/java/com/newrelic/agent/instrumentation/InstrumentationImpl.java
=> slight change in how supportability is reported for token.link instrument

instrumentation/netty-3.4/src/main/java/com/agent/instrumentation/netty34/RequestWrapper.java, instrumentation/netty-3.4/src/test/java/netty34/RequestWrapperTest.java, instrumentation/netty-3.8/src/main/java/com/agent/instrumentation/netty38/RequestWrapper.java, instrumentation/netty-3.8/src/test/java/netty38/RequestWrapperTest.java, instrumentation/netty-4.0.0/src/main/java/com/agent/instrumentation/netty40/RequestWrapper.java, instrumentation/netty-4.0.0/src/test/java/netty40/RequestWrapperTest.java, instrumentation/netty-4.0.8/src/main/java/com/agent/instrumentation/netty40/RequestWrapper.java, instrumentation/netty-4.0.8/src/test/java/netty408/RequestWrapperTest.java
=> Internal tests for #1163

newrelic-agent/src/main/java/com/newrelic/agent/Agent.java, newrelic-agent/src/main/java/com/newrelic/agent/util/DelegatingInstrumentation.java, newrelic-agent/src/main/java/com/newrelic/agent/util/InstrumentationWrapper.java, newrelic-agent/src/main/java/com/newrelic/agent/util/UnwindableInstrumentation.java, newrelic-agent/src/main/java/com/newrelic/agent/util/UnwindableInstrumentationImpl.java, newrelic-agent/src/test/java/com/newrelic/agent/util/UnwindableInstrumentationImplTest.java
This is to run the tests on https://github.com/newrelic/newrelic-java-agent/pull/1136
=> Gracefully shutdown the agent if it encounters issues on startup

instrumentation/spring-webflux-5.0.0/README.md, instrumentation/spring-webflux-5.1.0/README.md, instrumentation/spring-webflux-5.3.0/README.md
Some minor language/grammar changes (past => passed).
=> Grammar changes

newrelic-agent/src/main/java/com/newrelic/agent/utilization/DockerData.java, newrelic-agent/src/test/java/com/newrelic/agent/utilization/DockerDataTest.java
Added pertinent test for NR-77066.
Removed unnecessary test for a missing ".scope"
=> Updated DockerData to use a single regex to determine container IDs.

README.md
Fixing the link for the support forum
=> Fixed support link

.github/workflows/GHA-Functional-Tests.yaml
Add retries to the java functional tests.  Also, removes old Github Enterprise logic that we no longer use.
=> add retry logic to java functional tests

.github/workflows/GHA-Functional-Tests.yaml, .github/workflows/Java-Instrumentation-Tests.yml
Make tests more consistent and fix and ID on functional tests.
=> improve consistency across tests. fix id

.github/workflows/X-Reusable-BuildAgent.yml
=> Fix name of build agent workflow

.github/workflows/GHA-Functional-Tests.yaml, .github/workflows/GHA-Unit-Tests.yaml, .github/workflows/Java-Instrumentation-Tests.yml
Adds retry on Unit Tests.  (also sneaks in a minor tweak to the order of some steps)
=> retry on unit tests

.github/workflows/GHA-Scala-Functional-Tests.yaml
Retry scala functional tests. 3 attempts.
Also removes old github enterprise logic.
=> retry on scala functional tests

gradle.properties, gradle.properties.gha
Bumps the agent version in gradle.properties for the agent version 8.2.0 post-release
=> 8.2.0 Post Release

.github/workflows/README.md, .github/workflows/TestSuite-Release.yml, .github/workflows/VerifyInstrumentation-Single.yml
Adding information about each workflow in the .github/workflow readme.
=> GHA workflow documentation

infinite-tracing/build.gradle.kts
=> refactor infinite-tracing with prev test

.github/workflows/GHA-Scala-Functional-Tests.yaml, .github/workflows/GHA-Scala-Instrumentation-Tests.yaml
=> Jacoco codecov scala instrumentation

agent-bridge/src/main/java/com/newrelic/agent/bridge/NoOpTransaction.java, newrelic-agent/src/main/java/com/newrelic/agent/Transaction.java, newrelic-agent/src/main/java/com/newrelic/agent/TransactionApiImpl.java, newrelic-api/src/main/java/com/newrelic/api/agent/NoOpAgent.java, newrelic-api/src/main/java/com/newrelic/api/agent/Transaction.java
Adds methods to the API that are required by the csec agent.
=> NR-115333 - Agent API changes for csec

.github/actions/setup-environment/action.yml, .github/workflows/Create-Custom-Jar.yml, .github/workflows/GHA-Functional-Tests.yaml, .github/workflows/GHA-Scala-Functional-Tests.yaml, .github/workflows/GHA-Scala-Instrumentation-Tests.yaml, .github/workflows/GHA-Unit-Tests.yaml, .github/workflows/Java-Instrumentation-Tests.yml, .github/workflows/Test-AITs.yml, .github/workflows/VerifyInstrumentation-Single.yml, .github/workflows/VerifyInstrumentation.yml, .github/workflows/X-Reusable-BuildAgent.yml, .github/workflows/X-Reusable-VerifyInstrumentation.yml, .github/workflows/publish_main_snapshot.yml, .github/workflows/publish_release.yml, gradle.properties.gha
Simplifies the setup of the environment to build the agent or run tests.
=> Ait deduplication

.github/workflows/GHA-Spotbugs.yml
Updating spotbugs workflow to use the setup-environment action
=> Fix spotbugs

.github/workflows/GHA-Scala-Functional-Tests.yaml, .github/workflows/GHA-Unit-Tests.yaml
use latest codecov action. Current action is 3.1.3
This upgrades from v2 to v3.
=> use latest codecov action

.github/workflows/Java-Instrumentation-Tests.yml, .github/workflows/Test-AITs.yml, .github/workflows/X-Reusable-VerifyInstrumentation.yml
- Simplifies the AIT workflow to use standard environment variables, instead of creating its own.
- Fails AITs and verify instrumentation tests when the agent jar cache misses.
=> GHA workflow improvements

.github/workflows/Test-AITs.yml
Just to re-enable the external test after having fixed it.
=> Restore the external.py to usage

gradle/script/spotbugs-exclude-filter.xml, newrelic-agent/src/main/java/com/newrelic/agent/attributes/AttributesFilter.java, newrelic-agent/src/main/java/com/newrelic/agent/config/AttributesConfigImpl.java, newrelic-agent/src/main/java/com/newrelic/agent/util/asm/AnnotationDetails.java, newrelic-agent/src/test/java/com/newrelic/agent/util/asm/AnnotationDetailsTest.java
Refactor array declarations
- com.newrelic.agent.config.AttributesConfigImpl.DEFAULT_BROWSER_EXCLUDES
- com.newrelic.agent.config.AttributesConfigImpl.DEFAULT_TRANSACTION_EVENTS_EXCLUDES
com.newrelic.agent.config.AttributesConfigImpl.isAttsEnabled(AgentConfig, boolean, String[])
- Calls String[].equals(String), line 105
Implement a sensible hashCode() implementation for com.newrelic.agent.util.asm.AnnotationDetails
=> Final pass of spotbugs changes

.github/workflows/Test-AITs.yml
Re-enable the spring webflux AIT
=> Re-enable the spring webflux AIT

.github/workflows/Test-AITs.yml
Enable security tests lasp_datastore & hsm_record_sql which were disabled
=> NR-25510 NR-25508 enable security AITs with the Datastore app

newrelic-weaver/src/test/java/com/newrelic/weave/weavepackage/CachedWeavePackageTest.java
Added some quick validation tests for the CachedWeavePackage tests
=> Added some quick validation tests

.github/workflows/Test-AITs.yml
Re-enable the Tomcat EE AIT in GHA
=> re-enable tomee test in GHA

.github/workflows/Test-AITs.yml
This test has worked for weeks, but suddenly stopped. Disabling for now, opening a ticket to investigate.
=> Disabling jms AIT

.github/actions/setup-environment/action.yml, newrelic-agent/src/main/java/com/newrelic/agent/config/JbossUtils.java, newrelic-agent/src/main/java/com/newrelic/agent/instrumentation/weaver/ClassWeaverService.java, newrelic-agent/src/main/java/com/newrelic/bootstrap/BootstrapAgent.java, newrelic-agent/src/main/java/com/newrelic/bootstrap/BootstrapLoader.java
Removes duplicate code.
Adds some comments so we know that some things are used in the security agent.
=> Removing duplicate code

agent-model/src/test/java/com/newrelic/agent/model/ErrorEventTest.java, agent-model/src/test/java/com/newrelic/agent/model/SpanEventTest.java
This PR adds unit tests for classes in the agent-model package:
- Introduces tests for ErrorEvent class
- Adds additional unit tests for the SpanEvent class
=> Add unittests agent model

agent-bridge/src/test/java/com/newrelic/agent/bridge/external/URISupportTest.java, agent-bridge/src/test/java/com/newrelic/agent/bridge/reflect/ClassReflectionTest.java, gradle/script/java.gradle
=> More unit tests jgb 0912

agent-bridge-datastore/src/test/java/com/newrelic/agent/bridge/datastore/JdbcHelperTest.java, agent-bridge-datastore/src/test/java/com/newrelic/agent/bridge/datastore/R2dbcOperationTest.java, gradle/script/java.gradle, newrelic-agent/src/test/java/com/newrelic/agent/instrumentation/classmatchers/HashSafeClassAndMethodMatcherTest.java, newrelic-agent/src/test/java/com/newrelic/agent/util/ClassUtilsTest.java, newrelic-agent/src/test/java/com/newrelic/agent/util/asm/BytecodeGenProxyBuilderTest.java, newrelic-agent/src/test/java/com/newrelic/agent/util/asm/PatchedClassWriterTest.java
more unit tests and exclusions
=> More unit test. more exclusions

gradle/script/java.gradle
Added exclusions for the inner classes of already excluded classes
=> Added exclusions for the inner classes of already excluded classes

agent-bridge-datastore/src/test/java/com/newrelic/agent/bridge/datastore/R2dbcObfuscatorTest.java
This PR adds unit tests for the SQL obfuscator methods in agent-bridge-datastore/.../R2dbcObfuscator.java.
=> Add coverage r2dbc

newrelic-agent/src/test/java/com/newrelic/agent/instrumentation/AgentWrapperTest.java, newrelic-agent/src/test/java/com/newrelic/agent/instrumentation/InstrumentationUtilsTest.java, newrelic-agent/src/test/java/com/newrelic/agent/instrumentation/InvocationPointTest.java
=> more unit tests

newrelic-agent/src/test/java/com/newrelic/agent/MockRPMService.java, newrelic-agent/src/test/java/com/newrelic/agent/profile/ProfilerServiceV2Test.java, newrelic-agent/src/test/java/com/newrelic/agent/profile/v2/ProfileSessionTest.java, newrelic-agent/src/test/java/com/newrelic/agent/util/asm/UtilsTest.java
=> a few more tests

functional_test/src/test/java/com/newrelic/agent/profile/method/MethodInfoWithLineNumbersTest.java, newrelic-agent/src/test/java/com/newrelic/agent/database/DefaultExplainPlanExecutorTest.java, newrelic-agent/src/test/java/com/newrelic/agent/profile/TestFileWithLineNumbers.java, newrelic-agent/src/test/java/com/newrelic/agent/profile/method/MethodInfoFactoryTest.java, newrelic-agent/src/test/java/com/newrelic/agent/profile/method/MethodInfoTest.java
=> more tests

buildSrc/build.gradle, functional_test/build.gradle, instrumentation-test/build.gradle, instrumentation/aws-java-sdk-dynamodb-2.15.34/build.gradle, instrumentation/graphql-java-16.2/build.gradle, instrumentation/graphql-java-17.0/build.gradle, instrumentation/jboss-7/build.gradle, instrumentation/okhttp-4.0.0/build.gradle, instrumentation/solr-jmx-7.0.0/build.gradle, instrumentation/wildfly-8-PORT/build.gradle, newrelic-agent/build.gradle
Removes a few redundant repository configurations.
=> Removing redundant repository config

instrumentation-test/src/test/java/com/newrelic/agent/introspec/internal/IntrospectorRPMConnectServiceTest.java
=> introspector rpm connect test

.github/workflows/Test-AITs.yml, newrelic-agent/src/main/resources/META-INF/excludes
Re-enable Open/Websphere liberty AITs and fixes how transaction initialization for Open Liberty 21
=> NR-25519 Re-enable Open/Websphere liberty AITs and fix transaction initialization for Open Liberty 21

instrumentation-test/src/test/java/com/newrelic/agent/introspec/internal/IntrospectorRPMServiceTest.java, newrelic-agent/src/test/java/com/newrelic/agent/instrumentation/tracing/DelegatingTraceDetailsTest.java, newrelic-agent/src/test/java/com/newrelic/agent/instrumentation/tracing/FlyweightTraceMethodVisitorTest.java
=> flyweight and trace details tests

gradle/script/java.gradle, newrelic-agent/src/test/java/com/newrelic/agent/instrumentation/tracing/TraceClassVisitorTests.java
=> more unit tests, another exclusion

newrelic-agent/src/test/java/com/newrelic/agent/application/PriorityApplicationNameTest.java
Quick win on PriorityApplicationName
=> add tests to PriorityAppName

gradle.properties
Security agent for next APM release
=> Security agent version bump to 1.0.4 public preview

newrelic-agent/src/test/java/com/newrelic/agent/instrumentation/MethodBuilderTest.java
=> Should be pretty good coverage on MethodBuilder

infinite-tracing/src/main/java/com/newrelic/InfiniteTracing.java, infinite-tracing/src/test/java/com/newrelic/ChannelManagerTest.java, infinite-tracing/src/test/java/com/newrelic/InfiniteTracingTest.java
=> add some mroe test coverage

newrelic-agent/src/test/java/com/newrelic/agent/instrumentation/weaver/ClassWeaverServiceTest.java
=> A good chunk of ClassWeaverService

gradle/script/java.gradle, instrumentation-test/src/main/java/com/newrelic/agent/introspec/internal/ErrorImpl.java, instrumentation-test/src/test/java/com/newrelic/agent/introspec/internal/ErrorImplTest.java, instrumentation-test/src/test/java/com/newrelic/agent/introspec/internal/ExternalRequestImplTest.java, instrumentation-test/src/test/java/com/newrelic/agent/introspec/internal/FailingWeavePackageListenerTest.java, instrumentation-test/src/test/java/com/newrelic/agent/introspec/internal/HttpServerLocatorTest.java
Tests for classes in instrumentation-test.
=> Tests for test fixtures

newrelic-agent/src/test/java/com/newrelic/agent/instrumentation/weaver/ClassWeaverServiceTest.java
=> Added a few more tests for ClassWeaverService

newrelic-agent/src/test/java/com/newrelic/agent/extension/util/ExtensionConversionUtilityTest.java, newrelic-agent/src/test/java/com/newrelic/agent/extension/util/MethodMapperTest.java, newrelic-agent/src/test/java/com/newrelic/agent/extension/util/MethodMatcherUtilityTest.java
Adds a couple more tests in newrelic.agent.extension.util classes, mostly exception handlers.
=> Add tests extension util

newrelic-agent/src/main/java/com/newrelic/agent/instrumentation/weaver/preprocessors/AgentPostprocessors.java
Resolves https://github.com/newrelic/newrelic-java-agent/issues/1073
This PR solves the problem described below by explicitly calling `AgentPostprocessors.setTracedWeaveInstrumentationDetails` before `AgentPostprocessors.postprocess` will be evaluated.
---
For some reason `AgentPostprocessors.setTracedWeaveInstrumentationDetails` was never getting called:
https://github.com/newrelic/newrelic-java-agent/blob/a9ed0161c1a0b7989c94145c9c505b02e67a8e16/newrelic-agent/src/main/java/com/newrelic/agent/instrumentation/weaver/preprocessors/AgentPostprocessors.java#L54-L56
Which meant that when calling `AgentPostprocessors.postprocess` on a `UtilityClass` (i.e. Any class in a weave package that doesn't have a `@Weave` or `@SkipIfPresent` annotation on it) the set of …
=> Populate TracedWeaveInstrumentationTracker in AgentPostprocessors

.github/workflows/Snyk_Scan.yml
created a snyk dependency scan workflow to be run on a weekly schedule or to be triggered manually
[Issue #1344](https://github.com/newrelic/newrelic-java-agent/issues/1344)
=> Created Snyk Dependency Scan Workflow

.github/workflows/Test-AITs.yml
This PR re-enables the disabled Play AIT.
=> Remove play from excludes list in Test-AITs.yml

.github/workflows/Release-UpdateSystemConfig.yml
Automating the update of Java agent version on the System Config.
=> Update System config automation

gradle.properties
Bumping new development version
=> Post release version bump

.github/workflows/Test-AITs.yml
Add SNAP back into the AITs workflow.
=> Remove snap from excludes list in Test-AITs.yml

newrelic-agent/src/main/java/com/newrelic/agent/config/AgentConfigImpl.java
DO NOT MERGE
This is just running the tests on PR https://github.com/newrelic/newrelic-java-agent/pull/1532
=> NR-164405 Fix Package Exclusion Issue with com.nr and com.newrelic

.github/pull_request_template.md
=> Make checks in pull_request_template render as actual checkboxes

instrumentation/servlet-2.4/src/main/java/com/nr/instrumentation/servlet24/ServletHelper.java, instrumentation/servlet-5.0/src/main/java/com/nr/instrumentation/servlet5/ServletHelper.java, instrumentation/servlet-6.0/src/main/java/com/nr/instrumentation/servlet6/ServletHelper.java, instrumentation/spring-4.3.0/src/main/java/com/nr/agent/instrumentation/SpringControllerUtility.java, newrelic-agent/src/main/java/com/newrelic/agent/Transaction.java, newrelic-agent/src/main/java/com/newrelic/agent/TransactionApiImpl.java, newrelic-agent/src/main/java/com/newrelic/agent/transaction/HigherPriorityTransactionNamingPolicy.java, newrelic-agent/src/main/java/com/newrelic/agent/transaction/SameOrHigherPriorityTransactionNamingPolicy.java, newrelic-agent/src/main/java/com/newrelic/agent/transaction/TransactionNamingUtility.java
Resolves #1530 
Adds logging around code which sets a transaction name.
=> Additional transaction naming logging

build.gradle, instrumentation/apache-struts-2.0/build.gradle, instrumentation/spring-3.0.0/build.gradle, instrumentation/spring-4.0.0/build.gradle, instrumentation/spring-4.2.0/build.gradle, instrumentation/spring-4.3.0/build.gradle, instrumentation/spring-cache-3.1.0/build.gradle, newrelic-agent/build.gradle
Upgrading JFR daemon to get the Okhttp upgrade
=> Upgrading JFR daemon

gradle.properties
Bump CSEC Java Agent version to 1.0.6
=> csec agent version bump to 1.0.6

gradle.properties
Post release update(s) for the Java Agent v8.7.0
=> 8.7.0 post-release

CHANGELOG.md
Quick tweak to the Release notes changelog
=> Update 8.7.0 release change-log JFR dependency

.github/workflows/Test-AITs.yml
=> disable inf tracing ait

newrelic-api/src/main/java/com/newrelic/api/agent/NewRelic.java
The goal of this PR is to make it easier to implement our static API.  There's no need to rewrite `recordMetric`, `incrementCounter` etc on `NewRelic`.  Instead, it's enough to provide an agent implementation and implement the `MetricAggregator`.
This also makes it clear that the method on `NewRelic` are just helper methods.
Github Actions when a pull request is made. …
=> Implement some NewRelic api methods

instrumentation/reactor-3.3.0/src/main/java/com/nr/instrumentation/ReactorConfig.java, instrumentation/reactor-3.3.0/src/main/java/com/nr/instrumentation/reactor/TokenLinkingSubscriber.java, instrumentation/reactor-3.3.0/src/main/java/reactor/core/publisher/Hooks_Instrumentation.java, instrumentation/reactor-3.3.0/src/main/java/reactor/core/publisher/LambdaMonoSubscriber_Instrumentation.java, instrumentation/reactor-3.3.0/src/main/java/reactor/core/publisher/LambdaSubscriber_Instrumentation.java, instrumentation/reactor-3.3.0/src/main/java/reactor/core/scheduler/InstantPeriodicWorkerTask_Instrumentation.java, instrumentation/reactor-3.3.0/src/main/java/reactor/core/scheduler/PeriodicWorkerTask_Instrumentation.java, instrumentation/reactor-3.3.0/src/main/java/reactor/core/scheduler/SchedulerTask_Instrumentation.java, instrumentation/reactor-3.3.0/src/main/java/reactor/core/scheduler/Schedulers_Instrumentation.java, instrumentation/reactor-3.3.0/src/main/java/reactor/core/scheduler/WorkerTask_Instrumentation.java, instrumentation/reactor-3.3.0/src/main/java/reactor/ipc/netty/http/server/HttpServerHandler_Skip.java, instrumentation/reactor-3.3.0/src/main/java/reactor/netty/http/server/HttpTrafficHandler_Skip.java, instrumentation/reactor-3.3.0/src/test/java/com/nr/agent/instrumentation/TransactionPropagationTest.java
Fixes some copyright blobs that had the wrong year.
Adds copyright to some files that had it missing.
=> Fixing copyright on reactor-3.3.0 module

instrumentation/spring-webclient-5.0/src/main/java/com/nr/agent/instrumentation/spring_webclient/Util.java, instrumentation/spring-webclient-5.0/src/test/java/com/nr/instrumentation/WebClientTest.java, instrumentation/spring-webclient-5.0/src/test/resources/spans.yml
=> Addition of Spring Webclient response code

.github/workflows/Release-UpdateSystemConfig.yml
Neither staging nor EU need the version update anymore.
This PR removes the code that updated both.
=> Remove staging/EU system config

gradle.properties
CSEC Java Agent Release Bump 1.0.6 to 1.0.7 Public Preview
=> Update CSEC agent to 1.0.7 Public Preview

gradle.properties
=> 8.8.0 post release

CHANGELOG.md
Add deprecation notices from 8.8.0 to 8.8.1
=> Update CHANGELOG.md with Deprecations 8.8.1

instrumentation/httpclient-5.0/src/main/java/com/nr/agent/instrumentation/httpclient50/InstrumentationUtils.java
Adding a log message when external is not reported.
=> Adding logging on httpclient-5.0 instrumentation on null response

CHANGELOG.md, gradle.properties
=> Post 8.9.1 updates

instrumentation/glassfish-6/build.gradle
This version failed verifyInstrumentation.
=> Glassfish - ignoring 8.0.0-M2

instrumentation/kafka-clients-node-metrics-1.0.0/build.gradle
Related verifier failure: https://github.com/newrelic/newrelic-java-agent/issues/1765
=> Cap kafka-clients-node-metrics-1.0.0 support

instrumentation/kafka-streams-spans-3.2.0/build.gradle
Related verifier failures: https://github.com/newrelic/newrelic-java-agent/issues/1767
=> Cap kafka-streams-spans-3.2.0 supported versions

gradle.properties
Run tests for #1796 - CSEC Java Agent Version Bump to 1.1.2
=> PR Test run: CSEC Java Agent Version Bump to 1.1.2

instrumentation/glassfish-6/build.gradle
For full details see https://github.com/newrelic/newrelic-java-agent/issues/1806
=> Update glassfish-6 supported versions

README.md
We are changing platform for reporting security vulnerabilities and the change of URL is needed to point researchers to our disclosure process page
[here](https://github.com/newrelic/newrelic-java-agent/blob/main/CONTRIBUTI …
=> README - Security vulnerability reporting URL Changed

.github/workflows/Test-AITs.yml
Pekko instrumentation is not yet in the main branch, but the AIT got merged.
Disabling it.
=> Disabling pekko AIT

newrelic-agent/src/main/java/com/newrelic/agent/service/module/ClassToJarPathSubmitterImpl.java
This field was flagged by Spotbugs as a possible constant. Making it so.
=> Making class field a constant

instrumentation/jdbc-sqlserver/build.gradle
New version is not compatible with our instrumentation
=> Capping jdbc-sqlserver

CHANGELOG.md, gradle.properties
Post v8.11.0 release task: update changelog and agent version in `gradle.properties`
=> Post v8.11.0 release: update changelog and agent version

instrumentation/graphql-java-21.0/build.gradle
Capping versions our current instrumentation applies to.
=> Cap graphql-21 instrumentation

gradle.properties
Implements: https://github.com/newrelic/newrelic-java-agent/pull/1867
=> Bump csec version to 1.2.1

gradle.properties
=> Test run for: Bump csec version to 1.3.0. https://github.com/newrelic/newrelic-java-agent/pull/1896

instrumentation/aws-bedrock-runtime-2.20/README.md, instrumentation/aws-bedrock-runtime-2.20/src/main/java/llm/models/ModelInvocation.java, instrumentation/aws-bedrock-runtime-2.20/src/main/java/llm/models/ai21labs/jurassic/JurassicModelInvocation.java, instrumentation/aws-bedrock-runtime-2.20/src/main/java/llm/models/amazon/titan/TitanModelInvocation.java, instrumentation/aws-bedrock-runtime-2.20/src/main/java/llm/models/anthropic/claude/ClaudeModelInvocation.java, instrumentation/aws-bedrock-runtime-2.20/src/main/java/llm/models/cohere/command/CommandModelInvocation.java, instrumentation/aws-bedrock-runtime-2.20/src/main/java/llm/models/cohere/command/README.md, instrumentation/aws-bedrock-runtime-2.20/src/main/java/llm/models/meta/llama2/Llama2ModelInvocation.java, instrumentation/aws-bedrock-runtime-2.20/src/test/java/llm/events/LlmEventTest.java, instrumentation/aws-bedrock-runtime-2.20/src/test/java/llm/models/ai21labs/jurassic/JurassicModelInvocationTest.java, instrumentation/aws-bedrock-runtime-2.20/src/test/java/llm/models/amazon/titan/TitanModelInvocationTest.java, instrumentation/aws-bedrock-runtime-2.20/src/test/java/llm/models/anthropic/claude/ClaudeModelInvocationTest.java, instrumentation/aws-bedrock-runtime-2.20/src/test/java/llm/models/cohere/command/CommandModelInvocationTest.java, instrumentation/aws-bedrock-runtime-2.20/src/test/java/llm/models/meta/llama2/Llama2ModelInvocationTest.java, newrelic-api/src/main/java/com/newrelic/api/agent/LlmTokenCountCallback.java
Mostly just formatting but also one potential bug fix related to using the correct message index when calculating token usage.
=> AIM: Cleanup and bug fix

newrelic-agent/build.gradle, newrelic-agent/src/main/java/com/newrelic/agent/jfr/JfrService.java
=> Update Realtime Profiling Instance Naming

CHANGELOG.md, gradle.properties
=> Update changelog and agent snapshot version post 8.13.0

newrelic-scala3-api/build.gradle.kts
Resolves #1958 
Verified that the artifact shows up locally and in staging. The artifact is viewable in sonatype now.
=> Update scala3 artifact publishing

gradle.properties, newrelic-agent/src/main/java/com/newrelic/agent/instrumentation/ClassTransformerServiceImpl.java, newrelic-agent/src/test/java/com/newrelic/agent/config/ConfigFileHelperTest.java
Closes #2006 
Dup of PR https://github.com/newrelic/newrelic-java-agent/pull/2006 to run test workflows
=> Bump csec to v1.4.1

dev-tools/live-templates
Creates a file that contains live templates with common pieces of code used in instrumentation modules.
=> Live templates

dev-tools/live-templates
Updates to live templates
- Weave template will ignore anything after the first '_' in the class name
- getConfig template
=> Live templates updates

.github/workflows/dependency-submission.yml
* added section to set gradle.properties
=> Update dependency-submission Workflow

instrumentation/lettuce-6.0/build.gradle
Related: https://github.com/newrelic/newrelic-java-agent/issues/2119
=> Cap lettuce-6.0 instrumentation at 6.5.0.RELEASE

.github/workflows/dependency-submission.yml
* add `instrumentation` to the exclude-configuration
* fix typo
=> Update the Dependency Submission Workflow

newrelic-agent/src/main/resources/newrelic.yml
Updates the sample yml file with `send_jvm_props` and `obfuscate_jvm_props`
=> Add jvm prop settings to example yml file

newrelic-agent/src/main/java/com/newrelic/agent/config/SuperAgentIntegrationConfigImpl.java
Remove [dead code](https://newrelic.github.io/newrelic-java-agent/spotbugs/main/newrelic-agent-spotbugs-results/#Warnings_STYLE) from super agent config class
=> Dodgy code removal

.github/dependabot.yml, .github/workflows/dependency-submission.yml
Update the submitted dependency graph:
* add inclusion configuration to only add dependencies that are part of the **_shadowIntoJar_** and **_jarIntoJar_** configurations
* add exclusion to explicitly exclude any dependencies in the **_instrumentation_** module
=> Update Dependency Graph Exclusions

.github/workflows/Test-AITs.yml
=> Reenable pekko in AITs workflow

instrumentation/netty-4.1.16/src/main/java/com/agent/instrumentation/netty4116/Http2RequestHeaderWrapper.java
=> Grpc updates - Forked PR tests

instrumentation/httpclient-5.0/src/main/java/org/apache/hc/client5/http/async/HttpAsyncClient_Instrumentation.java, instrumentation/httpclient-5.0/src/main/java/org/apache/hc/core5/http/nio/support/BasicRequestProducer_Instrumentation.java
Potential fix for https://new-relic.atlassian.net/browse/NR-357516
=> Fix memory issue with httpclient-5.0 instrumentation

CHANGELOG.md, gradle.properties
=> Post Release Tasks for 8.19.0 Release

instrumentation/netty-reactor-0.9.0/src/main/java/reactor/core/publisher/MonoFlatMap_Instrumentation.java, instrumentation/reactor-3.3.0/src/main/java/reactor/core/publisher/MonoFlatMap_Instrumentation.java
=> Add Instrumentation for Reactor MonoFlatMap

instrumentation/opentelemetry-sdk-extension-autoconfigure-1.28.0/src/main/java/com/nr/agent/instrumentation/header/utils/HeaderType.java, instrumentation/opentelemetry-sdk-extension-autoconfigure-1.28.0/src/main/java/com/nr/agent/instrumentation/header/utils/W3CTraceParentHeader.java, instrumentation/opentelemetry-sdk-extension-autoconfigure-1.28.0/src/main/java/com/nr/agent/instrumentation/header/utils/W3CTraceParentValidator.java, instrumentation/opentelemetry-sdk-extension-autoconfigure-1.28.0/src/main/java/io/opentelemetry/sdk/trace/NRSpanBuilder.java
Resolves https://github.com/newrelic/newrelic-java-agent/issues/2297
=> Fix broken trace propagation with w3c headers

CHANGELOG.md, gradle.properties
Update changelog and snapshot version
=> 8.20.0 postrelease tasks

instrumentation/netty-reactor-0.9.0/src/main/java/reactor/core/publisher/MonoFlatMap_Instrumentation.java, instrumentation/reactor-3.3.0/src/main/java/reactor/core/publisher/MonoFlatMap_Instrumentation.java
=> Enhance Visibility Into Reactor FlatMapMain

instrumentation-test/src/main/java/com/newrelic/agent/introspec/SpanEvent.java, instrumentation-test/src/main/java/com/newrelic/agent/introspec/internal/SpanEventImpl.java, instrumentation/opentelemetry-sdk-extension-autoconfigure-1.28.0/src/test/java/io/opentelemetry/agent/otelhybrid/AssertionEvaluator.java, instrumentation/opentelemetry-sdk-extension-autoconfigure-1.28.0/src/test/java/io/opentelemetry/agent/otelhybrid/HybridAgentTest.java
Resolves https://github.com/newrelic/newrelic-java-agent/issues/2311
=> Otel cross agent tests

infinite-tracing/build.gradle.kts
Resolves #2336 
Bring in the updated infinite-tracing-protobuf artifact to address reported security issues.
=> Infinite tracing security fix

instrumentation/jedis-5.0.0/build.gradle
Related to https://github.com/newrelic/newrelic-java-agent/issues/2349
=> Cap jedis-5.0.0 instrumentation

newrelic-agent/src/main/java/com/newrelic/agent/transport/DataSenderImpl.java
Log connection errors at `SEVERE` level
Resolves #2326
=> Connection errors now logged at SEVERE

newrelic-agent/src/main/java/com/newrelic/agent/utilization/AzureAppService.java, newrelic-agent/src/main/java/com/newrelic/agent/utilization/UtilizationService.java, newrelic-agent/src/test/java/com/newrelic/agent/utilization/AzureAppServiceTest.java
Check for the 3 env vars we need for Azure App Services linking and send them up.
Resolves: https://github.com/newrelic/newrelic-java-agent/issues/2322
=> Linking metadata for Azure App services

buildSrc/src/main/java/com/nr/builder/publish/PublishConfig.java
Updates the snapshot publish URL for the migrated publish flow.
=> Correct SNAPSHOT publish url

buildSrc/src/main/java/com/nr/builder/publish/PublishConfig.java
Snapshot url was still slightly incorrect.
=> Fix snapshot URL again

newrelic-agent/src/main/java/com/newrelic/bootstrap/BootstrapAgent.java
Resolves #2431 
This allows applications to be selectively skipped based on the startup main class or executable jar file extracted from the command line. This is handy in situations where the "JAVA_TOOL_OPTIONS" environment variable contains the -javaagent flag but we don't want to apply the instrumentation to all java apps in the environment.
The skip list is configured via the `NEW_RELIC_STARTUP_JAVA_ARTIFACT_SKIPS` environment variable. This is a comma separated list of main classes, executable jar files or Java based tools/apps that the agent should NOT instrument.
`export NEW_RELIC_STARTUP_JAVA_ARTIFACT_SKIPS=keytool,myapp.jar,IgnoreThisClass`
=> Skip config implementation

CHANGELOG.md, gradle.properties
Update gradle.properties and CHANGELOG.md for the 8.23.0 release
=> Java agent post release 8.23.0

newrelic-agent/src/main/java/com/newrelic/agent/service/analytics/InsightsServiceImpl.java, newrelic-agent/src/main/java/com/newrelic/agent/service/logging/LogSenderServiceImpl.java
This PR improves logging message clarity in the New Relic Java agent by updating error messages when null attributes are encountered during event processing.
Resolves [#2244](https://github.com/newrelic/newrelic-java-agent/issues/2244)
N/A
[NR-373119]: https://new-relic.atlassian.net/browse/NR-373119?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> #2244: Clarify logging messages for invalid attributes on custom events and logging events

instrumentation/opentelemetry-sdk-extension-autoconfigure-1.28.0/src/main/java/com/nr/agent/instrumentation/utils/span/AttributeKey.java, instrumentation/opentelemetry-sdk-extension-autoconfigure-1.28.0/src/main/java/com/nr/agent/instrumentation/utils/span/AttributeType.java, instrumentation/opentelemetry-sdk-extension-autoconfigure-1.28.0/src/main/java/io/opentelemetry/sdk/trace/ExitTracerSpan.java, instrumentation/opentelemetry-sdk-extension-autoconfigure-1.28.0/src/main/java/io/opentelemetry/sdk/trace/NRSpanBuilder.java, instrumentation/opentelemetry-sdk-extension-autoconfigure-1.28.0/src/main/resources/attribute-mappings.json, instrumentation/opentelemetry-sdk-extension-autoconfigure-1.28.0/src/test/java/com/nr/agent/instrumentation/utils/span/AttributeMapperTest.java, instrumentation/opentelemetry-sdk-extension-autoconfigure-1.28.0/src/test/resources/attribute-mappings.json
- Attribute mappings JSON file completed
- First pass at converting mappings to use new AttributeMapper impl
All existing tests pass.
=> OTel attribute mapping - Completed JSON, first pass of mappings

newrelic-agent/build.gradle
Update JFR dependency to v1.15.0
=> Bump JFR version

instrumentation/aws-java-sdk-dynamodb-1.11.106/build.gradle
=> Optimize verify range
